import Foundation

extension MojiAlphabetData {
    static let kanjiMedia = MojiPageDefinition(
        page: .kanji(.media),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "online",
                title: "Online",
                subtitle: "Phones, posts and the internet",
                columns: 4,
                cells: [
                    .kanji("表", "hyou", "ひょう", "express, chart"),
                    .kanji("機", "ki", "き", "machine, chance"),
                    .kanji("受", "u(keru)", "う(ける)", "receive"),
                    .kanji("設", "setsu", "せつ", "set up"),
                    .kanji("保", "ho", "ほ", "keep, preserve"),
                    .kanji("面", "men", "めん", "surface, mask"),
                    .kanji("告", "koku", "こく", "announce"),
                    .kanji("組", "kumi", "くみ", "group, assemble"),
                    .kanji("投", "na(geru)", "な(げる)", "throw"),
                    .kanji("打", "u(tsu)", "う(つ)", "strike, type"),
                    .kanji("検", "ken", "けん", "examine"),
                    .kanji("配", "hai", "はい", "distribute"),
                    .kanji("注", "chuu", "ちゅう", "pour, attention"),
                    .kanji("録", "roku", "ろく", "recording"),
                    .kanji("存", "son", "そん", "exist"),
                    .kanji("帯", "tai", "たい", "belt, zone"),
                    .kanji("携", "kei", "けい", "portable (携帯)"),
                    .kanji("索", "saku", "さく", "search (検索)")
                ]
            ),
            MojiSectionDefinition(
                key: "media",
                title: "Media & internet",
                subtitle: "Posts, edits, shows and reviews",
                columns: 4,
                cells: [
                    .kanji("画", "ga", "が", "image, plan"),
                    .kanji("演", "en", "えん", "perform"),
                    .kanji("局", "kyoku", "きょく", "bureau, station"),
                    .kanji("放", "hou", "ほう", "release, broadcast"),
                    .kanji("展", "ten", "てん", "exhibition, unfold"),
                    .kanji("視", "shi", "し", "look at (視聴)"),
                    .kanji("映", "ei", "えい", "reflect, project"),
                    .kanji("賞", "shou", "しょう", "prize"),
                    .kanji("写", "sha", "しゃ", "copy, photograph"),
                    .kanji("評", "hyou", "ひょう", "review, evaluate"),
                    .kanji("音", "oto", "おと", "sound"),
                    .kanji("歌", "uta", "うた", "song"),
                    .kanji("批", "hi", "ひ", "criticize"),
                    .kanji("券", "ken", "けん", "ticket"),
                    .kanji("編", "hen", "へん", "edit"),
                    .kanji("除", "nozo(ku)", "のぞ(く)", "remove"),
                    .kanji("舞", "ma(u)", "ま(う)", "flutter, dance (舞台)"),
                    .kanji("劇", "geki", "げき", "drama"),
                    .kanji("印", "in", "いん", "mark, seal"),
                    .kanji("宣", "sen", "せん", "proclaim"),
                    .kanji("芸", "gei", "げい", "performing arts"),
                    .kanji("聴", "ki(ku)", "き(く)", "listen"),
                    .kanji("了", "ryou", "りょう", "finish (了解)"),
                    .kanji("版", "han", "はん", "edition"),
                    .kanji("曲", "kyoku", "きょく", "tune, bend"),
                    .kanji("削", "kezu(ru)", "けず(る)", "delete, shave"),
                    .kanji("載", "no(seru)", "の(せる)", "publish, load"),
                    .kanji("著", "cho", "ちょ", "author, notable"),
                    .kanji("誌", "shi", "し", "magazine"),
                    .kanji("刊", "kan", "かん", "periodical issue (週刊)"),
                    .kanji("更", "kou", "こう", "renew, further"),
                    .kanji("描", "ega(ku)", "えが(く)", "draw, depict"),
                    .kanji("絵", "e", "え", "painting"),
                    .kanji("掲", "kaka(geru)", "かか(げる)", "post (掲示板)"),
                    .kanji("札", "satsu", "さつ", "bill, tag"),
                    .kanji("奏", "sou", "そう", "play music"),
                    .kanji("騒", "sawa(gu)", "さわ(ぐ)", "make noise"),
                    .kanji("俳", "hai", "はい", "actor"),
                    .kanji("炎", "honoo", "ほのお", "flame (炎上)"),
                    .kanji("刷", "su(ru)", "す(る)", "print (印刷)"),
                    .kanji("稿", "kou", "こう", "draft, post"),
                    .kanji("漫", "man", "まん", "manga, aimless"),
                    .kanji("翻", "hon", "ほん", "translate, flip (翻訳)"),
                    .kanji("覧", "ran", "らん", "look over"),
                    .kanji("弦", "gen", "げん", "string, bowstring (弦楽器)"),
                    .kanji("閲", "etsu", "えつ", "browse (閲覧)"),
                    .kanji("肖", "shou", "しょう", "likeness (肖像)"),
                    .kanji("媒", "bai", "ばい", "medium, go-between (媒体)"),
                    .kanji("譜", "fu", "ふ", "musical score, genealogy (楽譜)"),
                    .kanji("叙", "jo", "じょ", "narrate, confer (叙述)"),
                    .kanji("匿", "toku", "とく", "anonymity, harbor (匿名)"),
                    .kanji("篇", "hen", "へん", "volume, piece of writing (長篇)"),
                    .kanji("抄", "shou", "しょう", "excerpt (抄本)"),
                    .kanji("輯", "shuu", "しゅう", "gather (texts) (特輯)"),
                    .kanji("纂", "san", "さん", "compile (編纂)")
                ]
            ),
            MojiSectionDefinition(
                key: "chat",
                title: "Chat & manga",
                subtitle: "Words from messages, games and comics",
                columns: 4,
                cells: [
                    .kanji("駄", "da", "だ", "useless, no good (駄目)"),
                    .kanji("蘇", "yomigae(ru)", "よみがえ(る)", "revive (蘇る)"),
                    .kanji("謎", "nazo", "なぞ", "riddle, mystery (謎)"),
                    .kanji("煩", "wazura(washii)", "わずら(わしい)", "annoying, trouble (煩わしい)"),
                    .kanji("喧", "ken", "けん", "quarrel, noisy (喧嘩)"),
                    .kanji("濡", "nu(reru)", "ぬ(れる)", "get wet (濡れる)"),
                    .kanji("嬉", "ure(shii)", "うれ(しい)", "glad, happy (嬉しい)"),
                    .kanji("噂", "uwasa", "うわさ", "rumor (噂)"),
                    .kanji("隈", "kuma", "くま", "dark circles, area (界隈)"),
                    .kanji("叶", "kana(u)", "かな(う)", "come true (叶う)"),
                    .kanji("凄", "sugo(i)", "すご(い)", "amazing, awful (凄い)"),
                    .kanji("冴", "sa(eru)", "さ(える)", "be clear, sharp (冴える)"),
                    .kanji("萌", "mo(eru)", "も(える)", "sprout, moe (萌え)"),
                    .kanji("瀕", "hin", "ひん", "on the brink (瀕死)"),
                    .kanji("遥", "haru(ka)", "はる(か)", "far away (遥か)"),
                    .kanji("喋", "shabe(ru)", "しゃべ(る)", "chatter, talk (喋る)"),
                    .kanji("揃", "soro(u)", "そろ(う)", "be all there, match (揃う)"),
                    .kanji("綺", "ki", "き", "pretty (綺麗)"),
                    .kanji("巷", "chimata", "ちまた", "town gossip, alleys (巷)"),
                    .kanji("轟", "todoro(ku)", "とどろ(く)", "roar, thunder (轟く)"),
                    .kanji("貰", "mora(u)", "もら(う)", "receive, get (貰う)"),
                    .kanji("溜", "ta(maru)", "た(まる)", "build up, pool (溜まる)"),
                    .kanji("苛", "ka", "か", "bully, irritate (苛める)"),
                    .kanji("醒", "sei", "せい", "awaken, sober up (覚醒)"),
                    .kanji("劫", "gou", "ごう", "eon, bothersome (億劫)"),
                    .kanji("吞", "no(mu)", "の(む)", "swallow, gulp (吞む)"),
                    .kanji("屑", "kuzu", "くず", "scraps, scum (屑)"),
                    .kanji("這", "ha(u)", "は(う)", "crawl (這う)"),
                    .kanji("閃", "hirame(ku)", "ひらめ(く)", "flash, inspiration (閃き)"),
                    .kanji("淋", "sabi(shii)", "さび(しい)", "desolate (淋しい)"),
                    .kanji("喰", "ku(u)", "く(う)", "devour (喰う)"),
                    .kanji("惹", "hi(ku)", "ひ(く)", "attract (惹かれる)"),
                    .kanji("筈", "hazu", "はず", "should be, expected (筈)"),
                    .kanji("嘩", "ka", "か", "squabble (喧嘩)"),
                    .kanji("馴", "na(reru)", "な(れる)", "tame, familiar (馴染み)"),
                    .kanji("摑", "tsuka(mu)", "つか(む)", "grab, clutch (摑む)"),
                    .kanji("賑", "nigi(yaka)", "にぎ(やか)", "lively, bustling (賑やか)"),
                    .kanji("繫", "tsuna(gu)", "つな(ぐ)", "connect, tie (繫ぐ)")
                ]
            )
        ],
        lessonOrder: "表機受設保面告画組投打演局放検展配視映賞写評音注歌録批存券編除舞劇印宣芸帯聴了版曲削載著誌刊更描絵掲札携奏騒索俳炎刷稿漫翻駄覧弦閲肖媒譜叙蘇謎匿篇煩喧濡嬉噂隈叶凄抄冴萌瀕遥喋揃綺巷轟貰溜苛醒劫吞屑這閃淋喰惹筈嘩馴摑賑輯繫纂"
    )
}
