import Foundation

extension MojiAlphabetData {
    static let kanjiCity = MojiPageDefinition(
        page: .kanji(.city),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "town",
                title: "Streets & buildings",
                subtitle: "Towns, shops, stations and halls",
                columns: 4,
                cells: [
                    .kanji("国", "kuni", "くに", "country"),
                    .kanji("部", "bu", "ぶ", "section, club"),
                    .kanji("市", "shi", "し", "city"),
                    .kanji("場", "ba", "ば", "place, scene"),
                    .kanji("京", "kyou", "きょう", "capital"),
                    .kanji("公", "kou", "こう", "public"),
                    .kanji("都", "to", "と", "metropolis"),
                    .kanji("区", "ku", "く", "ward"),
                    .kanji("県", "ken", "けん", "prefecture"),
                    .kanji("道", "michi", "みち", "road, path"),
                    .kanji("所", "tokoro", "ところ", "spot, where"),
                    .kanji("村", "mura", "むら", "village"),
                    .kanji("町", "machi", "まち", "town"),
                    .kanji("建", "ta(teru)", "た(てる)", "build"),
                    .kanji("施", "shi", "し", "carry out, facility"),
                    .kanji("宮", "miya", "みや", "shrine, palace"),
                    .kanji("席", "seki", "せき", "seat"),
                    .kanji("店", "mise", "みせ", "shop"),
                    .kanji("銀", "gin", "ぎん", "silver"),
                    .kanji("門", "mon", "もん", "gate"),
                    .kanji("段", "dan", "だん", "step, stairs"),
                    .kanji("階", "kai", "かい", "floor (story)"),
                    .kanji("路", "ro", "ろ", "route"),
                    .kanji("図", "zu", "ず", "map, diagram"),
                    .kanji("室", "shitsu", "しつ", "room"),
                    .kanji("橋", "hashi", "はし", "bridge"),
                    .kanji("館", "kan", "かん", "hall, building"),
                    .kanji("屋", "ya", "や", "roof, -ya store"),
                    .kanji("園", "en", "えん", "garden, park"),
                    .kanji("駅", "eki", "えき", "station"),
                    .kanji("城", "shiro", "しろ", "castle"),
                    .kanji("築", "chiku", "ちく", "architecture"),
                    .kanji("居", "i(ru)", "い(る)", "be (present)"),
                    .kanji("庫", "ko", "こ", "warehouse"),
                    .kanji("街", "machi", "まち", "streets, downtown"),
                    .kanji("邸", "tei", "てい", "mansion, residence (邸宅)"),
                    .kanji("郵", "yuu", "ゆう", "mail"),
                    .kanji("堂", "dou", "どう", "hall, temple (食堂)"),
                    .kanji("倉", "kura", "くら", "granary, depot (倉庫)"),
                    .kanji("舎", "sha", "しゃ", "quarters, building (校舎)"),
                    .kanji("泊", "to(maru)", "と(まる)", "stay overnight"),
                    .kanji("郊", "kou", "こう", "suburbs (郊外)"),
                    .kanji("棟", "tou", "とう", "building wing, ridge (病棟)"),
                    .kanji("舗", "ho", "ほ", "storefront, pave (舗装)"),
                    .kanji("荘", "sou", "そう", "villa, inn (別荘)"),
                    .kanji("壇", "dan", "だん", "platform, stage (壇上)"),
                    .kanji("架", "ka", "か", "span (a bridge), rack (架空)"),
                    .kanji("亭", "tei", "てい", "inn, restaurant (料亭)"),
                    .kanji("塔", "tou", "とう", "tower")
                ]
            ),
            MojiSectionDefinition(
                key: "directions",
                title: "Directions",
                subtitle: "Up, down, near, far and the four winds",
                columns: 4,
                cells: [
                    .kanji("中", "naka", "なか", "middle, inside"),
                    .kanji("上", "ue", "うえ", "up, above"),
                    .kanji("東", "higashi", "ひがし", "east"),
                    .kanji("内", "uchi", "うち", "within"),
                    .kanji("方", "kata", "かた", "direction, person"),
                    .kanji("外", "soto", "そと", "outside"),
                    .kanji("下", "shita", "した", "down, below"),
                    .kanji("北", "kita", "きた", "north"),
                    .kanji("向", "mu(ku)", "む(く)", "face toward"),
                    .kanji("近", "chika(i)", "ちか(い)", "near"),
                    .kanji("側", "gawa", "がわ", "side (of)"),
                    .kanji("西", "nishi", "にし", "west"),
                    .kanji("南", "minami", "みなみ", "south"),
                    .kanji("横", "yoko", "よこ", "side, beside"),
                    .kanji("央", "ou", "おう", "center"),
                    .kanji("右", "migi", "みぎ", "right"),
                    .kanji("左", "hidari", "ひだり", "left"),
                    .kanji("角", "kado", "かど", "corner"),
                    .kanji("遠", "too(i)", "とお(い)", "far"),
                    .kanji("隣", "tonari", "となり", "next door"),
                    .kanji("巽", "tatsumi", "たつみ", "southeast (巽)")
                ]
            ),
            MojiSectionDefinition(
                key: "transport",
                title: "Transport",
                subtitle: "Trains, ships and the road",
                columns: 4,
                cells: [
                    .kanji("車", "kuruma", "くるま", "car"),
                    .kanji("線", "sen", "せん", "line, track"),
                    .kanji("港", "minato", "みなと", "harbor"),
                    .kanji("航", "kou", "こう", "navigate"),
                    .kanji("鉄", "tetsu", "てつ", "iron"),
                    .kanji("輪", "wa", "わ", "wheel, ring"),
                    .kanji("船", "fune", "ふね", "ship"),
                    .kanji("停", "tei", "てい", "halt"),
                    .kanji("駐", "chuu", "ちゅう", "park (a car)"),
                    .kanji("搭", "tou", "とう", "get on board, load (搭乗)"),
                    .kanji("舶", "haku", "はく", "ocean liner (船舶)"),
                    .kanji("舟", "fune", "ふね", "boat"),
                    .kanji("符", "fu", "ふ", "token, ticket (切符)"),
                    .kanji("帆", "ho", "ほ", "sail"),
                    .kanji("汽", "ki", "き", "vapor (汽車)"),
                    .kanji("桟", "san", "さん", "jetty, scaffold (桟橋)"),
                    .kanji("舵", "kaji", "かじ", "rudder, helm")
                ]
            )
        ],
        lessonOrder: "国中上部東市内方場京外下公都区県北向近道側所村西町建施車南宮席店線銀門段横港階路図室橋央右館屋園左航鉄輪船駅停城角築居庫遠街邸郵駐堂隣倉舎泊郊棟舗搭荘壇架亭塔舶舟符帆汽巽桟舵"
    )
}
