import Foundation

extension MojiAlphabetData {
    static let kanjiDescribing = MojiPageDefinition(
        page: .kanji(.describing),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "basics",
                title: "Big & small",
                subtitle: "Size, feel, taste and looks",
                columns: 4,
                cells: [
                    .kanji("大", "oo(kii)", "おお(きい)", "big"),
                    .kanji("長", "naga(i)", "なが(い)", "long"),
                    .kanji("新", "atara(shii)", "あたら(しい)", "new"),
                    .kanji("高", "taka(i)", "たか(い)", "tall, expensive"),
                    .kanji("明", "aka(rui)", "あか(るい)", "bright"),
                    .kanji("強", "tsuyo(i)", "つよ(い)", "strong"),
                    .kanji("小", "chii(sai)", "ちい(さい)", "small"),
                    .kanji("多", "oo(i)", "おお(い)", "many"),
                    .kanji("正", "tada(shii)", "ただ(しい)", "correct"),
                    .kanji("安", "yasu(i)", "やす(い)", "cheap, calm"),
                    .kanji("重", "omo(i)", "おも(い)", "heavy"),
                    .kanji("広", "hiro(i)", "ひろ(い)", "wide"),
                    .kanji("少", "suko(shi)", "すこ(し)", "few, a little"),
                    .kanji("難", "muzuka(shii)", "むずか(しい)", "difficult"),
                    .kanji("優", "yasa(shii)", "やさ(しい)", "gentle, superior"),
                    .kanji("低", "hiku(i)", "ひく(い)", "low"),
                    .kanji("若", "waka(i)", "わか(い)", "young"),
                    .kanji("美", "utsuku(shii)", "うつく(しい)", "beautiful"),
                    .kanji("深", "fuka(i)", "ふか(い)", "deep"),
                    .kanji("良", "yo(i)", "よ(い)", "good"),
                    .kanji("古", "furu(i)", "ふる(い)", "old (things)"),
                    .kanji("悪", "waru(i)", "わる(い)", "bad"),
                    .kanji("細", "hoso(i)", "ほそ(い)", "slender, fine"),
                    .kanji("太", "futo(i)", "ふと(い)", "fat, thick"),
                    .kanji("速", "haya(i)", "はや(い)", "fast"),
                    .kanji("危", "abu(nai)", "あぶ(ない)", "dangerous"),
                    .kanji("冷", "tsume(tai)", "つめ(たい)", "cold (to touch)"),
                    .kanji("短", "mijika(i)", "みじか(い)", "short"),
                    .kanji("熱", "atsu(i)", "あつ(い)", "hot (to touch), fever"),
                    .kanji("静", "shizu(ka)", "しず(か)", "quiet"),
                    .kanji("軽", "karu(i)", "かる(い)", "light (weight)"),
                    .kanji("弱", "yowa(i)", "よわ(い)", "weak"),
                    .kanji("暗", "kura(i)", "くら(い)", "dark"),
                    .kanji("甘", "ama(i)", "あま(い)", "sweet"),
                    .kanji("忙", "isoga(shii)", "いそが(しい)", "busy"),
                    .kanji("辛", "kara(i)", "から(い)", "spicy")
                ]
            ),
            MojiSectionDefinition(
                key: "texture",
                title: "Look & feel",
                subtitle: "Texture, temperature and age",
                columns: 4,
                cells: [
                    .kanji("鮮", "sen", "せん", "fresh, vivid"),
                    .kanji("非", "hi", "ひ", "non-, wrong"),
                    .kanji("旧", "kyuu", "きゅう", "former"),
                    .kanji("未", "mi", "み", "not yet"),
                    .kanji("適", "teki", "てき", "suitable"),
                    .kanji("久", "hisa(shii)", "ひさ(しい)", "long time"),
                    .kanji("固", "kata(meru)", "かた(める)", "solidify, firm (固定)"),
                    .kanji("精", "sei", "せい", "precision, vitality"),
                    .kanji("豊", "yuta(ka)", "ゆた(か)", "plentiful"),
                    .kanji("厚", "atsu(i)", "あつ(い)", "thick (slab)"),
                    .kanji("永", "ei", "えい", "eternal"),
                    .kanji("秘", "hi", "ひ", "secret"),
                    .kanji("巨", "kyo", "きょ", "giant"),
                    .kanji("汚", "kitana(i)", "きたな(い)", "dirty"),
                    .kanji("薄", "usu(i)", "うす(い)", "thin, pale"),
                    .kanji("渋", "shibu(i)", "しぶ(い)", "astringent, understated"),
                    .kanji("透", "tou", "とう", "transparent, see through (透明)"),
                    .kanji("既", "sude(ni)", "すで(に)", "already"),
                    .kanji("硬", "kata(i)", "かた(い)", "hard, stiff"),
                    .kanji("賢", "kashiko(i)", "かしこ(い)", "wise"),
                    .kanji("詳", "kuwa(shii)", "くわ(しい)", "detailed"),
                    .kanji("柔", "yawa(rakai)", "やわ(らかい)", "soft"),
                    .kanji("濃", "ko(i)", "こ(い)", "dense, dark (color)"),
                    .kanji("浅", "asa(i)", "あさ(い)", "shallow"),
                    .kanji("軟", "nan", "なん", "pliable, soft (柔軟)"),
                    .kanji("芳", "hou", "ほう", "aromatic, honorable (芳名)"),
                    .kanji("珍", "mezura(shii)", "めずら(しい)", "rare"),
                    .kanji("狭", "sema(i)", "せま(い)", "narrow"),
                    .kanji("暖", "atata(kai)", "あたた(かい)", "warm (climate)"),
                    .kanji("粘", "neba(ru)", "ねば(る)", "sticky, persevere"),
                    .kanji("乾", "kawa(ku)", "かわ(く)", "become dry (乾く)"),
                    .kanji("偉", "era(i)", "えら(い)", "great (admirable)"),
                    .kanji("潤", "uruo(u)", "うるお(う)", "moisten, profit (利潤)"),
                    .kanji("粗", "ara(i)", "あら(い)", "coarse, crude (粗末)"),
                    .kanji("凝", "ko(ru)", "こ(る)", "congeal, be absorbed in"),
                    .kanji("澄", "su(mu)", "す(む)", "limpid, clear (澄む)"),
                    .kanji("臭", "kusa(i)", "くさ(い)", "smelly, stink"),
                    .kanji("涼", "suzu(shii)", "すず(しい)", "cool"),
                    .kanji("燥", "sou", "そう", "parched (乾燥)"),
                    .kanji("薫", "kao(ru)", "かお(る)", "scent, waft (薫る)"),
                    .kanji("濁", "nigo(ru)", "にご(る)", "be muddy, voiced (濁音)"),
                    .kanji("朽", "ku(chiru)", "く(ちる)", "decay, molder"),
                    .kanji("斑", "han", "はん", "spot, speckle (斑点)"),
                    .kanji("艶", "tsuya", "つや", "gloss, charm"),
                    .kanji("匂", "nio(u)", "にお(う)", "smell, give off a scent"),
                    .kanji("爽", "sawa(yaka)", "さわ(やか)", "refreshing"),
                    .kanji("瞭", "ryou", "りょう", "clear, obvious (明瞭)"),
                    .kanji("昧", "mai", "まい", "obscure, absorbed in (三昧)"),
                    .kanji("曖", "ai", "あい", "vague (曖昧)")
                ]
            ),
            MojiSectionDefinition(
                key: "colors",
                title: "Colors",
                subtitle: "From white to indigo",
                columns: 4,
                cells: [
                    .kanji("白", "shiro", "しろ", "white"),
                    .kanji("黒", "kuro", "くろ", "black"),
                    .kanji("赤", "aka", "あか", "red"),
                    .kanji("青", "ao", "あお", "blue"),
                    .kanji("色", "iro", "いろ", "color"),
                    .kanji("緑", "midori", "みどり", "green"),
                    .kanji("黄", "ki", "き", "yellow"),
                    .kanji("彩", "sai", "さい", "color, coloring (色彩)"),
                    .kanji("紅", "kou", "こう", "crimson, deep red (紅葉)"),
                    .kanji("丹", "tan", "たん", "red ochre, painstaking (丹念)"),
                    .kanji("紫", "murasaki", "むらさき", "purple"),
                    .kanji("灰", "hai", "はい", "ash"),
                    .kanji("朱", "shu", "しゅ", "vermilion"),
                    .kanji("紺", "kon", "こん", "navy blue"),
                    .kanji("藍", "ai", "あい", "indigo"),
                    .kanji("褐", "katsu", "かつ", "brown (褐色)")
                ]
            ),
            MojiSectionDefinition(
                key: "qualities",
                title: "Qualities",
                subtitle: "Strict, sharp, gentle, strange and more",
                columns: 4,
                cells: [
                    .kanji("激", "hage(shii)", "はげ(しい)", "violent, intense (激しい)"),
                    .kanji("異", "i", "い", "different, abnormal (異常)"),
                    .kanji("厳", "kibi(shii)", "きび(しい)", "strict, severe (厳しい)"),
                    .kanji("清", "sei", "せい", "clean, clear (清潔)"),
                    .kanji("乱", "mida(reru)", "みだ(れる)", "disorder, riot (混乱)"),
                    .kanji("密", "mitsu", "みつ", "compact, secret (密度)"),
                    .kanji("秀", "shuu", "しゅう", "excel, outstanding (優秀)"),
                    .kanji("緩", "yuru(i)", "ゆる(い)", "loose, gentle (緩い)"),
                    .kanji("貴", "ki", "き", "precious, noble (貴重)"),
                    .kanji("紛", "magi(reru)", "まぎ(れる)", "mix in, confusing (紛らわしい)"),
                    .kanji("仮", "kari", "かり", "temporary, fake (仮)"),
                    .kanji("敏", "bin", "びん", "quick, sensitive (敏感)"),
                    .kanji("裕", "yuu", "ゆう", "ample, wealthy (余裕)"),
                    .kanji("荒", "ara(i)", "あら(い)", "rough, wild (荒い)"),
                    .kanji("豪", "gou", "ごう", "luxurious, Australia (豪華)"),
                    .kanji("微", "bi", "び", "tiny, subtle (微妙)"),
                    .kanji("妙", "myou", "みょう", "uncanny, exquisite (妙)"),
                    .kanji("雅", "ga", "が", "elegant, refined (優雅)"),
                    .kanji("繁", "han", "はん", "busy, luxuriant (繁華街)"),
                    .kanji("魅", "mi", "み", "charm (魅力)"),
                    .kanji("泰", "tai", "たい", "serene, Thailand (安泰)"),
                    .kanji("猛", "mou", "もう", "ferocious (猛暑)"),
                    .kanji("殊", "shu", "しゅ", "particular, especially (特殊)"),
                    .kanji("奇", "ki", "き", "odd, curious (奇妙)"),
                    .kanji("鋭", "surudo(i)", "するど(い)", "sharp, keen (鋭い)"),
                    .kanji("烈", "retsu", "れつ", "vehement, ardent (強烈)"),
                    .kanji("狂", "kuru(u)", "くる(う)", "crazy, go mad (狂う)"),
                    .kanji("淡", "awa(i)", "あわ(い)", "faint, pale (淡い)"),
                    .kanji("虚", "kyo", "きょ", "empty, false (虚しい)"),
                    .kanji("惨", "san", "さん", "miserable, cruel (悲惨)"),
                    .kanji("穏", "oda(yaka)", "おだ(やか)", "calm, gentle (穏やか)"),
                    .kanji("巧", "taku(mi)", "たく(み)", "skillful, clever (巧み)"),
                    .kanji("疎", "so", "そ", "sparse, estranged (過疎)"),
                    .kanji("鈍", "nibu(i)", "にぶ(い)", "dull, blunt (鈍い)"),
                    .kanji("剛", "gou", "ごう", "sturdy, tough (剛健)"),
                    .kanji("酷", "koku", "こく", "cruel, harsh (残酷)"),
                    .kanji("邪", "ja", "じゃ", "wicked, in the way (邪魔)"),
                    .kanji("劣", "oto(ru)", "おと(る)", "inferior (劣る)"),
                    .kanji("朴", "boku", "ぼく", "rustic, artless (素朴)"),
                    .kanji("佳", "ka", "か", "excellent, fine (佳作)"),
                    .kanji("壮", "sou", "そう", "magnificent, robust (壮大)"),
                    .kanji("凡", "bon", "ぼん", "mediocre, ordinary (平凡)"),
                    .kanji("窮", "kyuu", "きゅう", "cramped, destitute (窮屈)"),
                    .kanji("麗", "rei", "れい", "lovely (綺麗)"),
                    .kanji("粋", "sui", "すい", "chic, essence (純粋)"),
                    .kanji("傑", "ketsu", "けつ", "masterpiece, hero (傑作)"),
                    .kanji("拙", "setsu", "せつ", "clumsy, unskilled (稚拙)"),
                    .kanji("庸", "you", "よう", "commonplace (中庸)"),
                    .kanji("醜", "miniku(i)", "みにく(い)", "ugly (醜い)"),
                    .kanji("稀", "mare", "まれ", "seldom, rare (稀に)"),
                    .kanji("旺", "ou", "おう", "vigorous (旺盛)"),
                    .kanji("緻", "chi", "ち", "fine, meticulous (緻密)"),
                    .kanji("辣", "ratsu", "らつ", "harsh, biting (辛辣)"),
                    .kanji("璧", "heki", "へき", "flawless jewel (完璧)")
                ]
            )
        ],
        lessonOrder: "大長新高明強小多正安重広少難優鮮低若美非白深良古悪細旧太激黒速赤青危色異厳未冷適久短熱清固精乱豊静厚軽密永秀秘巨汚緩弱貴紛薄渋透仮暗敏裕既荒硬豪微妙賢詳緑柔雅繁濃魅黄甘彩浅軟泰紅猛芳珍狭殊奇暖鋭烈丹粘狂淡乾虚惨忙紫穏巧疎鈍剛酷辛邪劣朴偉佳潤壮粗凝灰澄凡窮麗臭粋涼朱燥紺薫濁朽傑拙庸藍醜斑褐艶匂稀爽旺緻瞭昧辣曖璧"
    )
}
