import Foundation

extension MojiAlphabetData {
    static let kanjiNames = MojiPageDefinition(
        page: .kanji(.names),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "places",
                title: "Names & places",
                subtitle: "Surnames, prefectures and cities",
                columns: 4,
                cells: [
                    .kanji("藤", "fuji", "ふじ", "wisteria (佐藤)"),
                    .kanji("沢", "sawa", "さわ", "marsh, plenty (沢山)"),
                    .kanji("井", "i", "い", "well (井戸)"),
                    .kanji("岡", "oka", "おか", "knoll (福岡)"),
                    .kanji("佐", "sa", "さ", "aide (佐藤)"),
                    .kanji("阪", "saka", "さか", "Osaka, slope (大阪)"),
                    .kanji("崎", "saki", "さき", "promontory (長崎)"),
                    .kanji("郎", "rou", "ろう", "lad, son (太郎)"),
                    .kanji("浜", "hama", "はま", "beach (横浜)"),
                    .kanji("伊", "i", "い", "Italy (伊藤)"),
                    .kanji("江", "e", "え", "creek, Edo (江戸)"),
                    .kanji("奈", "na", "な", "Nara (奈良)"),
                    .kanji("塚", "tsuka", "つか", "mound (宝塚)"),
                    .kanji("鈴", "suzu", "すず", "small bell (鈴木)"),
                    .kanji("郡", "gun", "ぐん", "county"),
                    .kanji("埼", "sai", "さい", "Saitama (埼玉)"),
                    .kanji("浦", "ura", "うら", "bay shore (浦和)"),
                    .kanji("阿", "a", "あ", "flatter, nook (阿部)"),
                    .kanji("斎", "sai", "さい", "study room, purify (書斎)"),
                    .kanji("仙", "sen", "せん", "hermit sage (仙人)"),
                    .kanji("茨", "ibara", "いばら", "thorn bush (茨城)"),
                    .kanji("潟", "kata", "かた", "lagoon (新潟)"),
                    .kanji("堀", "hori", "ほり", "moat"),
                    .kanji("幌", "horo", "ほろ", "hood, canopy (札幌)"),
                    .kanji("梶", "kaji", "かじ", "scull oar (梶原)"),
                    .kanji("栃", "tochi", "とち", "horse chestnut (栃木)"),
                    .kanji("岐", "ki", "き", "fork, branch off (分岐)"),
                    .kanji("亜", "a", "あ", "sub-, Asia (亜熱帯)"),
                    .kanji("筑", "chiku", "ちく", "ancient zither (筑波)"),
                    .kanji("阜", "fu", "ふ", "hillock (岐阜)"),
                    .kanji("滋", "ji", "じ", "nourish (滋賀)"),
                    .kanji("俣", "mata", "また", "river fork (水俣)"),
                    .kanji("辻", "tsuji", "つじ", "crossroads"),
                    .kanji("那", "na", "な", "Naha, what (那覇)"),
                    .kanji("姓", "sei", "せい", "surname"),
                    .kanji("畿", "ki", "き", "capital area (近畿)"),
                    .kanji("弥", "ya", "や", "ever more (弥生)"),
                    .kanji("庄", "shou", "しょう", "manor, village (庄屋)"),
                    .kanji("呉", "go", "ご", "Wu China, give (呉服)"),
                    .kanji("媛", "hime", "ひめ", "noble lady (愛媛)"),
                    .kanji("釧", "kushiro", "くしろ", "bracelet (釧路)"),
                    .kanji("函", "hako", "はこ", "box, case (函館)"),
                    .kanji("堺", "sakai", "さかい", "boundary (堺市)"),
                    .kanji("窪", "kubo", "くぼ", "hollow, dip (窪み)"),
                    .kanji("畠", "hatake", "はたけ", "field (畠山)"),
                    .kanji("湘", "shou", "しょう", "Xiang River, Shonan (湘南)"),
                    .kanji("諏", "su", "す", "deliberate, Suwa (諏訪)"),
                    .kanji("淀", "yodo", "よど", "pool, stagnate (淀川)"),
                    .kanji("逗", "tou", "とう", "linger, stay (逗留)"),
                    .kanji("奄", "en", "えん", "cover over, Amami (奄美)"),
                    .kanji("嵯", "sa", "さ", "craggy (嵯峨)"),
                    .kanji("佃", "tsukuda", "つくだ", "tilled field (佃煮)"),
                    .kanji("峨", "ga", "が", "lofty peak (嵯峨)"),
                    .kanji("宕", "tou", "とう", "stone shelter, Atago (愛宕)"),
                    .kanji("洛", "raku", "らく", "Kyoto, capital (洛中)"),
                    .kanji("塙", "hanawa", "はなわ", "hill spur"),
                    .kanji("邑", "yuu", "ゆう", "township (都邑)"),
                    .kanji("祁", "ki", "き", "intense, large")
                ]
            ),
            MojiSectionDefinition(
                key: "virtue",
                title: "Wisdom & kindness",
                subtitle: "Virtues and blessings in names",
                columns: 4,
                cells: [
                    .kanji("智", "chi", "ち", "wisdom, intellect (智恵)"),
                    .kanji("靖", "sei", "せい", "peaceful, tranquil (靖国)"),
                    .kanji("孜", "shi", "し", "diligent (孜々)"),
                    .kanji("聡", "sou", "そう", "quick-witted, wise (聡明)"),
                    .kanji("嘉", "ka", "か", "laudable, auspicious"),
                    .kanji("淳", "jun", "じゅん", "simple-hearted, sincere (淳朴)"),
                    .kanji("敦", "ton", "とん", "warm-hearted, earnest"),
                    .kanji("祐", "yuu", "ゆう", "divine help (天祐)"),
                    .kanji("亮", "ryou", "りょう", "lucid, bright"),
                    .kanji("輔", "ho", "ほ", "counsel, aide (輔佐)"),
                    .kanji("郁", "iku", "いく", "perfumed, refined (馥郁)"),
                    .kanji("亨", "kou", "こう", "smooth success (亨通)"),
                    .kanji("欣", "kin", "きん", "elated (欣喜)"),
                    .kanji("禎", "tei", "てい", "felicity, auspicious sign"),
                    .kanji("馨", "kei", "けい", "lingering scent, renown"),
                    .kanji("慧", "kei", "けい", "insight (慧眼)"),
                    .kanji("彬", "hin", "ひん", "refined, well-balanced"),
                    .kanji("匡", "kyou", "きょう", "set right, save"),
                    .kanji("欽", "kin", "きん", "imperial sanction, admire (欽定)"),
                    .kanji("佑", "yuu", "ゆう", "assist, protect (天佑)"),
                    .kanji("渥", "aku", "あく", "gracious, moist"),
                    .kanji("惇", "jun", "じゅん", "kind-hearted, sincere"),
                    .kanji("脩", "shuu", "しゅう", "dried meat, cultivate"),
                    .kanji("允", "in", "いん", "grant, truly (允許)"),
                    .kanji("怜", "rei", "れい", "sharp-witted, tender (怜悧)"),
                    .kanji("悌", "tei", "てい", "brotherly respect (孝悌)"),
                    .kanji("丞", "jou", "じょう", "deputy, assist (丞相)"),
                    .kanji("侑", "yuu", "ゆう", "urge (to eat), help"),
                    .kanji("迪", "teki", "てき", "path, guide (啓迪)"),
                    .kanji("宥", "nada(meru)", "なだ(める)", "soothe, pardon (宥める)"),
                    .kanji("洵", "jun", "じゅん", "truly, in truth"),
                    .kanji("倖", "kou", "こう", "windfall, lucky chance (僥倖)"),
                    .kanji("恕", "jo", "じょ", "forbearance, forgive (寛恕)"),
                    .kanji("誼", "gi", "ぎ", "friendship, intimacy (友誼)"),
                    .kanji("諒", "ryou", "りょう", "appreciate, sincerity (諒承)"),
                    .kanji("叡", "ei", "えい", "sagacity, imperial (叡智)"),
                    .kanji("俐", "ri", "り", "clever (伶俐)"),
                    .kanji("娃", "a", "あ", "pretty girl, beauty"),
                    .kanji("惺", "sei", "せい", "clear-headed, awake"),
                    .kanji("楚", "so", "そ", "neat, thorn bush (清楚)"),
                    .kanji("凛", "rin", "りん", "dignified, crisp cold (凛々しい)"),
                    .kanji("醇", "jun", "じゅん", "mellow, pure (芳醇)"),
                    .kanji("憐", "ren", "れん", "compassion, lovely (可憐)")
                ]
            ),
            MojiSectionDefinition(
                key: "great",
                title: "Strength & greatness",
                subtitle: "Wide, lofty and brave in names",
                columns: 4,
                cells: [
                    .kanji("弘", "kou", "こう", "broaden, widespread (弘法)"),
                    .kanji("彦", "hiko", "ひこ", "young man (in names) (彦)"),
                    .kanji("浩", "kou", "こう", "vast expanse, abundant (浩然)"),
                    .kanji("宏", "kou", "こう", "grand, spacious (宏大)"),
                    .kanji("晋", "shin", "しん", "advance, Jin dynasty"),
                    .kanji("紘", "kou", "こう", "main cord, the world (八紘)"),
                    .kanji("亘", "wata(ru)", "わた(る)", "extend over, span (亘る)"),
                    .kanji("毅", "ki", "き", "resolute, strong-willed (毅然)"),
                    .kanji("肇", "chou", "ちょう", "commence, found"),
                    .kanji("喬", "kyou", "きょう", "tall (tree), proud (喬木)"),
                    .kanji("峻", "shun", "しゅん", "lofty, stern (峻厳)"),
                    .kanji("遼", "ryou", "りょう", "distant, Liao (遼遠)"),
                    .kanji("魁", "kai", "かい", "harbinger, ringleader (首魁)"),
                    .kanji("赳", "kyuu", "きゅう", "valiant (赳々)"),
                    .kanji("孟", "mou", "もう", "eldest, Mencius (孟子)"),
                    .kanji("尭", "gyou", "ぎょう", "Emperor Yao, high"),
                    .kanji("甫", "ho", "ほ", "just begun, Du Fu (杜甫)"),
                    .kanji("侃", "kan", "かん", "upright, forthright"),
                    .kanji("昂", "kou", "こう", "exalted, elated (昂揚)"),
                    .kanji("勁", "kei", "けい", "unbending, strong (勁草)"),
                    .kanji("捷", "shou", "しょう", "nimble, victory (敏捷)"),
                    .kanji("嵩", "kasa", "かさ", "bulk, mount up (嵩む)"),
                    .kanji("滉", "kou", "こう", "vast waters"),
                    .kanji("碩", "seki", "せき", "eminent, great (碩学)"),
                    .kanji("俠", "kyou", "きょう", "chivalry (任俠)"),
                    .kanji("恢", "kai", "かい", "recover, extensive (恢復)"),
                    .kanji("逞", "takuma(shii)", "たくま(しい)", "brawny, robust (逞しい)"),
                    .kanji("驍", "gyou", "ぎょう", "fierce, gallant steed (驍勇)"),
                    .kanji("渾", "kon", "こん", "whole, all-out (渾身)")
                ]
            ),
            MojiSectionDefinition(
                key: "skywater",
                title: "Sky & water",
                subtitle: "Light, dawns, shores and peaks in names",
                columns: 4,
                cells: [
                    .kanji("昌", "shou", "しょう", "prosperous, bright (昌)"),
                    .kanji("旭", "asahi", "あさひ", "rising sun (旭)"),
                    .kanji("曙", "akebono", "あけぼの", "first light (曙)"),
                    .kanji("淵", "fuchi", "ふち", "abyss, deep pool (深淵)"),
                    .kanji("晃", "kou", "こう", "dazzling (晃)"),
                    .kanji("磐", "iwa", "いわ", "bedrock (磐石)"),
                    .kanji("灘", "nada", "なだ", "rough open sea (灘)"),
                    .kanji("堰", "seki", "せき", "weir (堰)"),
                    .kanji("嶺", "mine", "みね", "ridge, divide (分水嶺)"),
                    .kanji("洲", "su", "す", "sandbar, continent (中洲)"),
                    .kanji("巌", "iwao", "いわお", "crag, boulder (巌)"),
                    .kanji("稜", "ryou", "りょう", "ridgeline, edge (稜線)"),
                    .kanji("湊", "minato", "みなと", "port (湊)"),
                    .kanji("渚", "nagisa", "なぎさ", "water's edge, beach (渚)"),
                    .kanji("耀", "you", "よう", "radiance, gleam (耀)"),
                    .kanji("暉", "ki", "き", "sunshine (暉)"),
                    .kanji("汐", "shio", "しお", "evening tide (汐)"),
                    .kanji("黎", "rei", "れい", "dark, dawn of (黎明)"),
                    .kanji("皓", "kou", "こう", "bright white (皓)"),
                    .kanji("洸", "kou", "こう", "sparkling water (洸)"),
                    .kanji("凪", "nagi", "なぎ", "calm at sea (凪)"),
                    .kanji("奎", "kei", "けい", "star of letters (奎)"),
                    .kanji("昴", "subaru", "すばる", "Pleiades (昴)"),
                    .kanji("晏", "an", "あん", "late, peaceful (晏)"),
                    .kanji("晟", "sei", "せい", "bright light (晟)"),
                    .kanji("崚", "ryou", "りょう", "towering peaks (崚)"),
                    .kanji("晨", "shin", "しん", "early morning (晨)"),
                    .kanji("颯", "satsu", "さつ", "breezy, gallant (颯爽)"),
                    .kanji("熙", "ki", "き", "radiant, merry (熙)"),
                    .kanji("澪", "mio", "みお", "water channel (澪)"),
                    .kanji("燎", "ryou", "りょう", "bonfire (燎原)"),
                    .kanji("燦", "san", "さん", "brilliant (燦々)"),
                    .kanji("燿", "you", "よう", "glow (燿)"),
                    .kanji("汀", "tei", "てい", "shoreline, bank (汀)"),
                    .kanji("灼", "shaku", "しゃく", "scorching (灼熱)"),
                    .kanji("昊", "kou", "こう", "summer sky (昊)"),
                    .kanji("昏", "kon", "こん", "dusk, faint (昏睡)"),
                    .kanji("沫", "matsu", "まつ", "splash, spray (飛沫)"),
                    .kanji("穹", "kyuu", "きゅう", "vault of heaven (蒼穹)"),
                    .kanji("焰", "en", "えん", "blaze (焰)"),
                    .kanji("漣", "ren", "れん", "ripples (漣)"),
                    .kanji("煌", "kou", "こう", "glitter (煌めく)"),
                    .kanji("燭", "shoku", "しょく", "candlelight (燭)")
                ]
            ),
            MojiSectionDefinition(
                key: "jewels",
                title: "Jewels & colors",
                subtitle: "Gems, silks and shades in names",
                columns: 4,
                cells: [
                    .kanji("綾", "aya", "あや", "twill, design"),
                    .kanji("圭", "kei", "けい", "jade tablet, corner"),
                    .kanji("瑞", "zui", "ずい", "auspicious, Sweden (瑞典)"),
                    .kanji("玲", "rei", "れい", "jingle of jewels"),
                    .kanji("琢", "taku", "たく", "cut (gems), refine (琢磨)"),
                    .kanji("琉", "ryuu", "りゅう", "Ryukyu, gem (琉球)"),
                    .kanji("巴", "tomoe", "ともえ", "swirl crest, Paris (巴里)"),
                    .kanji("錫", "suzu", "すず", "tin"),
                    .kanji("斐", "hi", "ひ", "beautiful pattern, Kai (甲斐)"),
                    .kanji("翠", "sui", "すい", "jade green, kingfisher (翡翠)"),
                    .kanji("珂", "ka", "か", "white jade"),
                    .kanji("黛", "mayuzumi", "まゆずみ", "eyebrow ink, dark green"),
                    .kanji("蒼", "sou", "そう", "deep blue, pale (蒼白)"),
                    .kanji("絢", "ken", "けん", "gorgeous, brocade-bright (絢爛)"),
                    .kanji("瑛", "ei", "えい", "jewel sparkle, crystal"),
                    .kanji("茜", "akane", "あかね", "madder red"),
                    .kanji("緋", "hi", "ひ", "scarlet"),
                    .kanji("碧", "heki", "へき", "azure, emerald (碧眼)"),
                    .kanji("玖", "kyuu", "きゅう", "black jade, nine (formal)"),
                    .kanji("紗", "sha", "しゃ", "gauze"),
                    .kanji("琳", "rin", "りん", "jade chime, beautiful gem"),
                    .kanji("瑚", "go", "ご", "ritual vessel, coral (珊瑚)"),
                    .kanji("瑶", "you", "よう", "precious jade"),
                    .kanji("瑳", "sa", "さ", "lustrous white, artful smile"),
                    .kanji("珀", "haku", "はく", "amber (琥珀)"),
                    .kanji("珊", "san", "さん", "coral (珊瑚)"),
                    .kanji("琥", "ko", "こ", "tiger-shaped jade (琥珀)")
                ]
            )
        ],
        lessonOrder: "藤沢井岡佐阪崎郎浜伊江奈塚鈴郡埼浦智弘彦阿浩斎仙茨潟宏堀幌梶昌靖旭栃岐孜聡亜曙筑阜嘉滋俣淵辻那姓淳晋晃畿紘弥庄敦磐祐亘呉媛釧綾毅函亮圭堺窪畠瑞輔湘灘堰郁玲肇諏亨嶺喬洲巌淀峻琢逗琉奄遼欣巴禎稜錫斐魁赳孟尭馨慧彬匡欽嵯佃翠湊渚珂峨宕佑耀黛渥惇脩甫蒼暉洛汐絢黎塙允瑛茜皓洸緋怜邑碧悌丞凪玖侃侑昂迪勁奎宥昴洵倖恕晏晟紗崚捷晨琳嵩滉瑚瑶瑳碩颯熙誼諒叡澪燎燦燿汀灼祁昊昏沫穹俐俠娃恢珀珊逞惺焰琥楚漣煌凛醇憐燭驍渾"
    )
}
