import Foundation

extension MojiAlphabetData {
    static let kanjiFeelings = MojiPageDefinition(
        page: .kanji(.feelings),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "feelings",
                title: "Feelings",
                subtitle: "Emotions and attitudes",
                columns: 4,
                cells: [
                    .kanji("感", "kan", "かん", "feeling, sense"),
                    .kanji("楽", "tano(shii)", "たの(しい)", "fun, ease"),
                    .kanji("念", "nen", "ねん", "thought, sense"),
                    .kanji("好", "su(ki)", "す(き)", "like"),
                    .kanji("望", "nozo(mu)", "のぞ(む)", "desire"),
                    .kanji("苦", "kuru(shii)", "くる(しい)", "hardship, bitter"),
                    .kanji("愛", "ai", "あい", "love"),
                    .kanji("緊", "kin", "きん", "tense (緊張)"),
                    .kanji("興", "kyou", "きょう", "interest, revive (興味)"),
                    .kanji("努", "do", "ど", "endeavor (努力)"),
                    .kanji("喜", "yoroko(bu)", "よろこ(ぶ)", "rejoice"),
                    .kanji("惑", "waku", "わく", "bewilder"),
                    .kanji("幸", "shiawa(se)", "しあわ(せ)", "happiness"),
                    .kanji("恐", "oso(reru)", "おそ(れる)", "fear"),
                    .kanji("希", "ki", "き", "hope (希望)"),
                    .kanji("欲", "ho(shii)", "ほ(しい)", "want"),
                    .kanji("笑", "wara(u)", "わら(う)", "laugh"),
                    .kanji("迷", "mayo(u)", "まよ(う)", "get lost, hesitate"),
                    .kanji("夢", "yume", "ゆめ", "dream"),
                    .kanji("焦", "ase(ru)", "あせ(る)", "be impatient, scorch"),
                    .kanji("悲", "kana(shii)", "かな(しい)", "sad"),
                    .kanji("謝", "ayama(ru)", "あやま(る)", "apologize, thank"),
                    .kanji("歓", "kan", "かん", "delight, welcome (歓迎)"),
                    .kanji("快", "kai", "かい", "pleasant, comfortable (快適)"),
                    .kanji("敬", "kei", "けい", "respect"),
                    .kanji("悩", "naya(mu)", "なや(む)", "be worried"),
                    .kanji("驚", "odoro(ku)", "おどろ(く)", "be surprised"),
                    .kanji("慰", "nagusa(meru)", "なぐさ(める)", "comfort, console"),
                    .kanji("慣", "na(reru)", "な(れる)", "get used to"),
                    .kanji("尊", "son", "そん", "revered"),
                    .kanji("嫌", "kira(i)", "きら(い)", "dislike"),
                    .kanji("怒", "oko(ru)", "おこ(る)", "get angry"),
                    .kanji("励", "hage(masu)", "はげ(ます)", "encourage, strive"),
                    .kanji("誇", "hoko(ri)", "ほこ(り)", "pride"),
                    .kanji("恋", "koi", "こい", "romance"),
                    .kanji("勇", "yuu", "ゆう", "courage"),
                    .kanji("怖", "kowa(i)", "こわ(い)", "scary"),
                    .kanji("雰", "fun", "ふん", "atmosphere (雰囲気)"),
                    .kanji("泣", "na(ku)", "な(く)", "cry"),
                    .kanji("悔", "kuya(shii)", "くや(しい)", "vexing, regret"),
                    .kanji("懐", "natsu(kashii)", "なつ(かしい)", "nostalgic, bosom"),
                    .kanji("奮", "fun", "ふん", "rouse, excite (興奮)"),
                    .kanji("恥", "ha(zukashii)", "は(ずかしい)", "shame"),
                    .kanji("嘆", "nage(ku)", "なげ(く)", "lament, sigh"),
                    .kanji("寂", "sabi(shii)", "さび(しい)", "lonely"),
                    .kanji("憂", "yuu", "ゆう", "melancholy, worry (憂鬱)"),
                    .kanji("惜", "o(shii)", "お(しい)", "a pity, cherish"),
                    .kanji("憾", "kan", "かん", "regret (遺憾)"),
                    .kanji("哀", "awa(re)", "あわ(れ)", "pitiful, sorrow"),
                    .kanji("悦", "etsu", "えつ", "rapture, joy (悦楽)"),
                    .kanji("辱", "joku", "じょく", "humiliate, disgrace (侮辱)"),
                    .kanji("飽", "a(kiru)", "あ(きる)", "get tired of, be full"),
                    .kanji("憎", "niku(mu)", "にく(む)", "hate"),
                    .kanji("慌", "awa(teru)", "あわ(てる)", "panic, be flustered"),
                    .kanji("憤", "fun", "ふん", "resentment, indignant (憤慨)"),
                    .kanji("慨", "gai", "がい", "deplore, deep emotion (感慨)"),
                    .kanji("恨", "ura(mu)", "うら(む)", "bear a grudge"),
                    .kanji("愉", "yu", "ゆ", "joyful, amusing (愉快)"),
                    .kanji("侮", "anado(ru)", "あなど(る)", "make light of, insult (侮辱)"),
                    .kanji("惧", "gu", "ぐ", "dread, misgiving (危惧)"),
                    .kanji("慕", "shita(u)", "した(う)", "yearn for, adore"),
                    .kanji("愁", "shuu", "しゅう", "grief, gloom (哀愁)"),
                    .kanji("憧", "akoga(reru)", "あこが(れる)", "long for, admire"),
                    .kanji("嫉", "shitsu", "しつ", "jealousy (嫉妬)"),
                    .kanji("畏", "i", "い", "awe, reverence (畏敬)"),
                    .kanji("諦", "akira(meru)", "あきら(める)", "give up"),
                    .kanji("蔑", "betsu", "べつ", "contempt, despise (軽蔑)"),
                    .kanji("惚", "ho(reru)", "ほ(れる)", "fall for, be charmed"),
                    .kanji("妬", "neta(mu)", "ねた(む)", "be jealous, begrudge"),
                    .kanji("羞", "shuu", "しゅう", "bashfulness (羞恥心)"),
                    .kanji("慄", "ritsu", "りつ", "shudder (戦慄)"),
                    .kanji("羨", "uraya(mu)", "うらや(む)", "envy"),
                    .kanji("憬", "kei", "けい", "yearning (憧憬)"),
                    .kanji("鬱", "utsu", "うつ", "depression, gloom (鬱病)")
                ]
            ),
            MojiSectionDefinition(
                key: "character",
                title: "Character",
                subtitle: "Virtues, vices and manners",
                columns: 4,
                cells: [
                    .kanji("善", "zen", "ぜん", "goodness (改善)"),
                    .kanji("志", "kokorozashi", "こころざし", "aspiration, will (志)"),
                    .kanji("慎", "shin", "しん", "careful, prudent (慎重)"),
                    .kanji("俊", "shun", "しゅん", "gifted, quick (俊足)"),
                    .kanji("孝", "kou", "こう", "filial piety (親孝行)"),
                    .kanji("堅", "kata(i)", "かた(い)", "solid, steady (堅実)"),
                    .kanji("誉", "homa(re)", "ほま(れ)", "honor, fame (名誉)"),
                    .kanji("徳", "toku", "とく", "virtue (道徳)"),
                    .kanji("忠", "chuu", "ちゅう", "loyalty (忠実)"),
                    .kanji("誠", "sei", "せい", "sincerity (誠実)"),
                    .kanji("耐", "ta(eru)", "た(える)", "endure, -proof (耐える)"),
                    .kanji("倫", "rin", "りん", "ethics (倫理)"),
                    .kanji("仁", "jin", "じん", "benevolence (仁)"),
                    .kanji("克", "koku", "こく", "overcome (克服)"),
                    .kanji("拘", "kou", "こう", "detain, be particular (拘る)"),
                    .kanji("慢", "man", "まん", "conceit, chronic (自慢)"),
                    .kanji("朗", "rou", "ろう", "cheerful, clear (朗らか)"),
                    .kanji("寛", "kan", "かん", "tolerant, relaxed (寛容)"),
                    .kanji("貞", "tei", "てい", "chastity, faithful (貞操)"),
                    .kanji("恩", "on", "おん", "debt of gratitude (恩)"),
                    .kanji("才", "sai", "さい", "talent, genius (天才)"),
                    .kanji("愚", "gu", "ぐ", "foolish (愚か)"),
                    .kanji("謙", "ken", "けん", "modest (謙虚)"),
                    .kanji("潔", "ketsu", "けつ", "spotless, gracious (潔い)"),
                    .kanji("痴", "chi", "ち", "folly (愚痴)"),
                    .kanji("寧", "nei", "ねい", "polite, rather (丁寧)"),
                    .kanji("忍", "nin", "にん", "stealth, endure (忍者)"),
                    .kanji("怠", "nama(keru)", "なま(ける)", "neglect, slack off (怠ける)"),
                    .kanji("恭", "kyou", "きょう", "reverent (恭しい)"),
                    .kanji("敢", "kan", "かん", "daring, dare to (勇敢)"),
                    .kanji("篤", "toku", "とく", "devoted, critical (危篤)"),
                    .kanji("堪", "ta(eru)", "た(える)", "withstand, bear (堪える)"),
                    .kanji("癖", "kuse", "くせ", "habit, quirk (口癖)"),
                    .kanji("卑", "hi", "ひ", "lowly, mean (卑怯)"),
                    .kanji("堕", "da", "だ", "degenerate, fall (堕落)"),
                    .kanji("摯", "shi", "し", "earnest (真摯)"),
                    .kanji("惰", "da", "だ", "lazy, inertia (怠惰)"),
                    .kanji("蛮", "ban", "ばん", "barbarian (野蛮)"),
                    .kanji("倹", "ken", "けん", "thrifty (倹約)"),
                    .kanji("淫", "in", "いん", "lewd (淫ら)"),
                    .kanji("貪", "don", "どん", "greedy, covet (貪欲)"),
                    .kanji("傲", "gou", "ごう", "arrogant (傲慢)"),
                    .kanji("遜", "son", "そん", "humble (謙遜)"),
                    .kanji("臆", "oku", "おく", "timid (臆病)")
                ]
            )
        ],
        lessonOrder: "感楽念好望苦愛緊興努善喜惑幸志恐希欲笑迷夢焦慎俊悲謝孝堅誉歓快敬悩徳忠誠驚慰慣尊嫌怒励誇耐恋勇倫怖仁克拘雰慢朗寛泣貞恩悔懐才奮愚恥謙嘆潔寂憂惜痴憾寧忍怠哀恭悦辱飽憎慌敢憤慨恨篤堪癖愉卑侮堕惧慕摯愁憧嫉惰蛮畏諦倹蔑惚妬淫羞貪傲慄羨遜憬臆鬱"
    )
}
