import Foundation

extension MojiAlphabetData {
    static let kanjiBody = MojiPageDefinition(
        page: .kanji(.body),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "body",
                title: "The body",
                subtitle: "From head to toe, inside and out",
                columns: 4,
                cells: [
                    .kanji("手", "te", "て", "hand"),
                    .kanji("目", "me", "め", "eye"),
                    .kanji("体", "karada", "からだ", "body"),
                    .kanji("首", "kubi", "くび", "neck"),
                    .kanji("指", "yubi", "ゆび", "finger"),
                    .kanji("心", "kokoro", "こころ", "heart"),
                    .kanji("口", "kuchi", "くち", "mouth"),
                    .kanji("身", "mi", "み", "body, oneself (自身)"),
                    .kanji("足", "ashi", "あし", "foot, leg"),
                    .kanji("声", "koe", "こえ", "voice"),
                    .kanji("頭", "atama", "あたま", "head"),
                    .kanji("脳", "nou", "のう", "brain"),
                    .kanji("顔", "kao", "かお", "face"),
                    .kanji("背", "se", "せ", "back, height"),
                    .kanji("筋", "suji", "すじ", "muscle, line"),
                    .kanji("骨", "hone", "ほね", "bone"),
                    .kanji("臓", "zou", "ぞう", "internal organ"),
                    .kanji("皮", "kawa", "かわ", "hide, peel"),
                    .kanji("歯", "ha", "は", "tooth"),
                    .kanji("肝", "kimo", "きも", "liver, nerve (肝心)"),
                    .kanji("胸", "mune", "むね", "chest"),
                    .kanji("腕", "ude", "うで", "arm"),
                    .kanji("毛", "ke", "け", "fur, body hair"),
                    .kanji("肩", "kata", "かた", "shoulder"),
                    .kanji("脚", "ashi", "あし", "leg, script (脚本)"),
                    .kanji("腹", "hara", "はら", "belly"),
                    .kanji("腰", "koshi", "こし", "lower back"),
                    .kanji("耳", "mimi", "みみ", "ear"),
                    .kanji("肺", "hai", "はい", "lung (肺)"),
                    .kanji("胆", "tan", "たん", "gall, courage (大胆)"),
                    .kanji("髪", "kami", "かみ", "hair (head)"),
                    .kanji("脈", "myaku", "みゃく", "pulse, vein (脈)"),
                    .kanji("眼", "gan", "がん", "eyeball (眼科)"),
                    .kanji("脂", "abura", "あぶら", "grease, fat (脂肪)"),
                    .kanji("肌", "hada", "はだ", "skin"),
                    .kanji("鼻", "hana", "はな", "nose"),
                    .kanji("胃", "i", "い", "stomach"),
                    .kanji("髄", "zui", "ずい", "marrow (骨髄)"),
                    .kanji("膚", "fu", "ふ", "skin surface (皮膚)"),
                    .kanji("尻", "shiri", "しり", "buttocks (尻)"),
                    .kanji("腎", "jin", "じん", "kidney (腎臓)"),
                    .kanji("掌", "tenohira", "てのひら", "palm (of hand) (掌)"),
                    .kanji("裸", "hadaka", "はだか", "naked (裸)"),
                    .kanji("膜", "maku", "まく", "membrane (鼓膜)"),
                    .kanji("脇", "waki", "わき", "armpit, side (脇)"),
                    .kanji("腸", "chou", "ちょう", "intestines (腸)"),
                    .kanji("舌", "shita", "した", "tongue (舌)"),
                    .kanji("肪", "bou", "ぼう", "body fat (脂肪)"),
                    .kanji("胴", "dou", "どう", "torso (胴体)"),
                    .kanji("椎", "tsui", "つい", "vertebra, shiitake (椎茸)"),
                    .kanji("拳", "kobushi", "こぶし", "fist (拳)"),
                    .kanji("渇", "kawa(ku)", "かわ(く)", "thirst (渇く)"),
                    .kanji("唇", "kuchibiru", "くちびる", "lips (唇)"),
                    .kanji("爪", "tsume", "つめ", "fingernail, claw (爪)"),
                    .kanji("瞳", "hitomi", "ひとみ", "pupil (of the eye) (瞳)"),
                    .kanji("眉", "mayu", "まゆ", "eyebrow (眉)"),
                    .kanji("股", "mata", "また", "crotch, thigh (股)"),
                    .kanji("肢", "shi", "し", "limb, option (選択肢)"),
                    .kanji("脊", "seki", "せき", "spine (脊髄)"),
                    .kanji("膝", "hiza", "ひざ", "knee, lap (膝)"),
                    .kanji("喉", "nodo", "のど", "throat (喉)"),
                    .kanji("嗅", "ka(gu)", "か(ぐ)", "sniff, smell (嗅ぐ)"),
                    .kanji("眸", "hitomi", "ひとみ", "eye pupil, gaze (眸)"),
                    .kanji("脹", "chou", "ちょう", "bloat, distend (膨脹)"),
                    .kanji("肘", "hiji", "ひじ", "elbow (肘)"),
                    .kanji("咽", "in", "いん", "pharynx, choke (咽喉)"),
                    .kanji("唾", "tsuba", "つば", "saliva, spit (唾)"),
                    .kanji("痩", "ya(seru)", "や(せる)", "get thin (痩せる)"),
                    .kanji("腺", "sen", "せん", "gland (汗腺)"),
                    .kanji("貌", "bou", "ぼう", "looks, appearance (容貌)"),
                    .kanji("頰", "hoo", "ほお", "cheek (頰)"),
                    .kanji("骸", "gai", "がい", "skeleton, remains (骸骨)"),
                    .kanji("顎", "ago", "あご", "jaw, chin (顎)"),
                    .kanji("肋", "roku", "ろく", "rib (肋骨)"),
                    .kanji("吻", "fun", "ふん", "snout, kiss (接吻)"),
                    .kanji("腔", "kou", "こう", "body cavity (口腔)")
                ]
            ),
            MojiSectionDefinition(
                key: "health",
                title: "Health & medicine",
                subtitle: "Feeling ill, the doctor and getting well",
                columns: 4,
                cells: [
                    .kanji("気", "ki", "き", "spirit, mood"),
                    .kanji("院", "in", "いん", "institution"),
                    .kanji("元", "gen", "げん", "origin (元気)"),
                    .kanji("死", "shi(nu)", "し(ぬ)", "die"),
                    .kanji("病", "byou", "びょう", "illness"),
                    .kanji("医", "i", "い", "doctor, medical"),
                    .kanji("命", "inochi", "いのち", "life (soul)"),
                    .kanji("健", "ken", "けん", "healthy"),
                    .kanji("療", "ryou", "りょう", "treatment"),
                    .kanji("薬", "kusuri", "くすり", "medicine"),
                    .kanji("康", "kou", "こう", "well-being"),
                    .kanji("患", "kan", "かん", "patient, illness"),
                    .kanji("血", "chi", "ち", "blood"),
                    .kanji("傷", "kizu", "きず", "wound"),
                    .kanji("香", "kaori", "かおり", "fragrance"),
                    .kanji("息", "iki", "いき", "breath"),
                    .kanji("痛", "ita(i)", "いた(い)", "painful"),
                    .kanji("射", "sha", "しゃ", "inject, radiate"),
                    .kanji("診", "shin", "しん", "diagnose"),
                    .kanji("吸", "su(u)", "す(う)", "inhale, suck"),
                    .kanji("看", "kan", "かん", "watch over"),
                    .kanji("症", "shou", "しょう", "symptom"),
                    .kanji("剤", "zai", "ざい", "drug, agent (薬剤)"),
                    .kanji("疲", "tsuka(reru)", "つか(れる)", "tired"),
                    .kanji("眠", "nemu(i)", "ねむ(い)", "sleepy"),
                    .kanji("涙", "namida", "なみだ", "tear (crying)"),
                    .kanji("妊", "nin", "にん", "pregnancy (妊娠)"),
                    .kanji("毒", "doku", "どく", "poison"),
                    .kanji("汗", "ase", "あせ", "sweat"),
                    .kanji("疾", "shitsu", "しつ", "disease, swift (疾患)"),
                    .kanji("菌", "kin", "きん", "germ, bacteria (細菌)"),
                    .kanji("娠", "shin", "しん", "conceive (妊娠)"),
                    .kanji("疫", "eki", "えき", "epidemic (疫病)"),
                    .kanji("癒", "iya(su)", "いや(す)", "heal, soothe"),
                    .kanji("尿", "nyou", "にょう", "urine"),
                    .kanji("吐", "ha(ku)", "は(く)", "vomit, spit out"),
                    .kanji("睡", "sui", "すい", "sleep (睡眠)"),
                    .kanji("盲", "mou", "もう", "blind (盲目)"),
                    .kanji("摂", "setsu", "せつ", "take in, intake (摂取)"),
                    .kanji("胎", "tai", "たい", "womb, fetus (胎児)"),
                    .kanji("挫", "za", "ざ", "sprain, setback (挫折)"),
                    .kanji("痕", "ato", "あと", "scar, trace (傷痕)"),
                    .kanji("痢", "ri", "り", "diarrhea (下痢)"),
                    .kanji("矯", "kyou", "きょう", "straighten, correct (矯正)"),
                    .kanji("泌", "hitsu", "ひつ", "secrete, ooze (分泌)"),
                    .kanji("腫", "ha(reru)", "は(れる)", "swelling, tumor (腫瘍)"),
                    .kanji("痘", "tou", "とう", "smallpox (天然痘)"),
                    .kanji("梗", "kou", "こう", "blockage, infarct (梗塞)"),
                    .kanji("瘍", "you", "よう", "ulcer, boil (潰瘍)"),
                    .kanji("灸", "kyuu", "きゅう", "moxibustion (お灸)"),
                    .kanji("娩", "ben", "べん", "childbirth (分娩)"),
                    .kanji("膏", "kou", "こう", "ointment, fat (軟膏)")
                ]
            )
        ],
        lessonOrder: "手目体首気院指心元死口身足病声頭医脳命健療顔背薬筋康患血傷香息痛骨射臓診吸看皮歯症肝胸剤腕毛肩脚疲腹腰眠耳涙肺妊毒胆髪脈汗眼脂肌疾菌娠鼻胃髄疫癒尿吐膚尻睡腎掌盲摂裸膜脇腸舌胎挫肪胴椎拳渇痕唇爪痢瞳矯泌腫眉股肢脊膝喉嗅痘眸脹肘咽唾梗痩腺瘍貌頰骸顎肋吻灸娩腔膏"
    )
}
