import Foundation

extension MojiAlphabetData {
    static let kanjiActions = MojiPageDefinition(
        page: .kanji(.actions),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "doing",
                title: "Everyday actions",
                subtitle: "Verbs you use every day",
                columns: 4,
                cells: [
                    .kanji("選", "era(bu)", "えら(ぶ)", "choose"),
                    .kanji("立", "ta(tsu)", "た(つ)", "stand"),
                    .kanji("開", "a(keru)", "あ(ける)", "open"),
                    .kanji("決", "ki(meru)", "き(める)", "decide"),
                    .kanji("作", "tsuku(ru)", "つく(る)", "make"),
                    .kanji("持", "mo(tsu)", "も(つ)", "hold"),
                    .kanji("取", "to(ru)", "と(る)", "take"),
                    .kanji("勝", "ka(tsu)", "か(つ)", "win"),
                    .kanji("売", "u(ru)", "う(る)", "sell"),
                    .kanji("集", "atsu(meru)", "あつ(める)", "gather"),
                    .kanji("引", "hi(ku)", "ひ(く)", "pull"),
                    .kanji("使", "tsuka(u)", "つか(う)", "use"),
                    .kanji("変", "ka(waru)", "か(わる)", "change, strange"),
                    .kanji("直", "nao(su)", "なお(す)", "fix, straight"),
                    .kanji("住", "su(mu)", "す(む)", "reside"),
                    .kanji("置", "o(ku)", "お(く)", "put"),
                    .kanji("付", "tsu(ku)", "つ(く)", "attach"),
                    .kanji("切", "ki(ru)", "き(る)", "cut"),
                    .kanji("消", "ke(su)", "け(す)", "erase, switch off"),
                    .kanji("起", "o(kiru)", "お(きる)", "wake up"),
                    .kanji("待", "ma(tsu)", "ま(つ)", "wait"),
                    .kanji("助", "tasu(keru)", "たす(ける)", "help"),
                    .kanji("張", "ha(ru)", "は(る)", "stretch"),
                    .kanji("伝", "tsuta(eru)", "つた(える)", "convey"),
                    .kanji("負", "ma(keru)", "ま(ける)", "lose (a game)"),
                    .kanji("失", "ushina(u)", "うしな(う)", "lose, miss"),
                    .kanji("守", "mamo(ru)", "まも(る)", "protect"),
                    .kanji("買", "ka(u)", "か(う)", "buy"),
                    .kanji("座", "suwa(ru)", "すわ(る)", "sit"),
                    .kanji("休", "yasu(mu)", "やす(む)", "rest"),
                    .kanji("込", "ko(mu)", "こ(む)", "be crowded, into"),
                    .kanji("返", "kae(su)", "かえ(す)", "give back"),
                    .kanji("押", "o(su)", "お(す)", "push"),
                    .kanji("払", "hara(u)", "はら(う)", "pay"),
                    .kanji("困", "koma(ru)", "こま(る)", "be troubled"),
                    .kanji("探", "saga(su)", "さが(す)", "look for"),
                    .kanji("借", "ka(riru)", "か(りる)", "borrow"),
                    .kanji("遊", "aso(bu)", "あそ(ぶ)", "play"),
                    .kanji("閉", "shi(meru)", "し(める)", "close"),
                    .kanji("貸", "ka(su)", "か(す)", "lend"),
                    .kanji("撮", "to(ru)", "と(る)", "shoot (photo)"),
                    .kanji("寝", "ne(ru)", "ね(る)", "sleep"),
                    .kanji("洗", "ara(u)", "あら(う)", "wash"),
                    .kanji("頑", "gan", "がん", "persist (頑張る)")
                ]
            ),
            MojiSectionDefinition(
                key: "more",
                title: "More actions",
                subtitle: "Handling, changing, breaking and fixing",
                columns: 4,
                cells: [
                    .kanji("現", "arawa(reru)", "あらわ(れる)", "appear"),
                    .kanji("調", "shira(beru)", "しら(べる)", "check, tone"),
                    .kanji("査", "sa", "さ", "inspect"),
                    .kanji("求", "moto(meru)", "もと(める)", "request, seek"),
                    .kanji("示", "shime(su)", "しめ(す)", "indicate"),
                    .kanji("再", "sai", "さい", "again, re-"),
                    .kanji("援", "en", "えん", "aid"),
                    .kanji("導", "michibi(ku)", "みちび(く)", "guide"),
                    .kanji("整", "totono(eru)", "ととの(える)", "arrange"),
                    .kanji("敗", "hai", "はい", "defeat"),
                    .kanji("接", "setsu", "せつ", "contact"),
                    .kanji("積", "tsu(mu)", "つ(む)", "pile up"),
                    .kanji("破", "yabu(ru)", "やぶ(る)", "tear, rip"),
                    .kanji("並", "nara(bu)", "なら(ぶ)", "line up"),
                    .kanji("修", "shuu", "しゅう", "repair, master"),
                    .kanji("拡", "kaku", "かく", "expand"),
                    .kanji("振", "fu(ru)", "ふ(る)", "shake, wave"),
                    .kanji("換", "ka(eru)", "か(える)", "exchange"),
                    .kanji("許", "yuru(su)", "ゆる(す)", "permit, forgive"),
                    .kanji("抜", "nu(ku)", "ぬ(く)", "pull out"),
                    .kanji("壊", "kowa(su)", "こわ(す)", "break, destroy"),
                    .kanji("伸", "no(biru)", "の(びる)", "lengthen, grow"),
                    .kanji("延", "no(basu)", "の(ばす)", "extend, postpone"),
                    .kanji("散", "chi(ru)", "ち(る)", "scatter"),
                    .kanji("脱", "nu(gu)", "ぬ(ぐ)", "take off (clothes)"),
                    .kanji("混", "ma(zeru)", "ま(ぜる)", "mix"),
                    .kanji("招", "mane(ku)", "まね(く)", "invite"),
                    .kanji("弾", "hi(ku)", "ひ(く)", "play (instrument), bullet"),
                    .kanji("抱", "da(ku)", "だ(く)", "hug"),
                    .kanji("縮", "chiji(mu)", "ちぢ(む)", "shrink"),
                    .kanji("似", "ni(ru)", "に(る)", "resemble"),
                    .kanji("包", "tsutsu(mu)", "つつ(む)", "wrap"),
                    .kanji("折", "o(ru)", "お(る)", "fold, snap"),
                    .kanji("替", "ka(eru)", "か(える)", "replace"),
                    .kanji("贈", "oku(ru)", "おく(る)", "give (a gift)"),
                    .kanji("照", "te(rasu)", "て(らす)", "illuminate"),
                    .kanji("掛", "ka(keru)", "か(ける)", "hang"),
                    .kanji("片", "kata", "かた", "one side, piece"),
                    .kanji("隠", "kaku(su)", "かく(す)", "hide"),
                    .kanji("輝", "kagaya(ku)", "かがや(く)", "shine"),
                    .kanji("捨", "su(teru)", "す(てる)", "throw away"),
                    .kanji("冒", "bou", "ぼう", "risk (冒険)"),
                    .kanji("拾", "hiro(u)", "ひろ(う)", "pick up"),
                    .kanji("酔", "yo(u)", "よ(う)", "get drunk")
                ]
            ),
            MojiSectionDefinition(
                key: "hands",
                title: "Hands at work",
                subtitle: "Grabbing, rubbing, wrapping and digging",
                columns: 4,
                cells: [
                    .kanji("摘", "teki", "てき", "pluck, point out (指摘)"),
                    .kanji("繰", "ku(ru)", "く(る)", "reel, repeat (繰り返す)"),
                    .kanji("触", "sawa(ru)", "さわ(る)", "touch (触る)"),
                    .kanji("束", "taba", "たば", "bundle (花束)"),
                    .kanji("巻", "ma(ku)", "ま(く)", "roll up, volume (巻く)"),
                    .kanji("握", "nigi(ru)", "にぎ(る)", "grip (握る)"),
                    .kanji("操", "sou", "そう", "operate, handle (操作)"),
                    .kanji("詰", "tsu(meru)", "つ(める)", "pack, stuff (詰める)"),
                    .kanji("括", "katsu", "かつ", "lump together (一括)"),
                    .kanji("刺", "sa(su)", "さ(す)", "stab, pierce (刺身)"),
                    .kanji("裂", "sa(ku)", "さ(く)", "split, rend (裂ける)"),
                    .kanji("扱", "atsuka(u)", "あつか(う)", "handle, treat (扱う)"),
                    .kanji("埋", "u(meru)", "う(める)", "bury, fill in (埋める)"),
                    .kanji("貫", "tsuranu(ku)", "つらぬ(く)", "pierce through (貫く)"),
                    .kanji("摩", "ma", "ま", "rub, chafe (摩擦)"),
                    .kanji("掘", "ho(ru)", "ほ(る)", "dig (掘る)"),
                    .kanji("絞", "shibo(ru)", "しぼ(る)", "wring, narrow down (絞る)"),
                    .kanji("拍", "haku", "はく", "clap, beat (拍手)"),
                    .kanji("覆", "oo(u)", "おお(う)", "cover, overturn (覆う)"),
                    .kanji("塗", "nu(ru)", "ぬ(る)", "paint, smear (塗る)"),
                    .kanji("抽", "chuu", "ちゅう", "draw out, abstract (抽選)"),
                    .kanji("据", "su(eru)", "す(える)", "set, install (据える)"),
                    .kanji("擦", "su(ru)", "す(る)", "scrape, graze (擦る)"),
                    .kanji("彫", "ho(ru)", "ほ(る)", "carve (彫刻)"),
                    .kanji("砕", "kuda(ku)", "くだ(く)", "smash, crush (砕く)"),
                    .kanji("磨", "miga(ku)", "みが(く)", "polish, brush (磨く)"),
                    .kanji("縛", "shiba(ru)", "しば(る)", "tie up (縛る)"),
                    .kanji("挟", "hasa(mu)", "はさ(む)", "pinch, sandwich (挟む)"),
                    .kanji("挿", "sou", "そう", "insert (挿入)"),
                    .kanji("捉", "tora(eru)", "とら(える)", "seize, perceive (捉える)"),
                    .kanji("搾", "shibo(ru)", "しぼ(る)", "squeeze (搾る)"),
                    .kanji("剥", "ha(gasu)", "は(がす)", "peel off (剥がす)"),
                    .kanji("撫", "na(deru)", "な(でる)", "stroke, pat (撫でる)"),
                    .kanji("拭", "fu(ku)", "ふ(く)", "wipe (拭く)"),
                    .kanji("貼", "ha(ru)", "は(る)", "paste on (貼る)"),
                    .kanji("弄", "moteaso(bu)", "もてあそ(ぶ)", "toy with (弄ぶ)"),
                    .kanji("捻", "nen", "ねん", "twist (捻る)"),
                    .kanji("塡", "ten", "てん", "plug a gap, load (補塡)"),
                    .kanji("潰", "tsubu(su)", "つぶ(す)", "crush, squash (潰す)")
                ]
            )
        ],
        lessonOrder: "選立開決現調作持取査勝売集引使求示変直住再置援付切消導起待助張伝負失守整敗買接積摘座破並修拡振休込返換許抜壊伸延散脱押払混招困弾抱繰触縮束似探借遊巻閉包折替貸贈握照操詰撮括掛刺寝裂扱片隠埋貫洗頑摩掘輝捨絞冒拍覆塗抽据拾擦彫砕磨酔縛挟挿捉搾剥撫拭貼弄捻塡潰"
    )
}
