import Foundation

extension MojiAlphabetData {
    static let kanjiWords = MojiPageDefinition(
        page: .kanji(.words),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "blocks",
                title: "Building blocks",
                subtitle: "The building blocks of common words",
                columns: 4,
                cells: [
                    .kanji("同", "ona(ji)", "おな(じ)", "same"),
                    .kanji("連", "ren", "れん", "link, take along"),
                    .kanji("対", "tai", "たい", "versus, pair"),
                    .kanji("合", "a(u)", "あ(う)", "fit, match"),
                    .kanji("相", "ai", "あい", "mutual, partner"),
                    .kanji("定", "tei", "てい", "fix, settle"),
                    .kanji("力", "chikara", "ちから", "power"),
                    .kanji("実", "jitsu", "じつ", "actual (実は)"),
                    .kanji("関", "kan", "かん", "related, barrier"),
                    .kanji("全", "zen", "ぜん", "all, whole"),
                    .kanji("経", "kei", "けい", "elapse, manage"),
                    .kanji("当", "a(taru)", "あ(たる)", "proper, hit the mark"),
                    .kanji("約", "yaku", "やく", "promise, approx."),
                    .kanji("不", "fu", "ふ", "not, un-"),
                    .kanji("性", "sei", "せい", "nature, gender"),
                    .kanji("的", "teki", "てき", "-ic, target"),
                    .kanji("要", "you", "よう", "need, essential"),
                    .kanji("成", "sei", "せい", "become, grow"),
                    .kanji("和", "wa", "わ", "Japanese style, harmony"),
                    .kanji("以", "i", "い", "by, from (以上)"),
                    .kanji("平", "hei", "へい", "flat, peace"),
                    .kanji("加", "kuwa(eru)", "くわ(える)", "add"),
                    .kanji("続", "tsuzu(ku)", "つづ(く)", "continue"),
                    .kanji("産", "san", "さん", "produce"),
                    .kanji("結", "musu(bu)", "むす(ぶ)", "tie, bind"),
                    .kanji("報", "hou", "ほう", "report, news"),
                    .kanji("活", "katsu", "かつ", "lively, activity"),
                    .kanji("予", "yo", "よ", "beforehand"),
                    .kanji("参", "san", "さん", "participate, visit"),
                    .kanji("利", "ri", "り", "profit, advantage"),
                    .kanji("別", "betsu", "べつ", "separate, different"),
                    .kanji("増", "fu(eru)", "ふ(える)", "increase"),
                    .kanji("係", "kakari", "かかり", "involvement, in charge"),
                    .kanji("特", "toku", "とく", "special"),
                    .kanji("情", "jou", "じょう", "emotion, information"),
                    .kanji("確", "tashi(ka)", "たし(か)", "certain"),
                    .kanji("減", "he(ru)", "へ(る)", "decrease"),
                    .kanji("必", "kanara(zu)", "かなら(ず)", "certainly, must"),
                    .kanji("能", "nou", "のう", "ability"),
                    .kanji("無", "mu", "む", "nothing, without"),
                    .kanji("真", "shin", "しん", "true, genuine"),
                    .kanji("有", "yuu", "ゆう", "possess (有名)"),
                    .kanji("常", "jou", "じょう", "usual"),
                    .kanji("可", "ka", "か", "possible, okay"),
                    .kanji("割", "wa(ru)", "わ(る)", "divide, crack"),
                    .kanji("由", "yuu", "ゆう", "cause (理由)"),
                    .kanji("何", "nani", "なに", "what"),
                    .kanji("違", "chiga(u)", "ちが(う)", "differ, wrong"),
                    .kanji("残", "noko(ru)", "のこ(る)", "remain"),
                    .kanji("例", "rei", "れい", "example"),
                    .kanji("然", "zen", "ぜん", "so (全然)"),
                    .kanji("他", "hoka", "ほか", "other"),
                    .kanji("完", "kan", "かん", "complete"),
                    .kanji("禁", "kin", "きん", "prohibit"),
                    .kanji("便", "ben", "べん", "convenience"),
                    .kanji("普", "fu", "ふ", "ordinary"),
                    .kanji("絶", "zetsu", "ぜつ", "absolute, sever"),
                    .kanji("頂", "itada(ku)", "いただ(く)", "receive (humble), top")
                ]
            ),
            MojiSectionDefinition(
                key: "being",
                title: "Being & having",
                subtitle: "Existing, filling, belonging and lasting",
                columns: 4,
                cells: [
                    .kanji("在", "zai", "ざい", "be located, exist (存在)"),
                    .kanji("備", "sona(eru)", "そな(える)", "prepare, equip (準備)"),
                    .kanji("満", "man", "まん", "full (満足)"),
                    .kanji("維", "i", "い", "maintain, fiber (維持)"),
                    .kanji("余", "ama(ru)", "あま(る)", "surplus, too much"),
                    .kanji("盛", "mo(ru)", "も(る)", "heap up, thrive (大盛り)"),
                    .kanji("伴", "tomona(u)", "ともな(う)", "accompany (伴う)"),
                    .kanji("属", "zoku", "ぞく", "belong, genus (所属)"),
                    .kanji("互", "taga(i)", "たが(い)", "each other (お互い)"),
                    .kanji("栄", "ei", "えい", "flourish, glory (栄養)"),
                    .kanji("充", "juu", "じゅう", "fill, charge (充電)"),
                    .kanji("併", "hei", "へい", "merge, combined (合併)"),
                    .kanji("徹", "tetsu", "てつ", "go through, all night (徹夜)"),
                    .kanji("隆", "ryuu", "りゅう", "prosperity, swell (隆盛)"),
                    .kanji("兼", "ka(neru)", "か(ねる)", "double as (兼ねる)"),
                    .kanji("膨", "fuku(ramu)", "ふく(らむ)", "swell (膨らむ)"),
                    .kanji("衰", "otoro(eru)", "おとろ(える)", "decline, weaken"),
                    .kanji("剰", "jou", "じょう", "excess (過剰)"),
                    .kanji("累", "rui", "るい", "cumulative (累計)"),
                    .kanji("耗", "mou", "もう", "wear down (消耗)")
                ]
            ),
            MojiSectionDefinition(
                key: "giving",
                title: "Giving & getting",
                subtitle: "Offers, requests, gifts and handovers",
                columns: 4,
                cells: [
                    .kanji("提", "tei", "てい", "submit, propose (提出)"),
                    .kanji("与", "ata(eru)", "あた(える)", "give, grant (与える)"),
                    .kanji("請", "sei", "せい", "apply for, claim (申請)"),
                    .kanji("献", "ken", "けん", "offer, dedicate (貢献)"),
                    .kanji("継", "tsu(gu)", "つ(ぐ)", "succeed, inherit (継ぐ)"),
                    .kanji("依", "i", "い", "rely on, request (依頼)"),
                    .kanji("還", "kan", "かん", "send back (返還)"),
                    .kanji("恵", "megu(mu)", "めぐ(む)", "bless, favor (恵まれる)"),
                    .kanji("貢", "kou", "こう", "tribute, contribute (貢献)"),
                    .kanji("獲", "kaku", "かく", "capture, win (獲得)"),
                    .kanji("奪", "uba(u)", "うば(う)", "rob, snatch (奪う)"),
                    .kanji("譲", "yuzu(ru)", "ゆず(る)", "hand over, yield (譲る)"),
                    .kanji("誘", "saso(u)", "さそ(う)", "ask out, tempt (誘う)"),
                    .kanji("託", "taku", "たく", "consign, entrust (託す)"),
                    .kanji("薦", "susu(meru)", "すす(める)", "recommend (推薦)"),
                    .kanji("呈", "tei", "てい", "present, reveal (贈呈)"),
                    .kanji("享", "kyou", "きょう", "enjoy, receive (享受)"),
                    .kanji("賜", "tamawa(ru)", "たまわ(る)", "bestow (賜る)"),
                    .kanji("捧", "sasa(geru)", "ささ(げる)", "devote, offer up (捧げる)"),
                    .kanji("頒", "han", "はん", "hand out (頒布)"),
                    .kanji("戴", "tai", "たい", "receive humbly (頂戴)"),
                    .kanji("乞", "ko(u)", "こ(う)", "beg (乞う)"),
                    .kanji("托", "taku", "たく", "alms, saucer (托鉢)")
                ]
            ),
            MojiSectionDefinition(
                key: "control",
                title: "Holding back",
                subtitle: "Refusing, blocking, ending and calming",
                columns: 4,
                cells: [
                    .kanji("処", "sho", "しょ", "deal with, dispose (処理)"),
                    .kanji("廃", "hai", "はい", "abolish, obsolete (廃止)"),
                    .kanji("撤", "tetsu", "てつ", "withdraw, remove (撤回)"),
                    .kanji("抑", "osa(eru)", "おさ(える)", "suppress, hold down (抑える)"),
                    .kanji("拒", "kyo", "きょ", "reject (拒否)"),
                    .kanji("棄", "ki", "き", "abandon, discard (放棄)"),
                    .kanji("却", "kyaku", "きゃく", "dismiss, return (却下)"),
                    .kanji("控", "hika(eru)", "ひか(える)", "hold back, refrain (控える)"),
                    .kanji("排", "hai", "はい", "expel, exclude (排除)"),
                    .kanji("抵", "tei", "てい", "resist, touch (抵抗)"),
                    .kanji("滅", "metsu", "めつ", "perish, destroy (絶滅)"),
                    .kanji("尽", "tsu(kusu)", "つ(くす)", "use up, devote (尽くす)"),
                    .kanji("阻", "so", "そ", "block, thwart (阻止)"),
                    .kanji("遂", "to(geru)", "と(げる)", "achieve, at last (遂げる)"),
                    .kanji("妨", "samata(geru)", "さまた(げる)", "obstruct (妨害)"),
                    .kanji("粛", "shuku", "しゅく", "solemn, self-restraint (自粛)"),
                    .kanji("鎮", "chin", "ちん", "quell, soothe (鎮める)"),
                    .kanji("遮", "saegi(ru)", "さえぎ(る)", "block off, interrupt (遮る)"),
                    .kanji("斥", "seki", "せき", "repel, expel (排斥)"),
                    .kanji("塞", "fusa(gu)", "ふさ(ぐ)", "plug, block up (塞ぐ)")
                ]
            )
        ],
        lessonOrder: "同連対合相定力実関全経当約不性的要成和以平加続産結報活予参利在別増係特情確提減必能無真有常与可割由何違備残例然満請他処完献維余禁廃盛便継普絶撤抑拒伴棄依還属互栄恵充貢却獲併徹奪譲誘控託排薦隆兼抵滅尽阻膨頂遂衰剰妨粛呈鎮累遮享賜斥捧頒戴乞耗塞托"
    )
}
