import Foundation

extension MojiAlphabetData {
    static let kanjiStudy = MojiPageDefinition(
        page: .kanji(.study),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "school",
                title: "School & language",
                subtitle: "Classes, tests, words and writing",
                columns: 4,
                cells: [
                    .kanji("本", "hon", "ほん", "book, origin"),
                    .kanji("学", "gaku", "がく", "study"),
                    .kanji("問", "mon", "もん", "question"),
                    .kanji("題", "dai", "だい", "title, topic"),
                    .kanji("記", "ki", "き", "write down (日記)"),
                    .kanji("教", "oshi(eru)", "おし(える)", "teach"),
                    .kanji("書", "ka(ku)", "か(く)", "write"),
                    .kanji("文", "bun", "ぶん", "sentence, writing"),
                    .kanji("位", "kurai", "くらい", "rank, about"),
                    .kanji("校", "kou", "こう", "school"),
                    .kanji("語", "go", "ご", "language, word"),
                    .kanji("補", "ho", "ほ", "supplement"),
                    .kanji("質", "shitsu", "しつ", "quality, question"),
                    .kanji("試", "tame(su)", "ため(す)", "try, test"),
                    .kanji("験", "ken", "けん", "examination"),
                    .kanji("英", "ei", "えい", "English"),
                    .kanji("復", "fuku", "ふく", "restore, repeat"),
                    .kanji("課", "ka", "か", "lesson, section"),
                    .kanji("字", "ji", "じ", "letter, character"),
                    .kanji("答", "kota(e)", "こた(え)", "answer"),
                    .kanji("専", "sen", "せん", "specialty, exclusive (専門)"),
                    .kanji("授", "ju", "じゅ", "instruct"),
                    .kanji("紙", "kami", "かみ", "paper"),
                    .kanji("師", "shi", "し", "teacher, master"),
                    .kanji("読", "yo(mu)", "よ(む)", "read"),
                    .kanji("辞", "ji", "じ", "words, resign (辞書)"),
                    .kanji("講", "kou", "こう", "lecture"),
                    .kanji("宿", "yado", "やど", "lodging (宿題)"),
                    .kanji("習", "nara(u)", "なら(う)", "learn"),
                    .kanji("留", "ryuu", "りゅう", "stay, detain (留学)"),
                    .kanji("卒", "sotsu", "そつ", "graduate"),
                    .kanji("順", "jun", "じゅん", "sequence"),
                    .kanji("練", "ren", "れん", "practice, train"),
                    .kanji("博", "haku", "はく", "Ph.D., broad, expo (博士)"),
                    .kanji("絡", "raku", "らく", "entwine (連絡)"),
                    .kanji("徒", "to", "と", "disciple, on foot (生徒)"),
                    .kanji("績", "seki", "せき", "achievement, results (成績)"),
                    .kanji("欠", "ka(keru)", "か(ける)", "lack"),
                    .kanji("緒", "sho", "しょ", "cord (一緒)"),
                    .kanji("章", "shou", "しょう", "chapter, badge (文章)"),
                    .kanji("勉", "ben", "べん", "effort (勉強)"),
                    .kanji("訓", "kun", "くん", "instruction, kun reading (訓練)"),
                    .kanji("塾", "juku", "じゅく", "cram school"),
                    .kanji("彰", "shou", "しょう", "commend, make clear (表彰)"),
                    .kanji("准", "jun", "じゅん", "quasi-, associate (准教授)"),
                    .kanji("奨", "shou", "しょう", "promote, award (奨励)"),
                    .kanji("漢", "kan", "かん", "Chinese (kanji)"),
                    .kanji("班", "han", "はん", "team, section (班長)"),
                    .kanji("詞", "shi", "し", "part of speech, lyrics (品詞)"),
                    .kanji("寮", "ryou", "りょう", "dormitory"),
                    .kanji("彙", "i", "い", "vocabulary (語彙)"),
                    .kanji("註", "chuu", "ちゅう", "annotation (註釈)")
                ]
            ),
            MojiSectionDefinition(
                key: "science",
                title: "Science & technology",
                subtitle: "Research, matter and machines",
                columns: 4,
                cells: [
                    .kanji("理", "ri", "り", "logic, principle"),
                    .kanji("化", "ka", "か", "change, -ization"),
                    .kanji("電", "den", "でん", "electricity"),
                    .kanji("球", "tama", "たま", "ball, sphere"),
                    .kanji("研", "ken", "けん", "research"),
                    .kanji("術", "jutsu", "じゅつ", "technique, art"),
                    .kanji("算", "san", "さん", "calculate"),
                    .kanji("究", "kyuu", "きゅう", "investigate"),
                    .kanji("技", "waza", "わざ", "skill"),
                    .kanji("種", "tane", "たね", "seed, kind"),
                    .kanji("量", "ryou", "りょう", "quantity"),
                    .kanji("核", "kaku", "かく", "nucleus, nuclear (核兵器)"),
                    .kanji("管", "kan", "かん", "pipe, control"),
                    .kanji("科", "ka", "か", "subject, science"),
                    .kanji("材", "zai", "ざい", "material"),
                    .kanji("具", "gu", "ぐ", "tool, ingredient"),
                    .kanji("装", "sou", "そう", "equipment, attire"),
                    .kanji("素", "so", "そ", "element, plain"),
                    .kanji("模", "mo", "も", "imitate, pattern"),
                    .kanji("類", "rui", "るい", "variety, sort"),
                    .kanji("油", "abura", "あぶら", "oil"),
                    .kanji("植", "u(eru)", "う(える)", "plant"),
                    .kanji("均", "kin", "きん", "level, average"),
                    .kanji("圧", "atsu", "あつ", "pressure (圧力)"),
                    .kanji("源", "minamoto", "みなもと", "source"),
                    .kanji("波", "nami", "なみ", "wave"),
                    .kanji("測", "haka(ru)", "はか(る)", "survey, measure"),
                    .kanji("宇", "u", "う", "eaves, universe"),
                    .kanji("燃", "mo(eru)", "も(える)", "burn"),
                    .kanji("析", "seki", "せき", "analyze (分析)"),
                    .kanji("宙", "chuu", "ちゅう", "midair, space"),
                    .kanji("陽", "you", "よう", "sun, positive"),
                    .kanji("液", "eki", "えき", "liquid"),
                    .kanji("酸", "san", "さん", "acid"),
                    .kanji("鋼", "hagane", "はがね", "steel"),
                    .kanji("炭", "tan", "たん", "charcoal, carbon"),
                    .kanji("械", "kai", "かい", "mechanism"),
                    .kanji("炉", "ro", "ろ", "furnace, hearth (原子炉)"),
                    .kanji("溶", "to(keru)", "と(ける)", "melt, dissolve"),
                    .kanji("鉱", "kou", "こう", "ore, mineral (鉱山)"),
                    .kanji("胞", "hou", "ほう", "cell, sac (細胞)"),
                    .kanji("銅", "dou", "どう", "copper, bronze"),
                    .kanji("顕", "ken", "けん", "manifest, visible (顕微鏡)"),
                    .kanji("晶", "shou", "しょう", "crystal, clear (結晶)"),
                    .kanji("磁", "ji", "じ", "magnet, porcelain (磁石)"),
                    .kanji("循", "jun", "じゅん", "circulate (循環)"),
                    .kanji("鉛", "namari", "なまり", "lead (metal)"),
                    .kanji("窒", "chitsu", "ちつ", "suffocate, nitrogen (窒素)"),
                    .kanji("塊", "katamari", "かたまり", "lump, mass"),
                    .kanji("衡", "kou", "こう", "balance, scale (均衡)"),
                    .kanji("硫", "ryuu", "りゅう", "sulfur (硫黄)"),
                    .kanji("泡", "awa", "あわ", "bubble, foam"),
                    .kanji("剖", "bou", "ぼう", "dissect (解剖)"),
                    .kanji("鋳", "chuu", "ちゅう", "cast (metal) (鋳造)"),
                    .kanji("硝", "shou", "しょう", "nitrate, saltpeter (硝酸)"),
                    .kanji("堆", "tai", "たい", "heap, sediment (堆積)"),
                    .kanji("錬", "ren", "れん", "temper (metal), train (錬金術)"),
                    .kanji("冶", "ya", "や", "smelting (冶金)")
                ]
            )
        ],
        lessonOrder: "本学問理化題記教書文電位校語球補研術算究質試験英技復課種量核字答専管科授紙師材読具辞講装素模類油植宿習均圧留源波測卒順練博絡徒績欠宇燃緒析章宙勉陽訓液酸鋼塾炭彰械炉溶鉱胞准奨漢銅顕班晶詞磁循寮鉛窒塊衡硫泡剖鋳硝堆錬冶彙註"
    )
}
