import Foundation

extension MojiAlphabetData {
    static let kanjiWork = MojiPageDefinition(
        page: .kanji(.work),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "office",
                title: "Work & office",
                subtitle: "Posts, paperwork and getting things done",
                columns: 4,
                cells: [
                    .kanji("会", "kai", "かい", "meeting, society"),
                    .kanji("事", "koto", "こと", "matter, fact"),
                    .kanji("社", "sha", "しゃ", "company, shrine"),
                    .kanji("業", "gyou", "ぎょう", "business, industry"),
                    .kanji("用", "you", "よう", "errand, purpose"),
                    .kanji("物", "mono", "もの", "thing, object"),
                    .kanji("品", "shina", "しな", "goods, refinement"),
                    .kanji("料", "ryou", "りょう", "fee, materials"),
                    .kanji("工", "kou", "こう", "craft, construction"),
                    .kanji("副", "fuku", "ふく", "vice-, side (副作用)"),
                    .kanji("労", "rou", "ろう", "labor, toil (労働)"),
                    .kanji("監", "kan", "かん", "oversee (監督)"),
                    .kanji("働", "hatara(ku)", "はたら(く)", "work"),
                    .kanji("仕", "shi", "し", "serve, do"),
                    .kanji("渉", "shou", "しょう", "negotiate (交渉)"),
                    .kanji("督", "toku", "とく", "direct, coach (監督)"),
                    .kanji("催", "sai", "さい", "hold an event (開催)"),
                    .kanji("従", "shitaga(u)", "したが(う)", "obey, follow (従う)"),
                    .kanji("採", "sai", "さい", "adopt, pick (採用)"),
                    .kanji("遣", "ken", "けん", "dispatch (派遣)"),
                    .kanji("僚", "ryou", "りょう", "colleague (同僚)"),
                    .kanji("署", "sho", "しょ", "station, signature (署名)"),
                    .kanji("司", "shi", "し", "administer, boss (上司)"),
                    .kanji("承", "shou", "しょう", "acknowledge (承知)"),
                    .kanji("締", "shi(meru)", "し(める)", "tighten, close (締め切り)"),
                    .kanji("執", "shitsu", "しつ", "execute, cling (執行)"),
                    .kanji("募", "bo", "ぼ", "recruit (募集)"),
                    .kanji("功", "kou", "こう", "merit, success (成功)"),
                    .kanji("項", "kou", "こう", "item, clause (項目)"),
                    .kanji("揮", "ki", "き", "wield, command (指揮)"),
                    .kanji("雇", "yato(u)", "やと(う)", "employ, hire (雇う)"),
                    .kanji("顧", "ko", "こ", "look back, client (顧客)"),
                    .kanji("免", "men", "めん", "exempt, license (免許)"),
                    .kanji("封", "fuu", "ふう", "seal (封筒)"),
                    .kanji("陳", "chin", "ちん", "display, state (陳列)"),
                    .kanji("遇", "guu", "ぐう", "treat (people), meet (待遇)"),
                    .kanji("簿", "bo", "ぼ", "register, ledger (名簿)"),
                    .kanji("帳", "chou", "ちょう", "notebook (手帳)"),
                    .kanji("諾", "daku", "だく", "consent (承諾)"),
                    .kanji("添", "so(eru)", "そ(える)", "attach, add (添付)"),
                    .kanji("欄", "ran", "らん", "column, blank (欄)"),
                    .kanji("訂", "tei", "てい", "correct (訂正)"),
                    .kanji("弊", "hei", "へい", "our (humble), harm (弊社)"),
                    .kanji("嘱", "shoku", "しょく", "commission (嘱託)"),
                    .kanji("謄", "tou", "とう", "official copy (謄本)"),
                    .kanji("吏", "ri", "り", "civil servant (官吏)"),
                    .kanji("宛", "a(teru)", "あ(てる)", "address to (宛先)"),
                    .kanji("捗", "choku", "ちょく", "make progress (進捗)"),
                    .kanji("箋", "sen", "せん", "note paper (便箋)")
                ]
            ),
            MojiSectionDefinition(
                key: "business",
                title: "Money & business",
                subtitle: "Prices, jobs and the economy",
                columns: 4,
                cells: [
                    .kanji("金", "kane", "かね", "money, gold"),
                    .kanji("支", "sasa(eru)", "ささ(える)", "support"),
                    .kanji("済", "su(mu)", "す(む)", "be finished, settle"),
                    .kanji("得", "e(ru)", "え(る)", "obtain, advantage"),
                    .kanji("資", "shi", "し", "resources, capital"),
                    .kanji("価", "ka", "か", "value (価格)"),
                    .kanji("企", "ki", "き", "plan, undertake"),
                    .kanji("税", "zei", "ぜい", "tax"),
                    .kanji("営", "ei", "えい", "run (a business)"),
                    .kanji("職", "shoku", "しょく", "job"),
                    .kanji("供", "kyou", "きょう", "supply, offer"),
                    .kanji("役", "yaku", "やく", "role, service"),
                    .kanji("費", "hi", "ひ", "expense"),
                    .kanji("収", "shuu", "しゅう", "income, obtain"),
                    .kanji("輸", "yu", "ゆ", "transport"),
                    .kanji("率", "ritsu", "りつ", "rate, ratio"),
                    .kanji("農", "nou", "のう", "agriculture"),
                    .kanji("額", "gaku", "がく", "amount, frame"),
                    .kanji("商", "shou", "しょう", "commerce"),
                    .kanji("担", "tan", "たん", "bear (担当)"),
                    .kanji("退", "tai", "たい", "retreat, retire"),
                    .kanji("造", "zou", "ぞう", "create, structure"),
                    .kanji("株", "kabu", "かぶ", "stock, share"),
                    .kanji("融", "yuu", "ゆう", "fuse, finance (金融)"),
                    .kanji("製", "sei", "せい", "manufacture"),
                    .kanji("財", "zai", "ざい", "property (財布)"),
                    .kanji("値", "ne", "ね", "price"),
                    .kanji("易", "eki", "えき", "easy, trade"),
                    .kanji("給", "kyuu", "きゅう", "salary, supply"),
                    .kanji("就", "shuu", "しゅう", "take (a job)"),
                    .kanji("販", "han", "はん", "sell (販売)"),
                    .kanji("貿", "bou", "ぼう", "foreign trade"),
                    .kanji("益", "eki", "えき", "gain, benefit"),
                    .kanji("債", "sai", "さい", "debt, bond"),
                    .kanji("損", "son", "そん", "loss"),
                    .kanji("貨", "ka", "か", "goods, currency"),
                    .kanji("勤", "tsuto(meru)", "つと(める)", "work for"),
                    .kanji("契", "kei", "けい", "contract, pledge"),
                    .kanji("需", "ju", "じゅ", "demand"),
                    .kanji("購", "kou", "こう", "purchase (購入)"),
                    .kanji("賃", "chin", "ちん", "wage, fare"),
                    .kanji("預", "azu(keru)", "あず(ける)", "deposit"),
                    .kanji("納", "osa(meru)", "おさ(める)", "pay in, supply, put away"),
                    .kanji("銭", "sen", "せん", "coin, sen (1/100 yen)"),
                    .kanji("貯", "cho", "ちょ", "save (money)"),
                    .kanji("蓄", "takuwa(eru)", "たくわ(える)", "store up, amass"),
                    .kanji("稼", "kase(gu)", "かせ(ぐ)", "earn (money)"),
                    .kanji("銘", "mei", "めい", "inscription, brand (銘柄)"),
                    .kanji("騰", "tou", "とう", "soar, skyrocket (高騰)"),
                    .kanji("酬", "shuu", "しゅう", "reward, pay back (報酬)"),
                    .kanji("卸", "oro(su)", "おろ(す)", "wholesale (卸売り)"),
                    .kanji("乏", "tobo(shii)", "とぼ(しい)", "scarce, meager"),
                    .kanji("幣", "hei", "へい", "currency, banknote (紙幣)"),
                    .kanji("俸", "hou", "ほう", "annual pay, salary (年俸)"),
                    .kanji("款", "kan", "かん", "contract terms (約款)"),
                    .kanji("廉", "ren", "れん", "inexpensive, upright (廉価)"),
                    .kanji("租", "so", "そ", "land tax, lease (租税)"),
                    .kanji("儲", "mou(keru)", "もう(ける)", "make a profit"),
                    .kanji("賦", "fu", "ふ", "levy, installments (月賦)"),
                    .kanji("綻", "hokoro(biru)", "ほころ(びる)", "come apart, collapse (破綻)")
                ]
            )
        ],
        lessonOrder: "会事社業金用支済得資物品価企税料工営職供役費収副輸率農労額監商働担退造株仕融製財渉値督催易従採給就販貿遣益僚署債司承締執損募貨勤功項契需購揮賃雇預納銭顧免貯封蓄稼陳遇簿銘騰帳諾添酬卸欄乏訂弊幣俸款嘱廉租謄儲吏賦宛捗箋綻"
    )
}
