import Foundation

extension MojiAlphabetData {
    static let kanjiPeople = MojiPageDefinition(
        page: .kanji(.people),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "family",
                title: "Family & friends",
                subtitle: "Family, friends and everyone else",
                columns: 4,
                cells: [
                    .kanji("人", "hito", "ひと", "person"),
                    .kanji("自", "ji", "じ", "self"),
                    .kanji("生", "i(kiru)", "い(きる)", "live, life"),
                    .kanji("者", "sha", "しゃ", "-er (someone who)"),
                    .kanji("員", "in", "いん", "member, staff"),
                    .kanji("子", "ko", "こ", "child"),
                    .kanji("氏", "shi", "し", "family name, Mr."),
                    .kanji("主", "shu", "しゅ", "master, main"),
                    .kanji("女", "onna", "おんな", "woman"),
                    .kanji("名", "na", "な", "name"),
                    .kanji("男", "otoko", "おとこ", "man"),
                    .kanji("私", "watashi", "わたし", "I, private"),
                    .kanji("夫", "otto", "おっと", "husband"),
                    .kanji("族", "zoku", "ぞく", "clan (家族)"),
                    .kanji("親", "oya", "おや", "parent"),
                    .kanji("様", "sama", "さま", "Mr./Ms., manner"),
                    .kanji("達", "tachi", "たち", "plural (-tachi)"),
                    .kanji("客", "kyaku", "きゃく", "guest, customer"),
                    .kanji("母", "haha", "はは", "mother"),
                    .kanji("友", "tomo", "とも", "friend"),
                    .kanji("父", "chichi", "ちち", "father"),
                    .kanji("彼", "kare", "かれ", "he, boyfriend"),
                    .kanji("婦", "fu", "ふ", "woman, wife"),
                    .kanji("児", "ji", "じ", "infant"),
                    .kanji("妻", "tsuma", "つま", "wife"),
                    .kanji("婚", "kon", "こん", "marriage"),
                    .kanji("齢", "rei", "れい", "age"),
                    .kanji("老", "rou", "ろう", "old age"),
                    .kanji("我", "ware", "われ", "self, ego"),
                    .kanji("仲", "naka", "なか", "relationship"),
                    .kanji("君", "kimi", "きみ", "you"),
                    .kanji("弟", "otouto", "おとうと", "younger brother"),
                    .kanji("兄", "ani", "あに", "older brother"),
                    .kanji("祖", "so", "そ", "ancestor"),
                    .kanji("僕", "boku", "ぼく", "I (boys)"),
                    .kanji("皆", "mina", "みな", "everyone"),
                    .kanji("孫", "mago", "まご", "grandchild"),
                    .kanji("妹", "imouto", "いもうと", "younger sister"),
                    .kanji("姉", "ane", "あね", "older sister"),
                    .kanji("誰", "dare", "だれ", "who"),
                    .kanji("俺", "ore", "おれ", "I (rough)")
                ]
            ),
            MojiSectionDefinition(
                key: "relations",
                title: "People around you",
                subtitle: "Relatives, partners and how people are called",
                columns: 4,
                cells: [
                    .kanji("己", "ko", "こ", "oneself (自己)"),
                    .kanji("童", "dou", "どう", "child, fairy tale (童話)"),
                    .kanji("娘", "musume", "むすめ", "daughter (娘)"),
                    .kanji("幼", "osana(i)", "おさな(い)", "very young, infancy (幼い)"),
                    .kanji("孤", "ko", "こ", "solitary, orphan (孤独)"),
                    .kanji("縁", "en", "えん", "fate, bond (縁)"),
                    .kanji("曽", "sou", "そう", "great- (曽祖父)"),
                    .kanji("輩", "hai", "はい", "fellow, comrade (先輩)"),
                    .kanji("稚", "chi", "ち", "childish, immature (幼稚)"),
                    .kanji("嫁", "yome", "よめ", "bride, daughter-in-law (嫁)"),
                    .kanji("賓", "hin", "ひん", "honored guest (来賓)"),
                    .kanji("匠", "takumi", "たくみ", "artisan, master (師匠)"),
                    .kanji("伯", "haku", "はく", "uncle, count (伯爵)"),
                    .kanji("紳", "shin", "しん", "gentleman (紳士)"),
                    .kanji("坊", "bou", "ぼう", "boy, monk (坊主)"),
                    .kanji("淑", "shuku", "しゅく", "graceful lady (淑女)"),
                    .kanji("奴", "yatsu", "やつ", "guy, slave (奴)"),
                    .kanji("叔", "shuku", "しゅく", "younger uncle (叔父)"),
                    .kanji("姻", "in", "いん", "marriage (婚姻)"),
                    .kanji("隷", "rei", "れい", "slave, servant (奴隷)"),
                    .kanji("寡", "ka", "か", "widow, few (寡黙)"),
                    .kanji("朋", "tomo", "とも", "pal (朋)"),
                    .kanji("嬢", "jou", "じょう", "young lady, Miss (お嬢さん)"),
                    .kanji("翁", "ou", "おう", "old man (翁)"),
                    .kanji("婿", "muko", "むこ", "son-in-law, groom (婿)"),
                    .kanji("嫡", "chaku", "ちゃく", "legitimate heir (嫡子)"),
                    .kanji("絆", "kizuna", "きずな", "bonds (絆)"),
                    .kanji("婆", "baba", "ばば", "old woman, granny (お婆さん)"),
                    .kanji("伶", "rei", "れい", "court musician (伶人)"),
                    .kanji("胤", "in", "いん", "offspring, lineage (胤)"),
                    .kanji("麿", "maro", "まろ", "I (old), name ending (麿)"),
                    .kanji("侶", "ryo", "りょ", "life partner, companion (伴侶)"),
                    .kanji("戚", "seki", "せき", "relatives (親戚)"),
                    .kanji("姥", "uba", "うば", "old crone (山姥)"),
                    .kanji("姪", "mei", "めい", "niece (姪)"),
                    .kanji("甥", "oi", "おい", "nephew (甥)")
                ]
            )
        ],
        lessonOrder: "人自生者員子氏主女名男私夫族親様達客母友父彼婦児妻婚齢老我仲君己童娘弟兄祖幼僕孤皆縁曽輩孫妹姉稚嫁賓匠伯紳坊淑奴誰俺叔姻隷寡朋嬢翁婿嫡絆婆伶胤麿侶戚姥姪甥"
    )
}
