import Foundation

extension MojiAlphabetData {
    static let kanjiSociety = MojiPageDefinition(
        page: .kanji(.society),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "politics",
                title: "Politics",
                subtitle: "Government and the news",
                columns: 4,
                cells: [
                    .kanji("政", "sei", "せい", "politics"),
                    .kanji("議", "gi", "ぎ", "debate"),
                    .kanji("民", "min", "みん", "people, nation"),
                    .kanji("党", "tou", "とう", "political party"),
                    .kanji("戦", "sen", "せん", "war, battle"),
                    .kanji("法", "hou", "ほう", "law, method"),
                    .kanji("制", "sei", "せい", "control, system"),
                    .kanji("治", "ji", "じ", "govern, cure"),
                    .kanji("務", "mu", "む", "task"),
                    .kanji("統", "tou", "とう", "unite, govern"),
                    .kanji("総", "sou", "そう", "general, total"),
                    .kanji("領", "ryou", "りょう", "territory, rule"),
                    .kanji("改", "arata(meru)", "あらた(める)", "reform, revise"),
                    .kanji("権", "ken", "けん", "right, authority"),
                    .kanji("府", "fu", "ふ", "government office"),
                    .kanji("共", "tomo", "とも", "together"),
                    .kanji("際", "sai", "さい", "occasion, border"),
                    .kanji("委", "i", "い", "committee"),
                    .kanji("軍", "gun", "ぐん", "army"),
                    .kanji("案", "an", "あん", "proposal, idea"),
                    .kanji("策", "saku", "さく", "policy, measure"),
                    .kanji("任", "nin", "にん", "entrust, duty"),
                    .kanji("論", "ron", "ろん", "argument, theory"),
                    .kanji("官", "kan", "かん", "official"),
                    .kanji("革", "kaku", "かく", "leather, revolution"),
                    .kanji("挙", "kyo", "きょ", "raise, election"),
                    .kanji("争", "araso(u)", "あらそ(う)", "dispute"),
                    .kanji("防", "fuse(gu)", "ふせ(ぐ)", "prevent, defend"),
                    .kanji("条", "jou", "じょう", "article, clause"),
                    .kanji("武", "bu", "ぶ", "military, martial"),
                    .kanji("衛", "ei", "えい", "guard"),
                    .kanji("義", "gi", "ぎ", "righteousness, -ism"),
                    .kanji("閣", "kaku", "かく", "cabinet, tower"),
                    .kanji("衆", "shuu", "しゅう", "masses, multitude"),
                    .kanji("票", "hyou", "ひょう", "ballot"),
                    .kanji("兵", "hei", "へい", "soldier"),
                    .kanji("器", "ki", "き", "vessel, device"),
                    .kanji("省", "shou", "しょう", "ministry, omit"),
                    .kanji("憲", "ken", "けん", "constitution"),
                    .kanji("盟", "mei", "めい", "alliance, oath"),
                    .kanji("責", "seki", "せき", "responsibility, blame"),
                    .kanji("隊", "tai", "たい", "squad"),
                    .kanji("邦", "hou", "ほう", "home country, Japanese"),
                    .kanji("障", "shou", "しょう", "hinder (障害)"),
                    .kanji("庁", "chou", "ちょう", "agency"),
                    .kanji("令", "rei", "れい", "order, command"),
                    .kanji("措", "so", "そ", "measure, step (措置)"),
                    .kanji("律", "ritsu", "りつ", "rule, rhythm"),
                    .kanji("閥", "batsu", "ばつ", "clique (財閥)"),
                    .kanji("旗", "hata", "はた", "flag"),
                    .kanji("擁", "you", "よう", "embrace, back (擁護)"),
                    .kanji("臣", "shin", "しん", "retainer, minister"),
                    .kanji("諮", "haka(ru)", "はか(る)", "consult (a panel)"),
                    .kanji("宰", "sai", "さい", "preside, manage (宰相)"),
                    .kanji("轄", "katsu", "かつ", "jurisdiction (管轄)"),
                    .kanji("枢", "suu", "すう", "pivot, hub (中枢)"),
                    .kanji("糾", "kyuu", "きゅう", "denounce, entwine (糾弾)"),
                    .kanji("迭", "tetsu", "てつ", "reshuffle, alternate (更迭)"),
                    .kanji("劾", "gai", "がい", "impeach (弾劾)"),
                    .kanji("罷", "hi", "ひ", "quit, dismiss from office (罷免)")
                ]
            ),
            MojiSectionDefinition(
                key: "community",
                title: "Society & life",
                subtitle: "Ceremonies, family and community",
                columns: 4,
                cells: [
                    .kanji("協", "kyou", "きょう", "cooperate"),
                    .kanji("団", "dan", "だん", "group, corps"),
                    .kanji("各", "kaku", "かく", "each"),
                    .kanji("式", "shiki", "しき", "ceremony, style"),
                    .kanji("格", "kaku", "かく", "status, standard"),
                    .kanji("境", "kyou", "きょう", "border"),
                    .kanji("護", "go", "ご", "protect (care)"),
                    .kanji("育", "soda(teru)", "そだ(てる)", "raise"),
                    .kanji("域", "iki", "いき", "region"),
                    .kanji("環", "kan", "かん", "environment, loop"),
                    .kanji("差", "sa", "さ", "difference"),
                    .kanji("福", "fuku", "ふく", "blessing, welfare"),
                    .kanji("離", "hana(reru)", "はな(れる)", "separate"),
                    .kanji("介", "kai", "かい", "mediate, care"),
                    .kanji("富", "tomi", "とみ", "riches"),
                    .kanji("般", "han", "はん", "general (一般)"),
                    .kanji("儀", "gi", "ぎ", "rite, formality (儀式)"),
                    .kanji("級", "kyuu", "きゅう", "class, grade"),
                    .kanji("等", "tou", "とう", "equal, etc."),
                    .kanji("層", "sou", "そう", "layer"),
                    .kanji("養", "yashina(u)", "やしな(う)", "foster, nurture"),
                    .kanji("籍", "seki", "せき", "family register, enrollment (戸籍)"),
                    .kanji("紹", "shou", "しょう", "introduce"),
                    .kanji("暮", "ku(rasu)", "く(らす)", "live (one's life), dusk"),
                    .kanji("誕", "tan", "たん", "be born (誕生)"),
                    .kanji("賀", "ga", "が", "congratulate (年賀状)"),
                    .kanji("祉", "shi", "し", "welfare (福祉)"),
                    .kanji("郷", "kyou", "きょう", "hometown, village (故郷)"),
                    .kanji("里", "sato", "さと", "village, home (里帰り)"),
                    .kanji("懇", "kon", "こん", "cordial, intimate (懇親会)"),
                    .kanji("祝", "iwa(u)", "いわ(う)", "celebrate"),
                    .kanji("礼", "rei", "れい", "courtesy, thanks"),
                    .kanji("貧", "mazu(shii)", "まず(しい)", "poor"),
                    .kanji("慶", "kei", "けい", "celebration, felicity (慶事)"),
                    .kanji("披", "hi", "ひ", "disclose, unveil (披露)"),
                    .kanji("庶", "sho", "しょ", "common people (庶民)"),
                    .kanji("俗", "zoku", "ぞく", "worldly, vulgar (俗語)"),
                    .kanji("飢", "u(eru)", "う(える)", "go hungry, famine (飢饉)"),
                    .kanji("宴", "en", "えん", "banquet, party (宴会)"),
                    .kanji("餓", "ga", "が", "starvation (餓死)"),
                    .kanji("扶", "fu", "ふ", "provide for, help (扶養)"),
                    .kanji("睦", "boku", "ぼく", "friendly, harmonious (親睦)")
                ]
            ),
            MojiSectionDefinition(
                key: "law",
                title: "Law & safety",
                subtitle: "Crime, courts and disasters",
                columns: 4,
                cells: [
                    .kanji("反", "han", "はん", "anti-, oppose"),
                    .kanji("判", "han", "はん", "judgment"),
                    .kanji("疑", "utaga(u)", "うたが(う)", "doubt"),
                    .kanji("裁", "sai", "さい", "court trial"),
                    .kanji("証", "shou", "しょう", "evidence"),
                    .kanji("規", "ki", "き", "regulation"),
                    .kanji("害", "gai", "がい", "harm"),
                    .kanji("警", "kei", "けい", "warn, police"),
                    .kanji("審", "shin", "しん", "judge, screen (審査)"),
                    .kanji("訴", "utta(eru)", "うった(える)", "sue, appeal"),
                    .kanji("被", "hi", "ひ", "suffer, cover"),
                    .kanji("察", "satsu", "さつ", "perceive, inspect"),
                    .kanji("殺", "koro(su)", "ころ(す)", "kill"),
                    .kanji("捜", "saga(su)", "さが(す)", "search for (捜査)"),
                    .kanji("捕", "tsuka(maeru)", "つか(まえる)", "catch"),
                    .kanji("故", "ko", "こ", "accident (事故)"),
                    .kanji("暴", "bou", "ぼう", "violence"),
                    .kanji("険", "ken", "けん", "steep, risky"),
                    .kanji("罪", "tsumi", "つみ", "sin, guilt"),
                    .kanji("則", "soku", "そく", "principle"),
                    .kanji("逮", "tai", "たい", "arrest (逮捕)"),
                    .kanji("救", "suku(u)", "すく(う)", "rescue"),
                    .kanji("償", "tsuguna(u)", "つぐな(う)", "compensate, atone"),
                    .kanji("拠", "kyo", "きょ", "basis"),
                    .kanji("刑", "kei", "けい", "punishment"),
                    .kanji("犯", "han", "はん", "commit (a crime)"),
                    .kanji("震", "shin", "しん", "quake"),
                    .kanji("逃", "ni(geru)", "に(げる)", "escape"),
                    .kanji("災", "sai", "さい", "disaster"),
                    .kanji("盗", "nusu(mu)", "ぬす(む)", "steal"),
                    .kanji("訟", "shou", "しょう", "lawsuit (訴訟)"),
                    .kanji("偽", "nise", "にせ", "fake, false"),
                    .kanji("脅", "odo(su)", "おど(す)", "threaten"),
                    .kanji("罰", "batsu", "ばつ", "penalty"),
                    .kanji("賠", "bai", "ばい", "compensation (賠償)"),
                    .kanji("秩", "chitsu", "ちつ", "regularity, order (秩序)"),
                    .kanji("賄", "makana(u)", "まかな(う)", "cover (costs), bribe (賄賂)"),
                    .kanji("懲", "ko(riru)", "こ(りる)", "learn a lesson, punish (懲役)"),
                    .kanji("廷", "tei", "てい", "law court, royal court (法廷)"),
                    .kanji("虐", "gyaku", "ぎゃく", "cruelty, abuse (虐待)"),
                    .kanji("拐", "kai", "かい", "kidnap (誘拐)"),
                    .kanji("詐", "sa", "さ", "fraud (詐欺)"),
                    .kanji("欺", "azamu(ku)", "あざむ(く)", "deceive"),
                    .kanji("殴", "nagu(ru)", "なぐ(る)", "punch, beat"),
                    .kanji("偵", "tei", "てい", "spy, detect (探偵)"),
                    .kanji("赦", "sha", "しゃ", "pardon (恩赦)"),
                    .kanji("窃", "setsu", "せつ", "theft, stealthy (窃盗)"),
                    .kanji("陪", "bai", "ばい", "jury, attend on (陪審)"),
                    .kanji("禍", "ka", "か", "calamity, woe (災禍)"),
                    .kanji("賊", "zoku", "ぞく", "bandit, rebel (海賊)"),
                    .kanji("拷", "gou", "ごう", "torture (拷問)"),
                    .kanji("囚", "shuu", "しゅう", "prisoner (囚人)"),
                    .kanji("拉", "ra", "ら", "abduct, drag off (拉致)"),
                    .kanji("毀", "ki", "き", "damage, break (毀損)"),
                    .kanji("賂", "ro", "ろ", "bribe (賄賂)"),
                    .kanji("蔽", "hei", "へい", "conceal, cover up (隠蔽)"),
                    .kanji("踪", "sou", "そう", "trace, whereabouts (失踪)"),
                    .kanji("錮", "ko", "こ", "confinement (禁錮)")
                ]
            )
        ],
        lessonOrder: "政議民党戦法制治務協統総領改権府共際委軍反判案策団任論官各革式挙争格疑裁証防境規護害条警育武域衛環審義訴被閣差衆福察票兵器省憲離殺盟捜責捕隊故介富般邦暴険罪儀障則逮級庁等救層令措償拠刑犯養震籍逃紹災暮律誕盗賀訟祉閥郷里懇偽脅祝礼旗貧擁罰賠臣秩賄慶懲諮披廷虐拐詐欺庶宰俗殴飢宴餓轄枢糾偵赦窃扶迭陪睦禍賊拷劾罷囚拉毀賂蔽踪錮"
    )
}
