import Foundation

extension MojiAlphabetData {
    static let kanjiNumbers = MojiPageDefinition(
        page: .kanji(.numbers),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "numbers",
                title: "Numbers & counting",
                subtitle: "Counting things, money and order",
                columns: 4,
                cells: [
                    .kanji("一", "ichi", "いち", "one"),
                    .kanji("十", "juu", "じゅう", "ten"),
                    .kanji("二", "ni", "に", "two"),
                    .kanji("三", "san", "さん", "three"),
                    .kanji("五", "go", "ご", "five"),
                    .kanji("四", "yon", "よん", "four"),
                    .kanji("回", "kai", "かい", "times, round"),
                    .kanji("九", "kyuu", "きゅう", "nine"),
                    .kanji("円", "en", "えん", "yen, circle"),
                    .kanji("八", "hachi", "はち", "eight"),
                    .kanji("六", "roku", "ろく", "six"),
                    .kanji("度", "do", "ど", "degree"),
                    .kanji("七", "nana", "なな", "seven"),
                    .kanji("数", "kazu", "かず", "number, count"),
                    .kanji("第", "dai", "だい", "-th (ordinal)"),
                    .kanji("百", "hyaku", "ひゃく", "hundred"),
                    .kanji("点", "ten", "てん", "point, dot"),
                    .kanji("千", "sen", "せん", "thousand"),
                    .kanji("半", "han", "はん", "half"),
                    .kanji("計", "kei", "けい", "measure, total"),
                    .kanji("両", "ryou", "りょう", "both"),
                    .kanji("台", "dai", "だい", "stand, platform"),
                    .kanji("歳", "sai", "さい", "years old"),
                    .kanji("番", "ban", "ばん", "turn, order"),
                    .kanji("万", "man", "まん", "ten thousand"),
                    .kanji("個", "ko", "こ", "piece"),
                    .kanji("号", "gou", "ごう", "issue No."),
                    .kanji("倍", "bai", "ばい", "double, -fold"),
                    .kanji("億", "oku", "おく", "hundred million"),
                    .kanji("枚", "mai", "まい", "sheet (counter)"),
                    .kanji("甲", "kou", "こう", "carapace, first rank (甲乙)"),
                    .kanji("兆", "chou", "ちょう", "trillion, omen"),
                    .kanji("零", "rei", "れい", "zero, spill"),
                    .kanji("乙", "otsu", "おつ", "B (second), chic"),
                    .kanji("伍", "go", "ご", "five, rank (落伍)"),
                    .kanji("壱", "ichi", "いち", "one (formal)"),
                    .kanji("丙", "hei", "へい", "C (third), third sign"),
                    .kanji("弐", "ni", "に", "two (formal)"),
                    .kanji("廿", "nijuu", "にじゅう", "twenty (廿)")
                ]
            ),
            MojiSectionDefinition(
                key: "shapes",
                title: "Shapes & positions",
                subtitle: "Sides, edges, lines and order",
                columns: 4,
                cells: [
                    .kanji("形", "katachi", "かたち", "shape"),
                    .kanji("辺", "hen", "へん", "vicinity, side (周辺)"),
                    .kanji("丸", "maru(i)", "まる(い)", "round"),
                    .kanji("周", "shuu", "しゅう", "around, lap (周り)"),
                    .kanji("幅", "haba", "はば", "width"),
                    .kanji("逆", "gyaku", "ぎゃく", "reverse, opposite (逆に)"),
                    .kanji("裏", "ura", "うら", "rear side, lining (裏)"),
                    .kanji("底", "soko", "そこ", "bottom"),
                    .kanji("枠", "waku", "わく", "frame (枠)"),
                    .kanji("列", "retsu", "れつ", "row, line (行列)"),
                    .kanji("端", "hashi", "はし", "edge, end (端)"),
                    .kanji("奥", "oku", "おく", "interior, depths (奥さん)"),
                    .kanji("範", "han", "はん", "range, model (範囲)"),
                    .kanji("沿", "so(u)", "そ(う)", "along (沿う)"),
                    .kanji("序", "jo", "じょ", "preface, beginning (序盤)"),
                    .kanji("距", "kyo", "きょ", "distance (距離)"),
                    .kanji("圏", "ken", "けん", "sphere, zone (圏外)"),
                    .kanji("菱", "hishi", "ひし", "rhombus (菱形)"),
                    .kanji("縦", "tate", "たて", "vertical, length (縦)"),
                    .kanji("軸", "jiku", "じく", "axis, shaft"),
                    .kanji("隔", "kaku", "かく", "interval, partition (間隔)"),
                    .kanji("緯", "i", "い", "latitude (緯度)"),
                    .kanji("径", "kei", "けい", "diameter (直径)"),
                    .kanji("軌", "ki", "き", "track, orbit (軌道)"),
                    .kanji("斜", "nana(me)", "なな(め)", "diagonal, slanting (斜め)"),
                    .kanji("隅", "sumi", "すみ", "corner, nook (隅)"),
                    .kanji("傍", "katawa(ra)", "かたわ(ら)", "beside, bystander (傍ら)"),
                    .kanji("郭", "kaku", "かく", "outline, enclosure (輪郭)"),
                    .kanji("垂", "ta(reru)", "た(れる)", "hang down, vertical (垂直)"),
                    .kanji("孔", "kou", "こう", "aperture, Confucius (孔子)"),
                    .kanji("尖", "toga(ru)", "とが(る)", "pointed (尖る)"),
                    .kanji("凸", "totsu", "とつ", "convex, bump (凸凹)"),
                    .kanji("凹", "heko(mu)", "へこ(む)", "concave, dent (凹む)"),
                    .kanji("弧", "ko", "こ", "arc, bracket (括弧)"),
                    .kanji("楕", "da", "だ", "ellipse (楕円)"),
                    .kanji("勾", "kou", "こう", "gradient, detain (勾配)"),
                    .kanji("隙", "suki", "すき", "gap, chance (隙間)"),
                    .kanji("叉", "sa", "さ", "prong, crossing (交叉)"),
                    .kanji("坦", "tan", "たん", "flat, level (平坦)"),
                    .kanji("窄", "saku", "さく", "constrict, narrowing (狭窄)")
                ]
            ),
            MojiSectionDefinition(
                key: "counters",
                title: "Counters & units",
                subtitle: "Counting words and old measures",
                columns: 4,
                cells: [
                    .kanji("双", "sou", "そう", "pair, twin (双子)"),
                    .kanji("杯", "hai", "はい", "cupful"),
                    .kanji("丁", "chou", "ちょう", "city block, exactly (丁度)"),
                    .kanji("冊", "satsu", "さつ", "book counter"),
                    .kanji("丈", "jou", "じょう", "length (大丈夫)"),
                    .kanji("匹", "hiki", "ひき", "animal counter"),
                    .kanji("軒", "ken", "けん", "house counter, eaves (一軒)"),
                    .kanji("隻", "seki", "せき", "ship counter, single"),
                    .kanji("寸", "sun", "すん", "Japanese inch, size (寸法)"),
                    .kanji("坪", "tsubo", "つぼ", "tsubo (3.3 m²)"),
                    .kanji("厘", "rin", "りん", "rin (1/1000)"),
                    .kanji("斗", "to", "と", "dipper (measure), Big Dipper (北斗)"),
                    .kanji("尺", "shaku", "しゃく", "shaku (30 cm), scale (尺度)"),
                    .kanji("升", "masu", "ます", "measuring box (1.8 L)"),
                    .kanji("斤", "kin", "きん", "loaf (bread unit), axe"),
                    .kanji("箇", "ka", "か", "unit, item counter (箇条)"),
                    .kanji("勺", "shaku", "しゃく", "small ladle unit (勺)"),
                    .kanji("匁", "monme", "もんめ", "monme, 3.75 g (匁)"),
                    .kanji("桁", "keta", "けた", "digit, crossbeam"),
                    .kanji("疋", "hiki", "ひき", "bolt of cloth"),
                    .kanji("頁", "peeji", "ページ", "page"),
                    .kanji("哩", "mairu", "まいる", "mile (哩)"),
                    .kanji("浬", "kairi", "かいり", "nautical mile (浬)")
                ]
            )
        ],
        lessonOrder: "一十二三五四回九円八六度七数第百点千半計両台歳番万形辺個丸周号幅逆倍億裏底枚枠列端奥双甲範沿序兆距圏零菱杯縦軸丁冊丈隔匹軒緯径軌斜隻隅傍寸郭垂坪厘乙伍斗尺孔升尖凸凹壱弧楕斤丙弐箇勺匁勾桁隙叉廿疋坦頁哩浬窄"
    )
}
