import Foundation

extension MojiAlphabetData {
    static let kanjiHome = MojiPageDefinition(
        page: .kanji(.home),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "home",
                title: "Home & tools",
                subtitle: "Furniture, containers and things you use",
                columns: 4,
                cells: [
                    .kanji("家", "ie", "いえ", "house, family"),
                    .kanji("宅", "taku", "たく", "home, residence"),
                    .kanji("蔵", "kura", "くら", "storehouse, fridge (冷蔵庫)"),
                    .kanji("戸", "to", "と", "door"),
                    .kanji("房", "bou", "ぼう", "room, tassel (冷房)"),
                    .kanji("庭", "niwa", "にわ", "yard"),
                    .kanji("板", "ita", "いた", "board, plank (板)"),
                    .kanji("壁", "kabe", "かべ", "wall"),
                    .kanji("縄", "nawa", "なわ", "straw rope (縄)"),
                    .kanji("柱", "hashira", "はしら", "pillar"),
                    .kanji("袋", "fukuro", "ふくろ", "bag"),
                    .kanji("浴", "a(biru)", "あ(びる)", "bathe, shower (浴びる)"),
                    .kanji("床", "yuka", "ゆか", "floorboards"),
                    .kanji("窓", "mado", "まど", "window"),
                    .kanji("飾", "kaza(ru)", "かざ(る)", "decorate (飾る)"),
                    .kanji("網", "ami", "あみ", "net (網)"),
                    .kanji("敷", "shi(ku)", "し(く)", "spread, lay (敷く)"),
                    .kanji("荷", "ni", "に", "luggage"),
                    .kanji("鎖", "kusari", "くさり", "chain (鎖)"),
                    .kanji("掃", "sou", "そう", "sweep, clean (掃除)"),
                    .kanji("卓", "taku", "たく", "table (食卓)"),
                    .kanji("干", "ho(su)", "ほ(す)", "dry, hang out (干す)"),
                    .kanji("箱", "hako", "はこ", "box"),
                    .kanji("玄", "gen", "げん", "entrance, dark (玄関)"),
                    .kanji("棒", "bou", "ぼう", "stick, pole (棒)"),
                    .kanji("鏡", "kagami", "かがみ", "mirror"),
                    .kanji("垣", "kaki", "かき", "hedge, fence (垣根)"),
                    .kanji("粧", "shou", "しょう", "makeup (化粧)"),
                    .kanji("棚", "tana", "たな", "shelf (棚)"),
                    .kanji("廊", "rou", "ろう", "corridor (廊下)"),
                    .kanji("灯", "tou", "とう", "lamp (電灯)"),
                    .kanji("筒", "tsutsu", "つつ", "tube, cylinder (封筒)"),
                    .kanji("畳", "tatami", "たたみ", "tatami, fold (畳む)"),
                    .kanji("机", "tsukue", "つくえ", "desk"),
                    .kanji("傘", "kasa", "かさ", "umbrella"),
                    .kanji("濯", "taku", "たく", "laundry (洗濯)"),
                    .kanji("扇", "sen", "せん", "folding fan (扇子)"),
                    .kanji("槽", "sou", "そう", "tank, tub (水槽)"),
                    .kanji("皿", "sara", "さら", "plate"),
                    .kanji("瓦", "kawara", "かわら", "roof tile (瓦)"),
                    .kanji("扉", "tobira", "とびら", "hinged door (扉)"),
                    .kanji("鉢", "hachi", "はち", "bowl, flowerpot (植木鉢)"),
                    .kanji("錠", "jou", "じょう", "lock, pill (錠剤)"),
                    .kanji("樽", "taru", "たる", "barrel, cask (樽)"),
                    .kanji("塀", "hei", "へい", "wall fence (塀)"),
                    .kanji("鍵", "kagi", "かぎ", "key"),
                    .kanji("臼", "usu", "うす", "mortar (臼)"),
                    .kanji("呂", "ro", "ろ", "bath (風呂)"),
                    .kanji("枕", "makura", "まくら", "pillow"),
                    .kanji("栓", "sen", "せん", "stopper, cork (栓)"),
                    .kanji("芯", "shin", "しん", "core, wick (芯)"),
                    .kanji("桶", "oke", "おけ", "tub, bucket (桶)"),
                    .kanji("椅", "i", "い", "chair (椅子)"),
                    .kanji("杭", "kui", "くい", "stake, post (杭)"),
                    .kanji("杖", "tsue", "つえ", "cane, staff (杖)"),
                    .kanji("蓋", "futa", "ふた", "lid (蓋)"),
                    .kanji("竿", "sao", "さお", "rod, fishing pole (竿)"),
                    .kanji("釘", "kugi", "くぎ", "nail (釘)"),
                    .kanji("巾", "kin", "きん", "rag, kerchief (雑巾)"),
                    .kanji("柵", "saku", "さく", "palisade, railing (柵)"),
                    .kanji("籠", "kago", "かご", "basket, cage (籠)"),
                    .kanji("煤", "susu", "すす", "soot (煤)"),
                    .kanji("襖", "fusuma", "ふすま", "sliding screen (襖)"),
                    .kanji("簞", "tan", "たん", "chest of drawers (簞笥)"),
                    .kanji("簾", "sudare", "すだれ", "bamboo blind (簾)"),
                    .kanji("蠟", "rou", "ろう", "wax, candle (蠟燭)")
                ]
            ),
            MojiSectionDefinition(
                key: "crafts",
                title: "Crafts & clothing",
                subtitle: "Fabric, sewing, pottery and jewels",
                columns: 4,
                cells: [
                    .kanji("針", "hari", "はり", "needle (針)"),
                    .kanji("織", "o(ru)", "お(る)", "weave (織る)"),
                    .kanji("玉", "tama", "たま", "gem, bead (玉)"),
                    .kanji("染", "so(meru)", "そ(める)", "dye, infect (感染)"),
                    .kanji("服", "fuku", "ふく", "clothes"),
                    .kanji("布", "nuno", "ぬの", "cloth"),
                    .kanji("宝", "takara", "たから", "treasure (宝石)"),
                    .kanji("柄", "gara", "がら", "pattern, handle (柄)"),
                    .kanji("衣", "i", "い", "garment"),
                    .kanji("錦", "nishiki", "にしき", "brocade (錦)"),
                    .kanji("繊", "sen", "せん", "fiber, delicate (繊維)"),
                    .kanji("糸", "ito", "いと", "thread"),
                    .kanji("綿", "wata", "わた", "cotton (綿)"),
                    .kanji("紋", "mon", "もん", "family crest, pattern (家紋)"),
                    .kanji("靴", "kutsu", "くつ", "shoes"),
                    .kanji("履", "ha(ku)", "は(く)", "put on (shoes), record (履歴)"),
                    .kanji("陶", "tou", "とう", "pottery (陶器)"),
                    .kanji("珠", "shu", "しゅ", "pearl, bead (真珠)"),
                    .kanji("縫", "nu(u)", "ぬ(う)", "sew (縫う)"),
                    .kanji("帽", "bou", "ぼう", "hat, cap (帽子)"),
                    .kanji("紡", "bou", "ぼう", "spin yarn (紡ぐ)"),
                    .kanji("絹", "kinu", "きぬ", "silk (絹)"),
                    .kanji("袖", "sode", "そで", "sleeve (袖)"),
                    .kanji("漆", "urushi", "うるし", "lacquer (漆)"),
                    .kanji("襟", "eri", "えり", "collar (襟)"),
                    .kanji("窯", "kama", "かま", "kiln (窯)"),
                    .kanji("埴", "hani", "はに", "clay (埴輪)"),
                    .kanji("袴", "hakama", "はかま", "hakama (袴)"),
                    .kanji("繕", "tsukuro(u)", "つくろ(う)", "mend, patch up (繕う)"),
                    .kanji("櫛", "kushi", "くし", "comb (櫛)"),
                    .kanji("裾", "suso", "すそ", "hem, foot of a slope (裾)"),
                    .kanji("瑠", "ru", "る", "lapis lazuli (瑠璃)"),
                    .kanji("縞", "shima", "しま", "stripe (縞)"),
                    .kanji("繭", "mayu", "まゆ", "cocoon (繭)"),
                    .kanji("塑", "so", "そ", "modeling, plastic (塑像)"),
                    .kanji("璃", "ri", "り", "glass gem (玻璃)"),
                    .kanji("衿", "eri", "えり", "kimono collar (衿)"),
                    .kanji("紬", "tsumugi", "つむぎ", "pongee silk (紬)"),
                    .kanji("綸", "rin", "りん", "silk thread (綸子)"),
                    .kanji("銑", "sen", "せん", "pig iron (銑鉄)"),
                    .kanji("煉", "ren", "れん", "refine, brick (煉瓦)"),
                    .kanji("釉", "yuu", "ゆう", "glaze (釉薬)"),
                    .kanji("箔", "haku", "はく", "foil, gilt (金箔)"),
                    .kanji("裳", "shou", "しょう", "skirt, costume (衣裳)"),
                    .kanji("錆", "sabi", "さび", "rust (錆)"),
                    .kanji("徽", "ki", "き", "badge, emblem (徽章)"),
                    .kanji("繡", "shuu", "しゅう", "embroidery (刺繡)")
                ]
            ),
            MojiSectionDefinition(
                key: "tools",
                title: "Old tools",
                subtitle: "Hats, ladders, saddles and inkstones",
                columns: 4,
                cells: [
                    .kanji("笠", "kasa", "かさ", "bamboo hat"),
                    .kanji("樋", "toi", "とい", "gutter, sluice"),
                    .kanji("梁", "hari", "はり", "beam, girder"),
                    .kanji("箕", "mi", "み", "winnowing basket"),
                    .kanji("帖", "chou", "ちょう", "album, quire (画帖)"),
                    .kanji("鞍", "kura", "くら", "saddle"),
                    .kanji("梯", "hashigo", "はしご", "ladder"),
                    .kanji("杵", "kine", "きね", "pestle"),
                    .kanji("碓", "usu", "うす", "treadle mortar"),
                    .kanji("竪", "tate", "たて", "harp, vertical (竪琴)"),
                    .kanji("矩", "ku", "く", "carpenter's square, rectangle (矩形)"),
                    .kanji("毬", "mari", "まり", "burr, ball (毬栗)"),
                    .kanji("槌", "tsuchi", "つち", "mallet, hammer"),
                    .kanji("硯", "suzuri", "すずり", "inkstone"),
                    .kanji("栞", "shiori", "しおり", "bookmark, guidebook"),
                    .kanji("錘", "omori", "おもり", "plumb weight, spindle (紡錘)"),
                    .kanji("鞠", "mari", "まり", "kickball, ball (蹴鞠)"),
                    .kanji("斧", "ono", "おの", "axe"),
                    .kanji("沓", "kutsu", "くつ", "footwear (old), crowd (雑沓)"),
                    .kanji("笈", "kyuu", "きゅう", "book backpack"),
                    .kanji("砥", "to", "と", "whetstone (砥石)"),
                    .kanji("砧", "kinuta", "きぬた", "fulling block"),
                    .kanji("秤", "hakari", "はかり", "scales, balance"),
                    .kanji("紐", "himo", "ひも", "strap, lace"),
                    .kanji("戟", "geki", "げき", "Chinese halberd, stimulus (刺戟)"),
                    .kanji("董", "tou", "とう", "antiques, supervise (骨董)"),
                    .kanji("楯", "tate", "たて", "wooden shield, buckler"),
                    .kanji("蓑", "mino", "みの", "straw raincoat"),
                    .kanji("鼎", "kanae", "かなえ", "tripod cauldron"),
                    .kanji("鞄", "kaban", "かばん", "briefcase, satchel"),
                    .kanji("駕", "ga", "が", "harness, surpass (凌駕)"),
                    .kanji("鋸", "nokogiri", "のこぎり", "saw"),
                    .kanji("錐", "kiri", "きり", "awl, drill"),
                    .kanji("輿", "koshi", "こし", "palanquin, public (輿論)"),
                    .kanji("鍬", "kuwa", "くわ", "hoe"),
                    .kanji("櫂", "kai", "かい", "oar, paddle"),
                    .kanji("鞭", "muchi", "むち", "whip"),
                    .kanji("櫓", "yagura", "やぐら", "watchtower, scull")
                ]
            )
        ],
        lessonOrder: "家宅蔵針戸織玉房庭染服布板壁縄柱袋浴宝柄床窓飾網敷衣荷鎖掃卓干箱玄錦繊棒糸綿笠鏡紋垣粧靴棚廊灯履筒畳机陶傘濯珠縫帽扇槽皿樋瓦扉紡鉢絹錠袖漆樽塀梁箕鍵襟臼呂窯枕埴袴繕栓芯帖桶鞍梯椅櫛杭裾瑠杵碓竪矩杖蓋竿毬槌縞繭釘硯塑璃衿栞紬綸銑錘鞠巾柵籠斧沓笈砥砧秤紐戟煉董釉楯煤蓑鼎箔裳鞄駕鋸錆錐徽襖輿鍬櫂簞繡鞭櫓簾蠟"
    )
}
