import Foundation

extension MojiAlphabetData {
    static let kanjiFood = MojiPageDefinition(
        page: .kanji(.food),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "meals",
                title: "Meals & drinks",
                subtitle: "Rice, meat, tea and tastes",
                columns: 4,
                cells: [
                    .kanji("米", "kome", "こめ", "rice (grain)"),
                    .kanji("果", "ka", "か", "result, fruit"),
                    .kanji("食", "ta(beru)", "た(べる)", "eat"),
                    .kanji("味", "aji", "あじ", "taste"),
                    .kanji("弁", "ben", "べん", "speech, bento"),
                    .kanji("飲", "no(mu)", "の(む)", "drink"),
                    .kanji("肉", "niku", "にく", "meat"),
                    .kanji("酒", "sake", "さけ", "alcohol"),
                    .kanji("飯", "meshi", "めし", "meal, cooked rice"),
                    .kanji("茶", "cha", "ちゃ", "tea"),
                    .kanji("塩", "shio", "しお", "salt"),
                    .kanji("乳", "chichi", "ちち", "milk"),
                    .kanji("菜", "sai", "さい", "vegetable"),
                    .kanji("卵", "tamago", "たまご", "egg"),
                    .kanji("湯", "yu", "ゆ", "hot water"),
                    .kanji("豆", "mame", "まめ", "bean"),
                    .kanji("糖", "tou", "とう", "sugar"),
                    .kanji("粉", "kona", "こな", "powder, flour"),
                    .kanji("麦", "mugi", "むぎ", "wheat"),
                    .kanji("菓", "ka", "か", "sweets"),
                    .kanji("汁", "shiru", "しる", "soup, juice"),
                    .kanji("酢", "su", "す", "vinegar"),
                    .kanji("胡", "ko", "こ", "foreign, sesame (胡麻)"),
                    .kanji("餅", "mochi", "もち", "rice cake (mochi)"),
                    .kanji("蜜", "mitsu", "みつ", "honey, nectar"),
                    .kanji("粥", "kayu", "かゆ", "rice porridge"),
                    .kanji("麺", "men", "めん", "noodles")
                ]
            ),
            MojiSectionDefinition(
                key: "kitchen",
                title: "Kitchen",
                subtitle: "Cooking, dishes and drinks",
                columns: 4,
                cells: [
                    .kanji("焼", "ya(ku)", "や(く)", "grill, bake"),
                    .kanji("旨", "mune", "むね", "tasty, gist (旨い)"),
                    .kanji("腐", "kusa(ru)", "くさ(る)", "rot, go bad (腐る)"),
                    .kanji("寿", "ju", "じゅ", "long life, sushi (寿司)"),
                    .kanji("揚", "a(geru)", "あ(げる)", "deep-fry, hoist (揚げる)"),
                    .kanji("喫", "kitsu", "きつ", "consume, smoke (喫茶)"),
                    .kanji("糧", "ryou", "りょう", "provisions (食糧)"),
                    .kanji("瓶", "bin", "びん", "bottle, vase (花瓶)"),
                    .kanji("缶", "kan", "かん", "can, tin (缶詰)"),
                    .kanji("蒸", "mu(su)", "む(す)", "steam (蒸す)"),
                    .kanji("煮", "ni(ru)", "に(る)", "simmer, boil (煮る)"),
                    .kanji("粒", "tsubu", "つぶ", "particle, drop (粒)"),
                    .kanji("沸", "wa(ku)", "わ(く)", "boil (water) (沸く)"),
                    .kanji("唐", "kara", "から", "Tang China, foreign (唐揚げ)"),
                    .kanji("釜", "kama", "かま", "iron pot (釜飯)"),
                    .kanji("炊", "ta(ku)", "た(く)", "cook rice (炊く)"),
                    .kanji("鍋", "nabe", "なべ", "pot, hot pot (鍋)"),
                    .kanji("漬", "tsu(keru)", "つ(ける)", "pickle, soak (漬物)"),
                    .kanji("醸", "jou", "じょう", "brew (醸造)"),
                    .kanji("酵", "kou", "こう", "ferment (発酵)"),
                    .kanji("抹", "matsu", "まつ", "matcha, erase (抹茶)"),
                    .kanji("丼", "donburi", "どんぶり", "rice bowl (丼)"),
                    .kanji("膳", "zen", "ぜん", "meal tray (膳)"),
                    .kanji("串", "kushi", "くし", "skewer (串)"),
                    .kanji("粟", "awa", "あわ", "millet (粟)"),
                    .kanji("箸", "hashi", "はし", "chopsticks (箸)"),
                    .kanji("惣", "sou", "そう", "deli dish (惣菜)"),
                    .kanji("酌", "shaku", "しゃく", "pour sake (晩酌)"),
                    .kanji("饗", "kyou", "きょう", "feast (饗宴)"),
                    .kanji("厨", "chuu", "ちゅう", "kitchen (厨房)"),
                    .kanji("煎", "sen", "せん", "roast, brew (煎茶)"),
                    .kanji("酎", "chuu", "ちゅう", "shochu (焼酎)"),
                    .kanji("肴", "sakana", "さかな", "snacks with drinks (肴)"),
                    .kanji("珈", "ka", "か", "coffee (珈琲)"),
                    .kanji("椀", "wan", "わん", "wooden bowl (椀)"),
                    .kanji("碗", "wan", "わん", "porcelain bowl (茶碗)"),
                    .kanji("馳", "chi", "ち", "treat, gallop (ご馳走)"),
                    .kanji("噌", "so", "そ", "miso (味噌)"),
                    .kanji("糊", "nori", "のり", "paste, glue (糊)"),
                    .kanji("瓢", "hyou", "ひょう", "gourd (瓢箪)"),
                    .kanji("醬", "shou", "しょう", "soy paste (醬油)")
                ]
            ),
            MojiSectionDefinition(
                key: "fruit",
                title: "Fruit & vegetables",
                subtitle: "From the market and the garden",
                columns: 4,
                cells: [
                    .kanji("梨", "nashi", "なし", "pear"),
                    .kanji("栗", "kuri", "くり", "chestnut"),
                    .kanji("柿", "kaki", "かき", "persimmon"),
                    .kanji("桃", "momo", "もも", "peach"),
                    .kanji("杏", "anzu", "あんず", "apricot"),
                    .kanji("芋", "imo", "いも", "potato, taro"),
                    .kanji("瓜", "uri", "うり", "melon, gourd"),
                    .kanji("柚", "yuzu", "ゆず", "yuzu citron"),
                    .kanji("茄", "ka", "か", "eggplant (茄子)"),
                    .kanji("杷", "ha", "は", "rake, loquat (枇杷)"),
                    .kanji("枇", "bi", "び", "loquat (枇杷)"),
                    .kanji("苺", "ichigo", "いちご", "strawberry"),
                    .kanji("茸", "kinoko", "きのこ", "mushroom"),
                    .kanji("萄", "dou", "どう", "grape (葡萄)"),
                    .kanji("葡", "bu", "ぶ", "Portugal, grape (葡萄)"),
                    .kanji("蕎", "kyou", "きょう", "buckwheat (蕎麦)"),
                    .kanji("蕪", "kabu", "かぶ", "turnip"),
                    .kanji("橙", "daidai", "だいだい", "bitter orange, orange (color)"),
                    .kanji("檎", "go", "ご", "apple (林檎)")
                ]
            )
        ],
        lessonOrder: "米果食味弁飲焼肉酒飯茶塩旨腐寿乳揚菜梨卵喫糧湯豆糖粉瓶缶栗蒸煮麦粒沸菓唐柿釜炊桃鍋漬醸汁酵酢胡抹丼膳串粟餅箸杏蜜惣酌粥麺饗芋厨煎瓜柚茄酎杷枇肴苺珈茸萄椀葡碗馳噌糊蕎蕪橙檎瓢醬"
    )
}
