import Foundation

extension MojiAlphabetData {
    static let kanjiMovement = MojiPageDefinition(
        page: .kanji(.movement),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "going",
                title: "Going places",
                subtitle: "Verbs for moving around",
                columns: 4,
                cells: [
                    .kanji("出", "de(ru)", "で(る)", "go out, exit"),
                    .kanji("行", "i(ku)", "い(く)", "go"),
                    .kanji("発", "hatsu", "はつ", "depart, emit"),
                    .kanji("入", "hai(ru)", "はい(る)", "enter"),
                    .kanji("動", "ugo(ku)", "うご(く)", "move"),
                    .kanji("通", "too(ru)", "とお(る)", "pass through, commute"),
                    .kanji("来", "ku(ru)", "く(る)", "come"),
                    .kanji("進", "susu(mu)", "すす(む)", "advance"),
                    .kanji("交", "kou", "こう", "mix, exchange"),
                    .kanji("運", "un", "うん", "carry, luck"),
                    .kanji("流", "naga(reru)", "なが(れる)", "flow"),
                    .kanji("過", "su(giru)", "す(ぎる)", "exceed, pass"),
                    .kanji("止", "to(maru)", "と(まる)", "stop"),
                    .kanji("送", "oku(ru)", "おく(る)", "send"),
                    .kanji("転", "ten", "てん", "roll, turn over"),
                    .kanji("訪", "tazu(neru)", "たず(ねる)", "visit"),
                    .kanji("着", "tsu(ku)", "つ(く)", "arrive, wear"),
                    .kanji("乗", "no(ru)", "の(る)", "ride"),
                    .kanji("追", "o(u)", "お(う)", "chase"),
                    .kanji("落", "o(chiru)", "お(ちる)", "fall, drop"),
                    .kanji("渡", "wata(su)", "わた(す)", "hand over, cross"),
                    .kanji("移", "utsu(ru)", "うつ(る)", "shift (移動)"),
                    .kanji("帰", "kae(ru)", "かえ(る)", "go home"),
                    .kanji("歩", "aru(ku)", "ある(く)", "walk"),
                    .kanji("登", "nobo(ru)", "のぼ(る)", "climb"),
                    .kanji("飛", "to(bu)", "と(ぶ)", "fly"),
                    .kanji("降", "o(riru)", "お(りる)", "get off, descend"),
                    .kanji("超", "chou", "ちょう", "super-, exceed"),
                    .kanji("迎", "muka(eru)", "むか(える)", "welcome"),
                    .kanji("走", "hashi(ru)", "はし(る)", "run"),
                    .kanji("避", "sa(keru)", "さ(ける)", "avoid"),
                    .kanji("迫", "sema(ru)", "せま(る)", "press, close in"),
                    .kanji("旅", "tabi", "たび", "trip"),
                    .kanji("戻", "modo(ru)", "もど(る)", "go back"),
                    .kanji("越", "ko(eru)", "こ(える)", "cross over (越す)"),
                    .kanji("届", "todo(ku)", "とど(く)", "be delivered"),
                    .kanji("到", "tou", "とう", "reach (到着)"),
                    .kanji("泳", "oyo(gu)", "およ(ぐ)", "swim")
                ]
            ),
            MojiSectionDefinition(
                key: "motion",
                title: "Motion",
                subtitle: "Rising, falling, floating and wandering",
                columns: 4,
                cells: [
                    .kanji("突", "totsu", "とつ", "sudden, thrust (突然)"),
                    .kanji("寄", "yo(ru)", "よ(る)", "drop by, draw near (寄る)"),
                    .kanji("途", "to", "と", "on the way, path (途中)"),
                    .kanji("踏", "fu(mu)", "ふ(む)", "step on (踏む)"),
                    .kanji("浮", "u(ku)", "う(く)", "float (浮く)"),
                    .kanji("崩", "kuzu(reru)", "くず(れる)", "crumble (崩れる)"),
                    .kanji("倒", "tao(reru)", "たお(れる)", "fall over (倒れる)"),
                    .kanji("昇", "nobo(ru)", "のぼ(る)", "rise, ascend (昇る)"),
                    .kanji("傾", "katamu(ku)", "かたむ(く)", "lean, tilt (傾く)"),
                    .kanji("衝", "shou", "しょう", "collide, impact (衝突)"),
                    .kanji("駆", "ka(keru)", "か(ける)", "gallop, rush (駆ける)"),
                    .kanji("揺", "yu(reru)", "ゆ(れる)", "sway, rock (揺れる)"),
                    .kanji("滞", "tai", "たい", "stagnate, stay over (滞在)"),
                    .kanji("陥", "kan", "かん", "fall into, defect (欠陥)"),
                    .kanji("滑", "sube(ru)", "すべ(る)", "slide, slippery (滑る)"),
                    .kanji("巡", "megu(ru)", "めぐ(る)", "go around, patrol (巡る)"),
                    .kanji("沈", "shizu(mu)", "しず(む)", "sink (沈む)"),
                    .kanji("漏", "mo(reru)", "も(れる)", "leak (漏れる)"),
                    .kanji("潜", "mogu(ru)", "もぐ(る)", "dive, lurk (潜る)"),
                    .kanji("没", "botsu", "ぼつ", "sink into, vanish (没頭)"),
                    .kanji("往", "ou", "おう", "outward trip (往復)"),
                    .kanji("屈", "kutsu", "くつ", "bend down, give in (退屈)"),
                    .kanji("浸", "hita(su)", "ひた(す)", "soak, immerse (浸す)"),
                    .kanji("墜", "tsui", "つい", "crash, fall (墜落)"),
                    .kanji("漂", "tadayo(u)", "ただよ(う)", "drift (漂う)"),
                    .kanji("浪", "rou", "ろう", "wander, waves (浪人)"),
                    .kanji("逸", "itsu", "いつ", "deviate, excel (逸脱)"),
                    .kanji("遭", "a(u)", "あ(う)", "run into (遭遇)"),
                    .kanji("伏", "fu(seru)", "ふ(せる)", "lie face down (伏せる)"),
                    .kanji("赴", "fu", "ふ", "proceed, head for (赴任)"),
                    .kanji("搬", "han", "はん", "convey, haul (運搬)"),
                    .kanji("旋", "sen", "せん", "revolve, melody (旋律)"),
                    .kanji("奔", "hon", "ほん", "dash about (奔走)"),
                    .kanji("遷", "sen", "せん", "transition (変遷)"),
                    .kanji("漕", "ko(gu)", "こ(ぐ)", "paddle, pedal (漕ぐ)"),
                    .kanji("溢", "afu(reru)", "あふ(れる)", "overflow (溢れる)"),
                    .kanji("溺", "obo(reru)", "おぼ(れる)", "drown, dote (溺れる)"),
                    .kanji("辿", "tado(ru)", "たど(る)", "follow (a path), trace"),
                    .kanji("迂", "u", "う", "detour, roundabout (迂回)"),
                    .kanji("廻", "mawa(ru)", "まわ(る)", "rotate, turn round (廻転)")
                ]
            ),
            MojiSectionDefinition(
                key: "sports",
                title: "Sports & games",
                subtitle: "Matches, sumo, board games and pastimes",
                columns: 4,
                cells: [
                    .kanji("競", "kyou", "きょう", "compete (競争)"),
                    .kanji("塁", "rui", "るい", "baseball base, fort (本塁打)"),
                    .kanji("盤", "ban", "ばん", "game board, base (将棋盤)"),
                    .kanji("躍", "yaku", "やく", "leap, be active (活躍)"),
                    .kanji("挑", "chou", "ちょう", "challenge (挑戦)"),
                    .kanji("綱", "tsuna", "つな", "hawser, sumo rope (横綱)"),
                    .kanji("趣", "shu", "しゅ", "hobby, taste (趣味)"),
                    .kanji("覇", "ha", "は", "supremacy, title (制覇)"),
                    .kanji("撲", "boku", "ぼく", "strike, sumo (相撲)"),
                    .kanji("踊", "odo(ru)", "おど(る)", "dance"),
                    .kanji("棋", "ki", "き", "shogi (将棋)"),
                    .kanji("駒", "koma", "こま", "game piece, pony (駒)"),
                    .kanji("俵", "tawara", "たわら", "straw bale (土俵)"),
                    .kanji("釣", "tsu(ru)", "つ(る)", "fish, change (お釣り)"),
                    .kanji("碁", "go", "ご", "board game go (囲碁)"),
                    .kanji("跳", "to(bu)", "と(ぶ)", "jump, hop (跳ぶ)"),
                    .kanji("鍛", "kita(eru)", "きた(える)", "train, forge (鍛える)"),
                    .kanji("娯", "go", "ご", "amusement (娯楽)"),
                    .kanji("戯", "gi", "ぎ", "frolic, drama (戯曲)"),
                    .kanji("賭", "ka(keru)", "か(ける)", "bet, gamble (賭ける)"),
                    .kanji("凧", "tako", "たこ", "kite (toy) (凧揚げ)"),
                    .kanji("玩", "gan", "がん", "toy, pet (玩具)"),
                    .kanji("稽", "kei", "けい", "practice, funny (稽古)"),
                    .kanji("蹴", "ke(ru)", "け(る)", "kick (蹴る)"),
                    .kanji("采", "sai", "さい", "dice, command (采配)")
                ]
            )
        ],
        lessonOrder: "出行発入動通来進交運流過止送転訪着乗追落渡移帰突歩登飛降超競迎走塁寄途踏避迫浮崩旅倒昇盤戻越躍傾届衝挑到駆綱揺滞趣陥覇泳滑巡沈撲漏踊棋潜没往屈浸駒墜俵漂浪逸釣遭伏碁赴搬跳鍛旋娯戯奔遷賭凧玩漕稽蹴溢采溺辿迂廻"
    )
}
