import Foundation

extension MojiAlphabetData {
    static let kanjiHistory = MojiPageDefinition(
        page: .kanji(.history),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "past",
                title: "The past",
                subtitle: "Eras, rulers, ruins and far lands",
                columns: 4,
                cells: [
                    .kanji("独", "doku", "どく", "alone, Germany"),
                    .kanji("州", "shuu", "しゅう", "state, province"),
                    .kanji("欧", "ou", "おう", "Europe"),
                    .kanji("韓", "kan", "かん", "Korea"),
                    .kanji("史", "shi", "し", "history"),
                    .kanji("士", "shi", "し", "samurai, gentleman"),
                    .kanji("歴", "reki", "れき", "career, past"),
                    .kanji("将", "shou", "しょう", "commander, future"),
                    .kanji("遺", "i", "い", "bequeath, heritage (遺産)"),
                    .kanji("王", "ou", "おう", "king"),
                    .kanji("皇", "kou", "こう", "emperor (imperial)"),
                    .kanji("洋", "you", "よう", "ocean, Western"),
                    .kanji("紀", "ki", "き", "chronicle, era"),
                    .kanji("刻", "koku", "こく", "engrave, moment"),
                    .kanji("跡", "ato", "あと", "footprints, ruins (足跡)"),
                    .kanji("典", "ten", "てん", "classic, code"),
                    .kanji("華", "ka", "か", "splendor, China"),
                    .kanji("帝", "tei", "てい", "sovereign"),
                    .kanji("盆", "bon", "ぼん", "tray, Obon festival (お盆)"),
                    .kanji("碑", "hi", "ひ", "monument, tombstone (記念碑)"),
                    .kanji("墳", "fun", "ふん", "burial mound (古墳)"),
                    .kanji("闇", "yami", "やみ", "darkness"),
                    .kanji("蹟", "seki", "せき", "historic remains (史蹟)")
                ]
            ),
            MojiSectionDefinition(
                key: "war",
                title: "War & weapons",
                subtitle: "Battles, arms and soldiers",
                columns: 4,
                cells: [
                    .kanji("撃", "u(tsu)", "う(つ)", "fire (a gun)"),
                    .kanji("攻", "se(meru)", "せ(める)", "attack"),
                    .kanji("抗", "kou", "こう", "oppose, defy (抗議)"),
                    .kanji("爆", "baku", "ばく", "explode"),
                    .kanji("狙", "nera(u)", "ねら(う)", "aim at (狙う)"),
                    .kanji("闘", "tou", "とう", "fight, struggle (闘う)"),
                    .kanji("陣", "jin", "じん", "camp, battle line (陣)"),
                    .kanji("銃", "juu", "じゅう", "gun (銃)"),
                    .kanji("侵", "shin", "しん", "invade (侵入)"),
                    .kanji("威", "i", "い", "might, threat (威力)"),
                    .kanji("襲", "oso(u)", "おそ(う)", "assault, raid (襲う)"),
                    .kanji("犠", "gi", "ぎ", "sacrifice (犠牲)"),
                    .kanji("敵", "teki", "てき", "enemy (敵)"),
                    .kanji("砲", "hou", "ほう", "cannon (大砲)"),
                    .kanji("牲", "sei", "せい", "offering (犠牲)"),
                    .kanji("矢", "ya", "や", "arrow (矢印)"),
                    .kanji("剣", "ken", "けん", "sword (剣道)"),
                    .kanji("艦", "kan", "かん", "warship (軍艦)"),
                    .kanji("艇", "tei", "てい", "small boat (競艇)"),
                    .kanji("盾", "tate", "たて", "shield (矛盾)"),
                    .kanji("矛", "hoko", "ほこ", "halberd (矛盾)"),
                    .kanji("征", "sei", "せい", "conquer (征服)"),
                    .kanji("虜", "ryo", "りょ", "captive (捕虜)"),
                    .kanji("騎", "ki", "き", "horseman, knight (騎士)"),
                    .kanji("刃", "ha", "は", "blade, edge (刃物)"),
                    .kanji("刀", "katana", "かたな", "katana (日本刀)"),
                    .kanji("弓", "yumi", "ゆみ", "bow (archery)"),
                    .kanji("伐", "batsu", "ばつ", "fell, subjugate (伐採)"),
                    .kanji("屯", "ton", "とん", "garrison (駐屯)"),
                    .kanji("曹", "sou", "そう", "sergeant, legal profession (法曹)"),
                    .kanji("哨", "shou", "しょう", "sentry (歩哨)"),
                    .kanji("尉", "i", "い", "officer rank (大尉)"),
                    .kanji("帥", "sui", "すい", "marshal (元帥)"),
                    .kanji("兜", "kabuto", "かぶと", "helmet (兜)"),
                    .kanji("斬", "zan", "ざん", "slash, novel (斬新)"),
                    .kanji("嚇", "kaku", "かく", "intimidate (威嚇)"),
                    .kanji("槍", "yari", "やり", "spear"),
                    .kanji("壕", "gou", "ごう", "trench, dugout (防空壕)"),
                    .kanji("凱", "gai", "がい", "triumph (凱旋)"),
                    .kanji("砦", "toride", "とりで", "fort, stronghold"),
                    .kanji("勃", "botsu", "ぼつ", "break out (勃発)"),
                    .kanji("舷", "gen", "げん", "ship's side (右舷)"),
                    .kanji("傭", "you", "よう", "hire, mercenary (傭兵)"),
                    .kanji("鋒", "hou", "ほう", "spearhead (先鋒)"),
                    .kanji("薙", "na(gu)", "な(ぐ)", "mow down (薙刀)"),
                    .kanji("鞘", "saya", "さや", "sheath, margin (鞘)"),
                    .kanji("鎧", "yoroi", "よろい", "armor (鎧)")
                ]
            ),
            MojiSectionDefinition(
                key: "court",
                title: "Old Japan",
                subtitle: "Emperors, lords, samurai and the court",
                columns: 4,
                cells: [
                    .kanji("昭", "shou", "しょう", "bright, Showa era (昭和)"),
                    .kanji("幕", "maku", "まく", "curtain, shogunate (幕府)"),
                    .kanji("殿", "den", "でん", "palace, lord (宮殿)"),
                    .kanji("陛", "hei", "へい", "Majesty (陛下)"),
                    .kanji("冠", "kanmuri", "かんむり", "crown (王冠)"),
                    .kanji("勲", "kun", "くん", "medal of merit (勲章)"),
                    .kanji("姫", "hime", "ひめ", "princess (姫)"),
                    .kanji("后", "kou", "こう", "empress (皇后)"),
                    .kanji("陵", "ryou", "りょう", "imperial tomb, hill (御陵)"),
                    .kanji("妃", "hi", "ひ", "queen consort (王妃)"),
                    .kanji("藩", "han", "はん", "feudal domain (藩)"),
                    .kanji("侍", "samurai", "さむらい", "serve, samurai (侍)"),
                    .kanji("倭", "wa", "わ", "ancient Japan (倭)"),
                    .kanji("禄", "roku", "ろく", "stipend, dignity (貫禄)"),
                    .kanji("卿", "kyou", "きょう", "lord, minister (卿)"),
                    .kanji("勅", "choku", "ちょく", "imperial order (勅令)"),
                    .kanji("楼", "rou", "ろう", "pavilion, tall building (楼閣)"),
                    .kanji("詔", "shou", "しょう", "imperial edict (詔書)"),
                    .kanji("嗣", "shi", "し", "heir (嗣子)"),
                    .kanji("夷", "i", "い", "eastern barbarian (征夷)"),
                    .kanji("侯", "kou", "こう", "marquis (侯爵)"),
                    .kanji("朕", "chin", "ちん", "imperial We (朕)"),
                    .kanji("謁", "etsu", "えつ", "audience (謁見)"),
                    .kanji("爵", "shaku", "しゃく", "peerage (爵位)"),
                    .kanji("璽", "ji", "じ", "imperial seal (御璽)"),
                    .kanji("閤", "kou", "こう", "side gate, regent (太閤)")
                ]
            ),
            MojiSectionDefinition(
                key: "arts",
                title: "Old arts",
                subtitle: "Poems, music and calligraphy",
                columns: 4,
                cells: [
                    .kanji("筆", "fude", "ふで", "writing brush"),
                    .kanji("詩", "shi", "し", "poem"),
                    .kanji("謡", "you", "よう", "Noh chant, song (民謡)"),
                    .kanji("琴", "koto", "こと", "koto (harp)"),
                    .kanji("墨", "sumi", "すみ", "ink (sumi)"),
                    .kanji("鼓", "ko", "こ", "drum (太鼓)"),
                    .kanji("笛", "fue", "ふえ", "flute, whistle"),
                    .kanji("琵", "bi", "び", "biwa lute (琵琶)"),
                    .kanji("琶", "wa", "わ", "lute, Lake Biwa (琵琶湖)"),
                    .kanji("詠", "ei", "えい", "recite (poetry), compose"),
                    .kanji("唄", "uta", "うた", "ballad, folk song (小唄)"),
                    .kanji("韻", "in", "いん", "rhyme, tone (余韻)"),
                    .kanji("伎", "ki", "き", "kabuki, skill (歌舞伎)"),
                    .kanji("笙", "shou", "しょう", "sho mouth organ"),
                    .kanji("絃", "gen", "げん", "strings (music) (管絃)"),
                    .kanji("楷", "kai", "かい", "block script (楷書)"),
                    .kanji("諧", "kai", "かい", "harmony, humor (俳諧)")
                ]
            )
        ],
        lessonOrder: "独州欧韓撃史士攻歴将遺抗王昭皇爆狙闘洋紀陣幕刻跡銃侵典華威襲筆犠詩殿敵砲牲帝矢剣艦陛艇盾冠勲矛姫征謡后琴墨盆虜騎陵妃刃碑刀鼓弓伐墳藩笛侍琵琶闇屯曹哨詠尉帥兜唄倭禄斬卿嚇韻勅楼詔槍壕凱砦嗣夷侯伎朕謁爵笙絃勃舷楷諧璽傭閤鋒薙鞘蹟鎧"
    )
}
