import Foundation

extension MojiAlphabetData {
    static let kanjiOldForms = MojiPageDefinition(
        page: .kanji(.oldForms),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "known",
                title: "Kanji you know",
                subtitle: "Traditional shapes of kanji you know",
                columns: 4,
                cells: [
                    .kanji("國", "kuni", "くに", "old form of 国"),
                    .kanji("實", "jitsu", "じつ", "old form of 実"),
                    .kanji("圓", "en", "えん", "old form of 円"),
                    .kanji("戰", "sen", "せん", "old form of 戦"),
                    .kanji("來", "ku(ru)", "く(る)", "old form of 来"),
                    .kanji("氣", "ki", "き", "old form of 気"),
                    .kanji("埜", "no", "の", "old form of 野"),
                    .kanji("縣", "ken", "けん", "old form of 県"),
                    .kanji("賣", "u(ru)", "う(る)", "old form of 売"),
                    .kanji("團", "dan", "だん", "old form of 団"),
                    .kanji("增", "fu(eru)", "ふ(える)", "old form of 増"),
                    .kanji("價", "ka", "か", "old form of 価"),
                    .kanji("廣", "hiro(i)", "ひろ(い)", "old form of 広"),
                    .kanji("應", "ou", "おう", "old form of 応"),
                    .kanji("爭", "araso(u)", "あらそ(う)", "old form of 争"),
                    .kanji("眞", "shin", "しん", "old form of 真"),
                    .kanji("檢", "ken", "けん", "old form of 検"),
                    .kanji("狀", "jou", "じょう", "old form of 状"),
                    .kanji("與", "ata(eru)", "あた(える)", "old form of 与"),
                    .kanji("轉", "ten", "てん", "old form of 転"),
                    .kanji("收", "shuu", "しゅう", "old form of 収"),
                    .kanji("條", "jou", "じょう", "old form of 条"),
                    .kanji("樂", "tano(shii)", "たの(しい)", "old form of 楽"),
                    .kanji("萬", "man", "まん", "old form of 万"),
                    .kanji("乘", "no(ru)", "の(る)", "old form of 乗"),
                    .kanji("衞", "ei", "えい", "old form of 衛"),
                    .kanji("驗", "ken", "けん", "old form of 験"),
                    .kanji("傳", "tsuta(eru)", "つた(える)", "old form of 伝"),
                    .kanji("每", "mai", "まい", "old form of 毎"),
                    .kanji("藏", "kura", "くら", "old form of 蔵"),
                    .kanji("擊", "u(tsu)", "う(つ)", "old form of 撃"),
                    .kanji("橫", "yoko", "よこ", "old form of 横"),
                    .kanji("樣", "sama", "さま", "old form of 様"),
                    .kanji("涉", "shou", "しょう", "old form of 渉"),
                    .kanji("專", "sen", "せん", "old form of 専"),
                    .kanji("惡", "waru(i)", "わる(い)", "old form of 悪"),
                    .kanji("錄", "roku", "ろく", "old form of 録"),
                    .kanji("步", "aru(ku)", "ある(く)", "old form of 歩"),
                    .kanji("郞", "rou", "ろう", "old form of 郎"),
                    .kanji("黑", "kuro", "くろ", "old form of 黒"),
                    .kanji("單", "tan", "たん", "old form of 単"),
                    .kanji("搜", "saga(su)", "さが(す)", "old form of 捜"),
                    .kanji("從", "shitaga(u)", "したが(う)", "old form of 従"),
                    .kanji("歷", "reki", "れき", "old form of 歴"),
                    .kanji("將", "shou", "しょう", "old form of 将"),
                    .kanji("嚴", "kibi(shii)", "きび(しい)", "old form of 厳"),
                    .kanji("壘", "rui", "るい", "old form of 塁"),
                    .kanji("裝", "sou", "そう", "old form of 装"),
                    .kanji("兒", "ji", "じ", "old form of 児"),
                    .kanji("藥", "kusuri", "くすり", "old form of 薬"),
                    .kanji("險", "ken", "けん", "old form of 険"),
                    .kanji("賴", "tano(mu)", "たの(む)", "old form of 頼"),
                    .kanji("藝", "gei", "げい", "old form of 芸"),
                    .kanji("拔", "nu(ku)", "ぬ(く)", "old form of 抜"),
                    .kanji("壞", "kowa(su)", "こわ(す)", "old form of 壊"),
                    .kanji("帶", "tai", "たい", "old form of 帯"),
                    .kanji("靜", "shizu(ka)", "しず(か)", "old form of 静"),
                    .kanji("聽", "ki(ku)", "き(く)", "old form of 聴"),
                    .kanji("廳", "chou", "ちょう", "old form of 庁"),
                    .kanji("拂", "hara(u)", "はら(う)", "old form of 払"),
                    .kanji("佛", "hotoke", "ほとけ", "old form of 仏"),
                    .kanji("爲", "i", "い", "old form of 為"),
                    .kanji("溫", "atata(kai)", "あたた(かい)", "old form of 温"),
                    .kanji("雜", "zatsu", "ざつ", "old form of 雑"),
                    .kanji("徵", "chou", "ちょう", "old form of 徴"),
                    .kanji("彈", "hi(ku)", "ひ(く)", "old form of 弾"),
                    .kanji("祕", "hi", "ひ", "old form of 秘"),
                    .kanji("揭", "kaka(geru)", "かか(げる)", "old form of 掲"),
                    .kanji("榮", "ei", "えい", "old form of 栄"),
                    .kanji("惠", "megu(mu)", "めぐ(む)", "old form of 恵"),
                    .kanji("卷", "ma(ku)", "ま(く)", "old form of 巻"),
                    .kanji("緖", "sho", "しょ", "old form of 緒"),
                    .kanji("燒", "ya(ku)", "や(く)", "old form of 焼"),
                    .kanji("讓", "yuzu(ru)", "ゆず(る)", "old form of 譲"),
                    .kanji("臟", "zou", "ぞう", "old form of 臓"),
                    .kanji("愼", "shin", "しん", "old form of 慎"),
                    .kanji("澁", "shibu(i)", "しぶ(い)", "old form of 渋"),
                    .kanji("奧", "oku", "おく", "old form of 奥"),
                    .kanji("駈", "ka(keru)", "か(ける)", "variant of 駆"),
                    .kanji("寢", "ne(ru)", "ね(る)", "old form of 寝"),
                    .kanji("稻", "ine", "いね", "old form of 稲"),
                    .kanji("盜", "nusu(mu)", "ぬす(む)", "old form of 盗"),
                    .kanji("騷", "sawa(gu)", "さわ(ぐ)", "old form of 騒"),
                    .kanji("搖", "yu(reru)", "ゆ(れる)", "old form of 揺"),
                    .kanji("德", "toku", "とく", "old form of 徳"),
                    .kanji("滯", "tai", "たい", "old form of 滞"),
                    .kanji("晝", "hiru", "ひる", "old form of 昼"),
                    .kanji("瀨", "se", "せ", "old form of 瀬"),
                    .kanji("陷", "kan", "かん", "old form of 陥"),
                    .kanji("卽", "soku", "そく", "old form of 即"),
                    .kanji("僞", "nise", "にせ", "old form of 偽"),
                    .kanji("綠", "midori", "みどり", "old form of 緑"),
                    .kanji("禮", "rei", "れい", "old form of 礼"),
                    .kanji("龍", "ryuu", "りゅう", "old form of 竜"),
                    .kanji("齊", "sei", "せい", "old form of 斉"),
                    .kanji("圈", "ken", "けん", "old form of 圏"),
                    .kanji("盡", "tsu(kusu)", "つ(くす)", "old form of 尽"),
                    .kanji("盃", "hai", "はい", "variant of 杯"),
                    .kanji("櫻", "sakura", "さくら", "old form of 桜"),
                    .kanji("黃", "ki", "き", "old form of 黄"),
                    .kanji("壽", "ju", "じゅ", "old form of 寿"),
                    .kanji("縱", "tate", "たて", "old form of 縦"),
                    .kanji("緣", "en", "えん", "old form of 縁"),
                    .kanji("劍", "ken", "けん", "old form of 剣"),
                    .kanji("恆", "kou", "こう", "old form of 恒"),
                    .kanji("曾", "sou", "そう", "old form of 曽"),
                    .kanji("默", "dama(ru)", "だま(る)", "old form of 黙"),
                    .kanji("狹", "sema(i)", "せま(い)", "old form of 狭"),
                    .kanji("寬", "kan", "かん", "old form of 寛"),
                    .kanji("淚", "namida", "なみだ", "old form of 涙"),
                    .kanji("淨", "jou", "じょう", "old form of 浄"),
                    .kanji("晚", "ban", "ばん", "old form of 晩"),
                    .kanji("拜", "oga(mu)", "おが(む)", "old form of 拝"),
                    .kanji("奬", "shou", "しょう", "old form of 奨"),
                    .kanji("剩", "jou", "じょう", "old form of 剰"),
                    .kanji("纖", "sen", "せん", "old form of 繊"),
                    .kanji("虛", "kyo", "きょ", "old form of 虚"),
                    .kanji("飜", "hon", "ほん", "old form of 翻"),
                    .kanji("髮", "kami", "かみ", "old form of 髪"),
                    .kanji("瀧", "taki", "たき", "old form of 滝"),
                    .kanji("莊", "sou", "そう", "old form of 荘"),
                    .kanji("懷", "natsu(kashii)", "なつ(かしい)", "old form of 懐"),
                    .kanji("亞", "a", "あ", "old form of 亜"),
                    .kanji("覽", "ran", "らん", "old form of 覧"),
                    .kanji("勳", "kun", "くん", "old form of 勲"),
                    .kanji("濕", "shime(ru)", "しめ(る)", "old form of 湿"),
                    .kanji("顯", "ken", "けん", "old form of 顕"),
                    .kanji("碎", "kuda(ku)", "くだ(く)", "old form of 砕"),
                    .kanji("謠", "you", "よう", "old form of 謡"),
                    .kanji("巢", "su", "す", "old form of 巣"),
                    .kanji("燈", "tou", "とう", "old form of 灯"),
                    .kanji("鎭", "chin", "ちん", "old form of 鎮"),
                    .kanji("醉", "yo(u)", "よ(う)", "old form of 酔"),
                    .kanji("穗", "ho", "ほ", "old form of 穂"),
                    .kanji("壯", "sou", "そう", "old form of 壮"),
                    .kanji("疊", "tatami", "たたみ", "old form of 畳"),
                    .kanji("彌", "ya", "や", "old form of 弥"),
                    .kanji("獸", "kemono", "けもの", "old form of 獣"),
                    .kanji("曆", "koyomi", "こよみ", "old form of 暦"),
                    .kanji("粹", "sui", "すい", "old form of 粋"),
                    .kanji("攝", "setsu", "せつ", "old form of 摂"),
                    .kanji("凉", "suzu(shii)", "すず(しい)", "old form of 涼"),
                    .kanji("峽", "kyou", "きょう", "old form of 峡"),
                    .kanji("釀", "jou", "じょう", "old form of 醸"),
                    .kanji("薰", "kao(ru)", "かお(る)", "old form of 薫"),
                    .kanji("戲", "gi", "ぎ", "old form of 戯"),
                    .kanji("鷄", "niwatori", "にわとり", "old form of 鶏"),
                    .kanji("禪", "zen", "ぜん", "old form of 禅"),
                    .kanji("曉", "akatsuki", "あかつき", "old form of 暁"),
                    .kanji("渴", "kawa(ku)", "かわ(く)", "old form of 渇"),
                    .kanji("敍", "jo", "じょ", "old form of 叙"),
                    .kanji("鑄", "chuu", "ちゅう", "old form of 鋳"),
                    .kanji("孃", "jou", "じょう", "old form of 嬢"),
                    .kanji("鍊", "ren", "れん", "old form of 錬"),
                    .kanji("儉", "ken", "けん", "old form of 倹"),
                    .kanji("瘦", "ya(seru)", "や(せる)", "old form of 痩")
                ]
            ),
            MojiSectionDefinition(
                key: "names",
                title: "In names",
                subtitle: "Old shapes and variants seen in names",
                columns: 4,
                cells: [
                    .kanji("嶋", "shima", "しま", "variant of 島"),
                    .kanji("薗", "en", "えん", "variant of 園"),
                    .kanji("冨", "tomi", "とみ", "variant of 富"),
                    .kanji("晄", "kou", "こう", "variant of 晃"),
                    .kanji("亙", "wata(ru)", "わた(る)", "old form of 亘"),
                    .kanji("峯", "mine", "みね", "variant of 峰"),
                    .kanji("槇", "maki", "まき", "old form of 槙"),
                    .kanji("巖", "iwao", "いわお", "old form of 巌"),
                    .kanji("檜", "hinoki", "ひのき", "old form of 桧"),
                    .kanji("祿", "roku", "ろく", "old form of 禄"),
                    .kanji("堯", "gyou", "ぎょう", "old form of 尭"),
                    .kanji("萠", "mo(eru)", "も(える)", "variant of 萌"),
                    .kanji("遙", "haru(ka)", "はる(か)", "old form of 遥"),
                    .kanji("穰", "jou", "じょう", "old form of 穣"),
                    .kanji("禰", "ne", "ね", "old form of 祢"),
                    .kanji("禱", "tou", "とう", "old form of 祷"),
                    .kanji("凜", "rin", "りん", "old form of 凛")
                ]
            )
        ],
        lessonOrder: "國實圓戰來氣埜縣賣團增嶋價廣應爭眞檢狀與轉收條樂萬乘衞驗傳每藏擊橫樣涉專惡錄步郞黑單搜從薗歷將嚴冨壘裝兒藥險賴藝拔壞帶靜聽廳拂佛爲溫雜徵彈祕揭榮惠卷緖燒讓臟愼澁奧駈寢稻盜騷搖德滯晝瀨陷卽僞綠禮龍齊圈盡盃櫻黃壽縱緣劍恆曾默狹寬淚淨晚拜奬剩纖虛飜髮瀧莊懷亞覽勳濕顯碎謠巢燈鎭醉穗壯疊晄彌獸亙曆粹攝凉峽峯釀薰戲鷄禪曉渴敍槇巖鑄檜孃祿堯鍊萠遙穰儉瘦禰禱凜"
    )
}
