import Foundation

extension MojiAlphabetData {
    static let kanjiNature = MojiPageDefinition(
        page: .kanji(.nature),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "weather",
                title: "Weather & the world",
                subtitle: "Sun, rain, mountains and seas",
                columns: 4,
                cells: [
                    .kanji("地", "chi", "ち", "ground, earth"),
                    .kanji("田", "ta", "た", "rice field"),
                    .kanji("野", "no", "の", "field, plain"),
                    .kanji("山", "yama", "やま", "mountain"),
                    .kanji("世", "se", "せ", "world, generation"),
                    .kanji("界", "kai", "かい", "realm, boundary"),
                    .kanji("川", "kawa", "かわ", "river"),
                    .kanji("海", "umi", "うみ", "sea"),
                    .kanji("水", "mizu", "みず", "water"),
                    .kanji("島", "shima", "しま", "island"),
                    .kanji("空", "sora", "そら", "sky"),
                    .kanji("土", "tsuchi", "つち", "soil"),
                    .kanji("石", "ishi", "いし", "stone"),
                    .kanji("天", "ten", "てん", "heaven"),
                    .kanji("光", "hikari", "ひかり", "light"),
                    .kanji("風", "kaze", "かぜ", "wind"),
                    .kanji("火", "hi", "ひ", "fire"),
                    .kanji("池", "ike", "いけ", "pond"),
                    .kanji("温", "atata(kai)", "あたた(かい)", "warm"),
                    .kanji("星", "hoshi", "ほし", "star"),
                    .kanji("雨", "ame", "あめ", "rain"),
                    .kanji("晴", "ha(re)", "は(れ)", "sunny"),
                    .kanji("雪", "yuki", "ゆき", "snow"),
                    .kanji("雲", "kumo", "くも", "cloud"),
                    .kanji("暑", "atsu(i)", "あつ(い)", "hot (weather)"),
                    .kanji("寒", "samu(i)", "さむ(い)", "cold (weather)")
                ]
            ),
            MojiSectionDefinition(
                key: "land",
                title: "Land, sea & sky",
                subtitle: "Mountains, coasts and weather",
                columns: 4,
                cells: [
                    .kanji("景", "kei", "けい", "scenery"),
                    .kanji("谷", "tani", "たに", "valley"),
                    .kanji("湾", "wan", "わん", "bay"),
                    .kanji("岸", "kishi", "きし", "shore"),
                    .kanji("河", "kawa", "かわ", "big river (河川)"),
                    .kanji("陸", "riku", "りく", "land"),
                    .kanji("岩", "iwa", "いわ", "rock"),
                    .kanji("坂", "saka", "さか", "slope"),
                    .kanji("露", "tsuyu", "つゆ", "dew, expose (露出)"),
                    .kanji("沖", "oki", "おき", "offshore, open sea (沖縄)"),
                    .kanji("津", "tsu", "つ", "haven, tsunami (津波)"),
                    .kanji("泉", "izumi", "いずみ", "fountain"),
                    .kanji("吹", "fu(ku)", "ふ(く)", "blow (吹く)"),
                    .kanji("砂", "suna", "すな", "sand"),
                    .kanji("瀬", "se", "せ", "shallows, rapids (瀬戸)"),
                    .kanji("潮", "shio", "しお", "tide (潮)"),
                    .kanji("噴", "fun", "ふん", "erupt, spout (噴火)"),
                    .kanji("凍", "koo(ru)", "こお(る)", "freeze (凍る)"),
                    .kanji("煙", "kemuri", "けむり", "smoke"),
                    .kanji("岳", "gaku", "がく", "high mountain (山岳)"),
                    .kanji("湖", "mizuumi", "みずうみ", "lake"),
                    .kanji("穴", "ana", "あな", "hole (穴)"),
                    .kanji("陰", "kage", "かげ", "shade, yin (日陰)"),
                    .kanji("丘", "oka", "おか", "hill"),
                    .kanji("壌", "jou", "じょう", "soil (土壌)"),
                    .kanji("磯", "iso", "いそ", "rocky shore (磯)"),
                    .kanji("氷", "koori", "こおり", "ice"),
                    .kanji("沼", "numa", "ぬま", "swamp, bog (沼)"),
                    .kanji("滝", "taki", "たき", "waterfall"),
                    .kanji("雷", "kaminari", "かみなり", "thunder"),
                    .kanji("湿", "shime(ru)", "しめ(る)", "damp, humid (湿気)"),
                    .kanji("泥", "doro", "どろ", "mud (泥棒)"),
                    .kanji("霞", "kasumi", "かすみ", "haze, mist (霞)"),
                    .kanji("漠", "baku", "ばく", "desert, vague (砂漠)"),
                    .kanji("洞", "dou", "どう", "cave, hollow (洞窟)"),
                    .kanji("堤", "tsutsumi", "つつみ", "embankment (堤防)"),
                    .kanji("溝", "mizo", "みぞ", "ditch, gap (溝)"),
                    .kanji("霧", "kiri", "きり", "fog, mist (霧)"),
                    .kanji("洪", "kou", "こう", "flood (洪水)"),
                    .kanji("渦", "uzu", "うず", "whirlpool, swirl (渦)"),
                    .kanji("峡", "kyou", "きょう", "gorge, strait (海峡)"),
                    .kanji("峰", "mine", "みね", "peak, summit (峰)"),
                    .kanji("曇", "kumo(ri)", "くも(り)", "cloudy"),
                    .kanji("嵐", "arashi", "あらし", "storm"),
                    .kanji("峠", "touge", "とうげ", "mountain pass (峠)"),
                    .kanji("岬", "misaki", "みさき", "cape (岬)"),
                    .kanji("礁", "shou", "しょう", "reef (岩礁)"),
                    .kanji("滴", "teki", "てき", "drip, drop (水滴)"),
                    .kanji("坑", "kou", "こう", "pit, mine shaft (炭坑)"),
                    .kanji("畔", "han", "はん", "lakeside, levee (湖畔)"),
                    .kanji("渓", "kei", "けい", "ravine stream (渓谷)"),
                    .kanji("湧", "wa(ku)", "わ(く)", "gush, spring up (湧く)"),
                    .kanji("虹", "niji", "にじ", "rainbow"),
                    .kanji("霜", "shimo", "しも", "frost"),
                    .kanji("雫", "shizuku", "しずく", "droplet (雫)"),
                    .kanji("彗", "sui", "すい", "comet (彗星)"),
                    .kanji("麓", "fumoto", "ふもと", "foot of a mountain (麓)"),
                    .kanji("濫", "ran", "らん", "excessive, abuse (濫用)"),
                    .kanji("氾", "han", "はん", "inundate (氾濫)"),
                    .kanji("崖", "gake", "がけ", "cliff (崖)"),
                    .kanji("窟", "kutsu", "くつ", "cavern (洞窟)")
                ]
            )
        ],
        lessonOrder: "地田野山世界川海水島空土石景谷天光湾岸風火河陸岩池温星坂露沖雨晴津泉雪吹砂瀬潮雲噴凍煙岳湖穴陰丘壌暑磯氷寒沼滝雷湿泥霞漠洞堤溝霧洪渦峡峰曇嵐峠岬礁滴坑畔渓湧虹霜雫彗麓濫氾崖窟"
    )
}
