import Foundation

extension MojiAlphabetData {
    static let kanjiFormal = MojiPageDefinition(
        page: .kanji(.formal),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "formal",
                title: "Formal Japanese",
                subtitle: "Linking words of news and documents",
                columns: 4,
                cells: [
                    .kanji("及", "oyo(bu)", "およ(ぶ)", "extend to, and (及び)"),
                    .kanji("諸", "sho", "しょ", "various (諸国)"),
                    .kanji("臨", "rin", "りん", "extra, face (臨時)"),
                    .kanji("略", "ryaku", "りゃく", "abbreviate, strategy (省略)"),
                    .kanji("為", "i", "い", "do, for the sake of (行為)"),
                    .kanji("致", "ita(su)", "いた(す)", "do (humble), match (一致)"),
                    .kanji("懸", "ken", "けん", "suspend, stake (懸命)"),
                    .kanji("至", "ita(ru)", "いた(る)", "arrive at, utmost (至急)"),
                    .kanji("是", "ze", "ぜ", "by all means, right (是非)"),
                    .kanji("御", "go", "ご", "honorable (御)"),
                    .kanji("斉", "sei", "せい", "all at once (一斉)"),
                    .kanji("唯", "yui", "ゆい", "only, sole (唯一)"),
                    .kanji("概", "gai", "がい", "summary, general (概要)"),
                    .kanji("須", "su", "す", "necessary (必須)"),
                    .kanji("随", "zui", "ずい", "follow, quite (随分)"),
                    .kanji("啓", "kei", "けい", "enlighten, Dear (拝啓)"),
                    .kanji("尚", "nao", "なお", "furthermore, still (尚)"),
                    .kanji("召", "me(su)", "め(す)", "summon, eat (honorific) (召し上がる)"),
                    .kanji("偶", "guu", "ぐう", "by chance, even number (偶然)"),
                    .kanji("該", "gai", "がい", "the said, applicable (該当)"),
                    .kanji("如", "jo", "じょ", "like, as if (突如)"),
                    .kanji("幾", "iku", "いく", "how many (幾つ)"),
                    .kanji("宜", "gi", "ぎ", "good, regards (宜しく)"),
                    .kanji("猶", "yuu", "ゆう", "grace period, still (猶予)"),
                    .kanji("羅", "ra", "ら", "spread out, gauze (網羅)"),
                    .kanji("遍", "hen", "へん", "everywhere, times (普遍)"),
                    .kanji("又", "mata", "また", "or, also (又は)"),
                    .kanji("沙", "sa", "さ", "affair, word (沙汰)"),
                    .kanji("逓", "tei", "てい", "relay, gradually (逓減)"),
                    .kanji("甚", "jin", "じん", "extremely (甚大)"),
                    .kanji("謹", "kin", "きん", "respectfully (謹んで)"),
                    .kanji("某", "bou", "ぼう", "a certain (某)"),
                    .kanji("衷", "chuu", "ちゅう", "inner heart, blend (折衷)"),
                    .kanji("逐", "chiku", "ちく", "one by one, expel (逐一)"),
                    .kanji("只", "tada", "ただ", "merely, free of charge (只)"),
                    .kanji("恣", "shi", "し", "arbitrary (恣意)"),
                    .kanji("或", "a(ru)", "あ(る)", "some, or (或いは)"),
                    .kanji("附", "fu", "ふ", "affiliated (附属)"),
                    .kanji("但", "tada(shi)", "ただ(し)", "however, provided (但し)"),
                    .kanji("且", "ka(tsu)", "か(つ)", "moreover, and (且つ)"),
                    .kanji("汰", "ta", "た", "weed out (淘汰)"),
                    .kanji("虞", "osore", "おそれ", "apprehension (虞)"),
                    .kanji("遵", "jun", "じゅん", "abide by (遵守)"),
                    .kanji("僅", "wazu(ka)", "わず(か)", "slight, mere (僅か)"),
                    .kanji("詮", "sen", "せん", "after all, inquire (所詮)"),
                    .kanji("頓", "ton", "とん", "tidy up, sudden (整頓)")
                ]
            ),
            MojiSectionDefinition(
                key: "classic",
                title: "Classical Japanese",
                subtitle: "Old grammar words of books and poems",
                columns: 4,
                cells: [
                    .kanji("之", "no", "の", "of (classical), this (之)"),
                    .kanji("也", "nari", "なり", "classical 'is' (也)"),
                    .kanji("吾", "ware", "われ", "literary I, my (吾輩)"),
                    .kanji("其", "sono", "その", "that, its (其の)"),
                    .kanji("乃", "no", "の", "namely, of (乃)"),
                    .kanji("此", "kono", "この", "this (此の)"),
                    .kanji("於", "o", "お", "at, in (於いて)"),
                    .kanji("已", "i", "い", "cease, already (已む)"),
                    .kanji("惟", "i", "い", "ponder (思惟)"),
                    .kanji("蒙", "mou", "もう", "ignorance, Mongolia (啓蒙)"),
                    .kanji("亦", "mata", "また", "also (亦)"),
                    .kanji("哉", "kana", "かな", "alas, how (哉)"),
                    .kanji("耶", "ya", "や", "interrogative, Jesus (耶蘇)"),
                    .kanji("爾", "ji", "じ", "since then, that (爾来)"),
                    .kanji("諄", "kudo(i)", "くど(い)", "tedious, repeated (諄い)"),
                    .kanji("云", "un", "うん", "say, and so on (云々)"),
                    .kanji("勿", "naka(re)", "なか(れ)", "do not, of course (勿論)"),
                    .kanji("尤", "motto(mo)", "もっと(も)", "reasonable, though (尤も)"),
                    .kanji("乎", "ko", "こ", "question particle (乎)"),
                    .kanji("汝", "nanji", "なんじ", "thou (汝)"),
                    .kanji("而", "ji", "じ", "and yet, moreover (而も)"),
                    .kanji("迄", "made", "まで", "until, up to (迄)"),
                    .kanji("沌", "ton", "とん", "chaos (混沌)"),
                    .kanji("些", "sa", "さ", "trifling (些細)"),
                    .kanji("忽", "kotsu", "こつ", "suddenly (忽ち)"),
                    .kanji("俄", "niwaka", "にわか", "abrupt, makeshift (俄か)"),
                    .kanji("恰", "ataka(mo)", "あたか(も)", "as if, appearance (恰好)"),
                    .kanji("殆", "hoton(do)", "ほとん(ど)", "almost (殆ど)"),
                    .kanji("俱", "ku", "く", "all together, club (俱楽部)"),
                    .kanji("套", "tou", "とう", "overcoat, cliché (外套)"),
                    .kanji("莫", "baku", "ばく", "vast, do not (莫大)"),
                    .kanji("堵", "to", "と", "relief, fence (安堵)"),
                    .kanji("徠", "rai", "らい", "come, invite (徠)"),
                    .kanji("悉", "shitsu", "しつ", "every last, entirely (悉く)"),
                    .kanji("畢", "hitsu", "ひつ", "end, after all (畢竟)"),
                    .kanji("斯", "shi", "し", "thus, such (斯く)"),
                    .kanji("疏", "so", "そ", "pass through, memorial (疏通)"),
                    .kanji("裡", "ri", "り", "inside, within (脳裡)"),
                    .kanji("牒", "chou", "ちょう", "official note (通牒)"),
                    .kanji("稟", "rin", "りん", "petition, nature (稟議)"),
                    .kanji("嘗", "na(meru)", "な(める)", "lick, formerly (嘗める)"),
                    .kanji("歎", "tan", "たん", "admire, sigh (感歎)"),
                    .kanji("頗", "sukobu(ru)", "すこぶ(る)", "exceedingly (頗る)"),
                    .kanji("諺", "kotowaza", "ことわざ", "proverb (諺)"),
                    .kanji("謂", "i", "い", "so-called, reason (所謂)"),
                    .kanji("寵", "chou", "ちょう", "favor, darling (寵児)"),
                    .kanji("顚", "ten", "てん", "tumble, whole story (顚末)")
                ]
            ),
            MojiSectionDefinition(
                key: "verbs",
                title: "Literary verbs",
                subtitle: "Soaring, drawing water, peeking and more",
                columns: 4,
                cells: [
                    .kanji("翔", "shou", "しょう", "glide, fly high (飛翔)"),
                    .kanji("漱", "sou", "そう", "gargle, rinse (漱石)"),
                    .kanji("逢", "a(u)", "あ(う)", "rendezvous, meet (逢う)"),
                    .kanji("讃", "san", "さん", "extol (讃美)"),
                    .kanji("湛", "tata(eru)", "たた(える)", "brim with, fill (湛える)"),
                    .kanji("挺", "tei", "てい", "gun counter, volunteer (挺身)"),
                    .kanji("綜", "sou", "そう", "synthesize (綜合)"),
                    .kanji("播", "ha", "は", "propagate, sow (伝播)"),
                    .kanji("寓", "guu", "ぐう", "allegory, lodging (寓話)"),
                    .kanji("坐", "za", "ざ", "sit (cross-legged) (坐禅)"),
                    .kanji("偲", "shino(bu)", "しの(ぶ)", "recall fondly"),
                    .kanji("蒔", "ma(ku)", "ま(く)", "sow (seeds), gold lacquer (蒔絵)"),
                    .kanji("凌", "shino(gu)", "しの(ぐ)", "tide over, surpass (凌ぐ)"),
                    .kanji("弛", "taru(mu)", "たる(む)", "slacken, sag (弛む)"),
                    .kanji("捺", "natsu", "なつ", "affix a seal, press (捺印)"),
                    .kanji("竣", "shun", "しゅん", "finish building (竣工)"),
                    .kanji("詢", "jun", "じゅん", "inquire of, consult (諮詢)"),
                    .kanji("頌", "shou", "しょう", "eulogy, ode (頌歌)"),
                    .kanji("曳", "ei", "えい", "tow, haul (曳航)"),
                    .kanji("庇", "kaba(u)", "かば(う)", "protect (someone), awning (庇う)"),
                    .kanji("汲", "ku(mu)", "く(む)", "draw water, ladle"),
                    .kanji("按", "an", "あん", "massage, ponder (按摩)"),
                    .kanji("臥", "ga", "が", "lie down, prone (臥す)"),
                    .kanji("挽", "ban", "ばん", "grind (coffee), recover (挽回)"),
                    .kanji("晒", "sara(su)", "さら(す)", "bleach, expose to air"),
                    .kanji("栖", "sei", "せい", "roost, abode"),
                    .kanji("穿", "uga(tsu)", "うが(つ)", "bore through, put on (穿く)"),
                    .kanji("耽", "fuke(ru)", "ふけ(る)", "indulge in, revel (耽る)"),
                    .kanji("訊", "jin", "じん", "interrogate (訊問)"),
                    .kanji("倦", "ken", "けん", "weariness, languor (倦怠)"),
                    .kanji("掠", "kasu(meru)", "かす(める)", "graze, plunder"),
                    .kanji("掬", "suku(u)", "すく(う)", "scoop up (with hands)"),
                    .kanji("牽", "ken", "けん", "lead (an animal), check (牽制)"),
                    .kanji("訣", "ketsu", "けつ", "parting, knack (秘訣)"),
                    .kanji("捲", "meku(ru)", "めく(る)", "turn (pages), roll up (捲る)"),
                    .kanji("棲", "su(mu)", "す(む)", "inhabit, live (棲息)"),
                    .kanji("焚", "ta(ku)", "た(く)", "kindle, burn (焚き火)"),
                    .kanji("葺", "fu(ku)", "ふ(く)", "thatch, roof (a house)"),
                    .kanji("遁", "ton", "とん", "flee, retreat (遁走)"),
                    .kanji("蒐", "shuu", "しゅう", "collect (curios) (蒐集)"),
                    .kanji("跨", "mata(gu)", "また(ぐ)", "straddle, step over (跨ぐ)"),
                    .kanji("摺", "su(ru)", "す(る)", "print on cloth, fold (摺る)"),
                    .kanji("斡", "atsu", "あつ", "broker, arrange (斡旋)"),
                    .kanji("撒", "ma(ku)", "ま(く)", "sprinkle, scatter (撒く)"),
                    .kanji("撞", "dou", "どう", "strike (a bell), clash (撞着)"),
                    .kanji("撰", "sen", "せん", "anthologize, select (勅撰)"),
                    .kanji("窺", "ukaga(u)", "うかが(う)", "peep at, watch for (窺う)"),
                    .kanji("擢", "teki", "てき", "pick out (抜擢)"),
                    .kanji("瞥", "betsu", "べつ", "glance (一瞥)"),
                    .kanji("曝", "baku", "ばく", "lay bare, expose (曝露)"),
                    .kanji("纏", "mato(u)", "まと(う)", "wrap around, coil (纏う)")
                ]
            )
        ],
        lessonOrder: "及諸臨略為致懸至是御斉唯之概須随啓也尚召偶該如幾宜猶吾羅遍又沙其翔逓甚乃漱謹此某於逢已讃湛挺綜播衷逐惟只恣寓坐偲蒙蒔或附但凌弛且汰虞遵亦哉耶捺竣詢頌爾諄僅詮頓云勿尤乎曳汝而迄庇汲沌些忽俄恰按殆臥俱套挽晒栖穿耽莫訊倦堵徠悉掠掬牽畢訣捲斯棲焚疏葺裡遁牒稟蒐跨嘗摺斡歎頗撒撞撰窺諺謂擢瞥寵曝顚纏"
    )
}
