import Foundation

extension MojiAlphabetData {
    static let kanjiAnimals = MojiPageDefinition(
        page: .kanji(.animals),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "animals",
                title: "Animal world",
                subtitle: "Beasts, birds, fish and insects",
                columns: 4,
                cells: [
                    .kanji("馬", "uma", "うま", "horse"),
                    .kanji("雄", "osu", "おす", "male, hero (英雄)"),
                    .kanji("羽", "hane", "はね", "feather, wing (羽)"),
                    .kanji("尾", "o", "お", "tail (尻尾)"),
                    .kanji("鹿", "shika", "しか", "deer (鹿)"),
                    .kanji("群", "mu(re)", "む(れ)", "flock, herd (群れ)"),
                    .kanji("鳥", "tori", "とり", "bird"),
                    .kanji("熊", "kuma", "くま", "bear (animal)"),
                    .kanji("翼", "tsubasa", "つばさ", "wing (翼)"),
                    .kanji("牛", "ushi", "うし", "cow"),
                    .kanji("魚", "sakana", "さかな", "fish"),
                    .kanji("鳴", "na(ku)", "な(く)", "chirp, ring (鳴る)"),
                    .kanji("犬", "inu", "いぬ", "dog"),
                    .kanji("虫", "mushi", "むし", "insect"),
                    .kanji("亀", "kame", "かめ", "turtle (亀)"),
                    .kanji("鶴", "tsuru", "つる", "crane (bird) (鶴)"),
                    .kanji("飼", "ka(u)", "か(う)", "keep (a pet) (飼う)"),
                    .kanji("鯨", "kujira", "くじら", "whale"),
                    .kanji("巣", "su", "す", "nest (巣)"),
                    .kanji("鳩", "hato", "はと", "pigeon, dove (鳩)"),
                    .kanji("柴", "shiba", "しば", "brushwood (柴犬)"),
                    .kanji("虎", "tora", "とら", "tiger (虎)"),
                    .kanji("鷹", "taka", "たか", "hawk (鷹)"),
                    .kanji("猪", "inoshishi", "いのしし", "wild boar (猪)"),
                    .kanji("昆", "kon", "こん", "insect, kelp (昆虫)"),
                    .kanji("猫", "neko", "ねこ", "cat"),
                    .kanji("獣", "kemono", "けもの", "beast (獣)"),
                    .kanji("蛇", "hebi", "へび", "snake (蛇)"),
                    .kanji("猿", "saru", "さる", "monkey (猿)"),
                    .kanji("狩", "ka(ru)", "か(る)", "hunt (狩り)"),
                    .kanji("貝", "kai", "かい", "shellfish"),
                    .kanji("鴨", "kamo", "かも", "wild duck (鴨)"),
                    .kanji("畜", "chiku", "ちく", "livestock (家畜)"),
                    .kanji("猟", "ryou", "りょう", "game hunting (猟師)"),
                    .kanji("羊", "hitsuji", "ひつじ", "sheep"),
                    .kanji("雀", "suzume", "すずめ", "sparrow (雀)"),
                    .kanji("豚", "buta", "ぶた", "pig"),
                    .kanji("殻", "kara", "から", "shell, husk (殻)"),
                    .kanji("鶏", "niwatori", "にわとり", "chicken (鶏肉)"),
                    .kanji("獅", "shi", "し", "lion (獅子)"),
                    .kanji("鷲", "washi", "わし", "eagle (鷲)"),
                    .kanji("雌", "mesu", "めす", "female (雌)"),
                    .kanji("蝶", "chou", "ちょう", "butterfly (蝶)"),
                    .kanji("蛍", "hotaru", "ほたる", "firefly (蛍)"),
                    .kanji("烏", "karasu", "からす", "crow (烏)"),
                    .kanji("牙", "kiba", "きば", "fang, tusk (牙)"),
                    .kanji("蚊", "ka", "か", "mosquito (蚊)"),
                    .kanji("狼", "ookami", "おおかみ", "wolf (狼)"),
                    .kanji("燕", "tsubame", "つばめ", "barn swallow (燕)"),
                    .kanji("鮎", "ayu", "あゆ", "sweetfish (鮎)"),
                    .kanji("蜂", "hachi", "はち", "bee, wasp (蜂)"),
                    .kanji("雛", "hina", "ひな", "chick, doll (雛祭り)"),
                    .kanji("蚕", "kaiko", "かいこ", "silkworm (蚕)"),
                    .kanji("餌", "esa", "えさ", "feed, bait (餌)"),
                    .kanji("鯉", "koi", "こい", "carp (鯉)"),
                    .kanji("蟹", "kani", "かに", "crab (蟹)"),
                    .kanji("鯛", "tai", "たい", "sea bream (鯛)"),
                    .kanji("哺", "ho", "ほ", "nurse, suckle (哺乳類)"),
                    .kanji("鱗", "uroko", "うろこ", "scale (fish) (鱗)")
                ]
            ),
            MojiSectionDefinition(
                key: "beasts",
                title: "Birds & beasts",
                subtitle: "Wild animals, fish and legends",
                columns: 4,
                cells: [
                    .kanji("竜", "ryuu", "りゅう", "dragon"),
                    .kanji("鵬", "hou", "ほう", "roc (giant bird)"),
                    .kanji("駿", "shun", "しゅん", "fleet steed, gifted (駿馬)"),
                    .kanji("鴻", "kou", "こう", "wild swan, great"),
                    .kanji("鵜", "u", "う", "cormorant (鵜飼い)"),
                    .kanji("牡", "bo", "ぼ", "male beast, peony (牡丹)"),
                    .kanji("鳳", "hou", "ほう", "phoenix (鳳凰)"),
                    .kanji("鷺", "sagi", "さぎ", "heron"),
                    .kanji("雁", "kari", "かり", "wild goose"),
                    .kanji("隼", "hayabusa", "はやぶさ", "falcon"),
                    .kanji("彪", "hyou", "ひょう", "tiger stripes"),
                    .kanji("犀", "sai", "さい", "rhinoceros"),
                    .kanji("啄", "taku", "たく", "peck (啄木鳥)"),
                    .kanji("蹄", "hizume", "ひづめ", "hoof"),
                    .kanji("鱒", "masu", "ます", "trout"),
                    .kanji("蝦", "ebi", "えび", "shrimp, prawn"),
                    .kanji("麟", "rin", "りん", "female qilin (麒麟)"),
                    .kanji("仔", "ko", "こ", "young (animal), fine detail (仔細)"),
                    .kanji("兎", "usagi", "うさぎ", "rabbit, hare"),
                    .kanji("豹", "hyou", "ひょう", "leopard"),
                    .kanji("凰", "ou", "おう", "female phoenix (鳳凰)"),
                    .kanji("羚", "rei", "れい", "antelope (羚羊)"),
                    .kanji("厩", "kyuu", "きゅう", "stable, barn (厩舎)"),
                    .kanji("禽", "kin", "きん", "fowl, captive (家禽)"),
                    .kanji("鳶", "tobi", "とび", "black kite"),
                    .kanji("螺", "ra", "ら", "spiral, conch (螺旋)"),
                    .kanji("蟬", "semi", "せみ", "cicada"),
                    .kanji("麒", "ki", "き", "qilin, giraffe (麒麟)"),
                    .kanji("鰯", "iwashi", "いわし", "sardine"),
                    .kanji("鷗", "kamome", "かもめ", "seagull")
                ]
            )
        ],
        lessonOrder: "馬雄羽尾鹿群鳥熊竜翼牛魚鳴犬虫亀鶴飼鯨巣鳩柴虎鷹猪昆猫鵬獣蛇猿狩貝鴨駿畜猟羊雀豚殻鶏獅鷲雌蝶蛍烏牙鴻鵜蚊狼燕牡鳳鷺雁鮎蜂隼雛蚕餌鯉彪蟹犀鯛哺啄蹄鱒鱗蝦麟仔兎豹凰羚厩禽鳶螺蟬麒鰯鷗"
    )
}
