import Foundation

extension MojiAlphabetData {
    static let kanjiPlants = MojiPageDefinition(
        page: .kanji(.plants),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "trees",
                title: "Trees",
                subtitle: "Timber and groves, often in surnames",
                columns: 4,
                cells: [
                    .kanji("木", "ki", "き", "tree"),
                    .kanji("松", "matsu", "まつ", "pine"),
                    .kanji("森", "mori", "もり", "forest"),
                    .kanji("林", "hayashi", "はやし", "grove"),
                    .kanji("李", "sumomo", "すもも", "damson plum, Li (surname)"),
                    .kanji("梅", "ume", "うめ", "plum"),
                    .kanji("桜", "sakura", "さくら", "cherry blossom"),
                    .kanji("柏", "kashiwa", "かしわ", "kashiwa oak"),
                    .kanji("桂", "katsura", "かつら", "katsura tree, cinnamon"),
                    .kanji("桐", "kiri", "きり", "paulownia"),
                    .kanji("楊", "you", "よう", "poplar, willow (楊枝)"),
                    .kanji("楠", "kusunoki", "くすのき", "camphor tree"),
                    .kanji("榎", "enoki", "えのき", "hackberry"),
                    .kanji("樺", "kaba", "かば", "birch"),
                    .kanji("槙", "maki", "まき", "yew pine"),
                    .kanji("槻", "tsuki", "つき", "zelkova"),
                    .kanji("楢", "nara", "なら", "konara oak"),
                    .kanji("橘", "tachibana", "たちばな", "tachibana orange"),
                    .kanji("桧", "hinoki", "ひのき", "Japanese cypress"),
                    .kanji("杜", "mori", "もり", "sacred grove, careless (杜撰)"),
                    .kanji("榛", "hashibami", "はしばみ", "hazel"),
                    .kanji("樟", "shou", "しょう", "camphor (樟脳)"),
                    .kanji("檀", "dan", "だん", "sandalwood, temple patron (檀家)"),
                    .kanji("樫", "kashi", "かし", "evergreen oak"),
                    .kanji("梓", "azusa", "あずさ", "catalpa, printing block (上梓)"),
                    .kanji("柊", "hiiragi", "ひいらぎ", "holly"),
                    .kanji("柾", "masa", "まさ", "straight grain, spindle tree"),
                    .kanji("梢", "kozue", "こずえ", "treetop, twig"),
                    .kanji("梧", "go", "ご", "parasol tree (梧桐)"),
                    .kanji("椋", "muku", "むく", "muku tree, starling (椋鳥)"),
                    .kanji("椰", "yashi", "やし", "coconut palm (椰子)"),
                    .kanji("楓", "kaede", "かえで", "maple"),
                    .kanji("柑", "kan", "かん", "citrus (蜜柑)"),
                    .kanji("柘", "tsuge", "つげ", "boxwood (柘植)"),
                    .kanji("梛", "nagi", "なぎ", "nagi tree, shrine tree"),
                    .kanji("椛", "momiji", "もみじ", "autumn leaves, birch")
                ]
            ),
            MojiSectionDefinition(
                key: "farming",
                title: "Plants & farming",
                subtitle: "Crops, trees and fields",
                columns: 4,
                cells: [
                    .kanji("幹", "miki", "みき", "trunk, core (新幹線)"),
                    .kanji("葉", "ha", "は", "leaf"),
                    .kanji("竹", "take", "たけ", "bamboo"),
                    .kanji("根", "ne", "ね", "root"),
                    .kanji("樹", "ju", "じゅ", "standing tree (樹木)"),
                    .kanji("稲", "ine", "いね", "rice plant (稲)"),
                    .kanji("芝", "shiba", "しば", "lawn, turf (芝生)"),
                    .kanji("漁", "gyo", "ぎょ", "fishing (漁業)"),
                    .kanji("杉", "sugi", "すぎ", "cedar"),
                    .kanji("麻", "asa", "あさ", "hemp, numb (麻酔)"),
                    .kanji("柳", "yanagi", "やなぎ", "willow"),
                    .kanji("畑", "hatake", "はたけ", "dry field, farm (畑)"),
                    .kanji("茂", "shige(ru)", "しげ(る)", "grow thick (茂る)"),
                    .kanji("牧", "boku", "ぼく", "pasture (牧場)"),
                    .kanji("殖", "shoku", "しょく", "breed, multiply (繁殖)"),
                    .kanji("枝", "eda", "えだ", "branch"),
                    .kanji("熟", "juku", "じゅく", "ripen, mature (成熟)"),
                    .kanji("培", "bai", "ばい", "cultivate (栽培)"),
                    .kanji("肥", "hi", "ひ", "fertilizer, fat (肥料)"),
                    .kanji("栽", "sai", "さい", "planting (盆栽)"),
                    .kanji("拓", "taku", "たく", "open up land (開拓)"),
                    .kanji("咲", "sa(ku)", "さ(く)", "bloom (咲く)"),
                    .kanji("葛", "kuzu", "くず", "kudzu, conflict (葛藤)"),
                    .kanji("耕", "tagaya(su)", "たがや(す)", "till, plow (耕す)"),
                    .kanji("鎌", "kama", "かま", "sickle (鎌倉)"),
                    .kanji("穫", "kaku", "かく", "harvest (収穫)"),
                    .kanji("桑", "kuwa", "くわ", "mulberry"),
                    .kanji("穂", "ho", "ほ", "ear of grain (稲穂)"),
                    .kanji("芽", "me", "め", "bud, sprout (芽)"),
                    .kanji("苗", "nae", "なえ", "seedling (苗字)"),
                    .kanji("刈", "ka(ru)", "か(る)", "mow, crop (刈る)"),
                    .kanji("笹", "sasa", "ささ", "bamboo grass"),
                    .kanji("穀", "koku", "こく", "grain, cereal (穀物)"),
                    .kanji("枯", "ka(reru)", "か(れる)", "wither (枯れる)"),
                    .kanji("稔", "mino(ru)", "みの(る)", "bear fruit (稔る)"),
                    .kanji("酪", "raku", "らく", "dairy (酪農)"),
                    .kanji("茎", "kuki", "くき", "stem, stalk"),
                    .kanji("藻", "mo", "も", "seaweed, algae (海藻)"),
                    .kanji("薪", "maki", "まき", "firewood"),
                    .kanji("畝", "une", "うね", "furrow, ridge (畝)"),
                    .kanji("穣", "jou", "じょう", "rich harvest (豊穣)"),
                    .kanji("藁", "wara", "わら", "straw"),
                    .kanji("墾", "kon", "こん", "break new ground (開墾)"),
                    .kanji("沃", "yoku", "よく", "fertile (肥沃)"),
                    .kanji("萎", "na(eru)", "な(える)", "wilt, droop (萎える)"),
                    .kanji("禾", "ka", "か", "grain plant (禾)"),
                    .kanji("籾", "momi", "もみ", "unhulled rice (籾)"),
                    .kanji("圃", "ho", "ほ", "farm plot (田圃)")
                ]
            ),
            MojiSectionDefinition(
                key: "flowers",
                title: "Flowers & grasses",
                subtitle: "Blossoms, reeds and wild herbs",
                columns: 4,
                cells: [
                    .kanji("花", "hana", "はな", "flower"),
                    .kanji("草", "kusa", "くさ", "grass"),
                    .kanji("菊", "kiku", "きく", "chrysanthemum"),
                    .kanji("萩", "hagi", "はぎ", "bush clover"),
                    .kanji("篠", "shino", "しの", "slender bamboo (篠竹)"),
                    .kanji("菅", "suge", "すげ", "sedge (菅笠)"),
                    .kanji("荻", "ogi", "おぎ", "silver reed"),
                    .kanji("芦", "ashi", "あし", "reed, Ashiya (芦屋)"),
                    .kanji("椿", "tsubaki", "つばき", "camellia"),
                    .kanji("蓮", "hasu", "はす", "lotus"),
                    .kanji("蘭", "ran", "らん", "orchid, Holland (蘭学)"),
                    .kanji("蒲", "gama", "がま", "cattail (蒲鉾)"),
                    .kanji("茅", "kaya", "かや", "thatching reed (茅葺き)"),
                    .kanji("芥", "kai", "かい", "mustard, rubbish (芥子)"),
                    .kanji("芭", "ba", "ば", "banana plant (芭蕉)"),
                    .kanji("蕉", "shou", "しょう", "plantain, Basho (芭蕉)"),
                    .kanji("苑", "en", "えん", "imperial garden (御苑)"),
                    .kanji("葵", "aoi", "あおい", "hollyhock"),
                    .kanji("芹", "seri", "せり", "Japanese parsley"),
                    .kanji("蔭", "kage", "かげ", "shadow of trees, thanks to (お蔭)"),
                    .kanji("蔦", "tsuta", "つた", "ivy"),
                    .kanji("萱", "kaya", "かや", "day lily, thatch grass"),
                    .kanji("芙", "fu", "ふ", "cotton rose (芙蓉)"),
                    .kanji("蕨", "warabi", "わらび", "bracken fern"),
                    .kanji("葦", "ashi", "あし", "common reed"),
                    .kanji("蕃", "ban", "ばん", "overgrow, barbarian (蕃族)"),
                    .kanji("叢", "sou", "そう", "thicket, series (叢書)"),
                    .kanji("茉", "matsu", "まつ", "jasmine (茉莉花)"),
                    .kanji("莉", "ri", "り", "jasmine bloom (茉莉)"),
                    .kanji("莞", "kan", "かん", "smile broadly (莞爾)"),
                    .kanji("菖", "shou", "しょう", "iris (菖蒲)"),
                    .kanji("菫", "sumire", "すみれ", "violet"),
                    .kanji("蓉", "you", "よう", "rose mallow, lotus (芙蓉)"),
                    .kanji("蕗", "fuki", "ふき", "butterbur"),
                    .kanji("苔", "koke", "こけ", "moss"),
                    .kanji("桔", "kitsu", "きつ", "bellflower (桔梗)"),
                    .kanji("萊", "rai", "らい", "goosefoot, Penglai (蓬萊)"),
                    .kanji("蓬", "yomogi", "よもぎ", "mugwort"),
                    .kanji("蔓", "tsuru", "つる", "vine, tendril"),
                    .kanji("蕾", "tsubomi", "つぼみ", "flower bud")
                ]
            )
        ],
        lessonOrder: "木幹葉松花竹森根林草樹稲芝漁杉麻李柳畑茂梅桜菊牧殖枝熟培肥栽拓咲萩葛篠菅耕鎌柏荻穫桑桂穂桐芽苗芦刈笹穀枯稔楊椿蓮蘭蒲茅楠芥榎樺槙槻酪茎芭楢蕉橘桧苑杜葵藻芹蔭薪榛蔦萱芙樟檀樫梓蕨畝葦蕃叢穣藁墾茉柊柾莉莞梢梧菖菫椋椰楓蓉蕗沃萎禾苔柑柘籾圃桔梛椛萊蓬蔓蕾"
    )
}
