import Foundation

extension MojiAlphabetData {
    static let kanjiReligion = MojiPageDefinition(
        page: .kanji(.religion),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "rites",
                title: "Rites & spirits",
                subtitle: "Temples, funerals, ghosts and fortune",
                columns: 4,
                cells: [
                    .kanji("神", "kami", "かみ", "god"),
                    .kanji("亡", "na(kunaru)", "な(くなる)", "pass away, the late (亡くなる)"),
                    .kanji("占", "urana(u)", "うらな(う)", "divine, occupy (占い)"),
                    .kanji("吉", "kichi", "きち", "good luck (大吉)"),
                    .kanji("葬", "sou", "そう", "funeral, bury (葬式)"),
                    .kanji("仏", "hotoke", "ほとけ", "Buddha"),
                    .kanji("寺", "tera", "てら", "temple"),
                    .kanji("喪", "mo", "も", "mourning, loss (喪失)"),
                    .kanji("宗", "shuu", "しゅう", "religion"),
                    .kanji("戒", "kai", "かい", "caution, commandment (警戒)"),
                    .kanji("祭", "matsuri", "まつり", "festival"),
                    .kanji("聖", "sei", "せい", "holy, saint (聖書)"),
                    .kanji("祥", "shou", "しょう", "good omen (発祥)"),
                    .kanji("墓", "haka", "はか", "grave (墓)"),
                    .kanji("浄", "jou", "じょう", "purify (浄化)"),
                    .kanji("拝", "oga(mu)", "おが(む)", "worship, pray to (拝む)"),
                    .kanji("霊", "rei", "れい", "spirit, ghost"),
                    .kanji("祈", "ino(ru)", "いの(る)", "pray"),
                    .kanji("魔", "ma", "ま", "magic, devil"),
                    .kanji("獄", "goku", "ごく", "hell, prison (地獄)"),
                    .kanji("鬼", "oni", "おに", "demon, ogre"),
                    .kanji("奉", "hou", "ほう", "dedicate, serve (奉仕)"),
                    .kanji("怪", "kai", "かい", "mystery, monster (怪獣)"),
                    .kanji("悼", "tou", "とう", "mourn (追悼)"),
                    .kanji("凶", "kyou", "きょう", "bad luck, evil (凶器)"),
                    .kanji("鐘", "kane", "かね", "temple bell (鐘)"),
                    .kanji("僧", "sou", "そう", "monk (僧侶)"),
                    .kanji("魂", "tamashii", "たましい", "soul (魂)"),
                    .kanji("慈", "ji", "じ", "mercy (慈悲)"),
                    .kanji("弔", "chou", "ちょう", "condolence (弔問)"),
                    .kanji("尼", "ama", "あま", "nun (尼)"),
                    .kanji("忌", "ki", "き", "abhor, death anniversary (一周忌)"),
                    .kanji("禅", "zen", "ぜん", "Zen (座禅)"),
                    .kanji("妖", "you", "よう", "bewitching, fairy (妖精)"),
                    .kanji("崇", "suu", "すう", "revere, worship (崇拝)"),
                    .kanji("幽", "yuu", "ゆう", "ghostly, deep (幽霊)"),
                    .kanji("逝", "sei", "せい", "die, depart (逝く)"),
                    .kanji("殉", "jun", "じゅん", "martyr (殉教)"),
                    .kanji("厄", "yaku", "やく", "misfortune, nuisance (厄介)"),
                    .kanji("呪", "noro(u)", "のろ(う)", "curse (呪い)"),
                    .kanji("怨", "on", "おん", "vengeful spirit (怨霊)"),
                    .kanji("棺", "kan", "かん", "coffin (棺桶)"),
                    .kanji("儒", "ju", "じゅ", "Confucian (儒教)"),
                    .kanji("冥", "mei", "めい", "underworld, dark (冥土)"),
                    .kanji("訃", "fu", "ふ", "obituary (訃報)"),
                    .kanji("詣", "mou(deru)", "もう(でる)", "visit a shrine (初詣)"),
                    .kanji("卜", "boku", "ぼく", "divination (卜)")
                ]
            ),
            MojiSectionDefinition(
                key: "temples",
                title: "Temples & old China",
                subtitle: "Buddhist words, shrines and dynasties",
                columns: 4,
                cells: [
                    .kanji("鄭", "tei", "てい", "Zheng (state), courteous (鄭重)"),
                    .kanji("秦", "shin", "しん", "Qin dynasty, Hata clan"),
                    .kanji("劉", "ryuu", "りゅう", "Liu (surname), kill"),
                    .kanji("幡", "hata", "はた", "banner, Hachiman (八幡)"),
                    .kanji("薩", "satsu", "さつ", "bodhisattva, Satsuma (菩薩)"),
                    .kanji("宋", "sou", "そう", "Song dynasty"),
                    .kanji("菩", "bo", "ぼ", "bodhi (菩提)"),
                    .kanji("牟", "mu", "む", "moo, Muni (釈迦牟尼)"),
                    .kanji("榊", "sakaki", "さかき", "sacred sakaki tree"),
                    .kanji("廟", "byou", "びょう", "mausoleum, shrine (霊廟)"),
                    .kanji("庵", "an", "あん", "hermitage, retreat"),
                    .kanji("魯", "ro", "ろ", "Russia (old), dull-witted"),
                    .kanji("迦", "ka", "か", "Shakya (釈迦)"),
                    .kanji("祇", "gi", "ぎ", "earthly deity, Gion (祇園)"),
                    .kanji("醍", "dai", "だい", "whey, real flavor (醍醐味)"),
                    .kanji("伽", "ka", "か", "attendance, temple hall (伽藍)"),
                    .kanji("舜", "shun", "しゅん", "Emperor Shun, rose of Sharon"),
                    .kanji("袈", "ke", "け", "monk's stole (袈裟)"),
                    .kanji("裟", "sa", "さ", "surplice (袈裟)"),
                    .kanji("巫", "miko", "みこ", "shrine maiden, shaman (巫女)"),
                    .kanji("竺", "jiku", "じく", "India (old), bamboo (天竺)"),
                    .kanji("陀", "da", "だ", "Amida, steep (阿弥陀)"),
                    .kanji("毘", "bi", "び", "Bishamon, assist (毘沙門)"),
                    .kanji("祢", "ne", "ね", "shrine priest (祢宜)"),
                    .kanji("祷", "tou", "とう", "prayer, invocation (祈祷)"),
                    .kanji("蔣", "shou", "しょう", "Jiang (surname), wild rice"),
                    .kanji("醐", "go", "ご", "ghee (醍醐)")
                ]
            )
        ],
        lessonOrder: "神亡占吉葬仏寺喪宗戒祭聖祥墓浄拝霊祈魔獄鬼奉怪悼凶鐘僧鄭魂慈弔尼忌秦禅劉幡妖崇薩幽逝宋殉菩牟榊廟庵厄呪怨魯迦棺儒祇醍伽冥訃舜袈裟詣卜巫竺陀毘祢祷蔣醐"
    )
}
