import Foundation

extension MojiAlphabetData {
    static let kanjiThinking = MojiPageDefinition(
        page: .kanji(.thinking),
        idPrefix: "j",
        sections: [
            MojiSectionDefinition(
                key: "mind",
                title: "Mind & words",
                subtitle: "Seeing, hearing, thinking and saying",
                columns: 4,
                cells: [
                    .kanji("見", "mi(ru)", "み(る)", "see"),
                    .kanji("言", "i(u)", "い(う)", "say"),
                    .kanji("意", "i", "い", "intention, meaning"),
                    .kanji("思", "omo(u)", "おも(う)", "think"),
                    .kanji("話", "hana(su)", "はな(す)", "talk"),
                    .kanji("考", "kanga(eru)", "かんが(える)", "consider"),
                    .kanji("知", "shi(ru)", "し(る)", "know"),
                    .kanji("信", "shin", "しん", "believe, trust"),
                    .kanji("聞", "ki(ku)", "き(く)", "hear, ask"),
                    .kanji("説", "setsu", "せつ", "explain, theory"),
                    .kanji("申", "mou(su)", "もう(す)", "say (humble)"),
                    .kanji("呼", "yo(bu)", "よ(ぶ)", "call"),
                    .kanji("頼", "tano(mu)", "たの(む)", "ask a favor"),
                    .kanji("覚", "obo(eru)", "おぼ(える)", "memorize"),
                    .kanji("願", "nega(u)", "ねが(う)", "wish, request"),
                    .kanji("訳", "wake", "わけ", "translation (わけ)"),
                    .kanji("忘", "wasu(reru)", "わす(れる)", "forget")
                ]
            ),
            MojiSectionDefinition(
                key: "ideas",
                title: "Ideas",
                subtitle: "Abstract words for thinking and discussing",
                columns: 4,
                cells: [
                    .kanji("派", "ha", "は", "faction"),
                    .kanji("原", "gen", "げん", "original, field"),
                    .kanji("解", "to(ku)", "と(く)", "solve, untie"),
                    .kanji("認", "mito(meru)", "みと(める)", "recognize, admit"),
                    .kanji("件", "ken", "けん", "matter, case"),
                    .kanji("基", "moto", "もと", "foundation"),
                    .kanji("勢", "sei", "せい", "force, vigor"),
                    .kanji("容", "you", "よう", "content, contain"),
                    .kanji("応", "ou", "おう", "respond"),
                    .kanji("談", "dan", "だん", "conversation"),
                    .kanji("状", "jou", "じょう", "condition, letter"),
                    .kanji("構", "kama(u)", "かま(う)", "structure, mind"),
                    .kanji("比", "kura(beru)", "くら(べる)", "compare"),
                    .kanji("断", "kotowa(ru)", "ことわ(る)", "refuse, cut off"),
                    .kanji("態", "tai", "たい", "attitude, state"),
                    .kanji("想", "sou", "そう", "idea, imagine"),
                    .kanji("象", "shou", "しょう", "phenomenon, elephant"),
                    .kanji("限", "kagi(ru)", "かぎ(る)", "limit"),
                    .kanji("準", "jun", "じゅん", "standard, semi-"),
                    .kanji("姿", "sugata", "すがた", "figure, appearance"),
                    .kanji("極", "kyoku", "きょく", "pole, extreme"),
                    .kanji("影", "kage", "かげ", "shadow"),
                    .kanji("含", "fuku(mu)", "ふく(む)", "include"),
                    .kanji("観", "kan", "かん", "view, outlook"),
                    .kanji("型", "kata", "かた", "type, mold"),
                    .kanji("況", "kyou", "きょう", "situation"),
                    .kanji("識", "shiki", "しき", "discern, know"),
                    .kanji("響", "hibi(ku)", "ひび(く)", "echo, affect"),
                    .kanji("程", "hodo", "ほど", "extent"),
                    .kanji("効", "kou", "こう", "effect"),
                    .kanji("否", "hi", "ひ", "no, deny"),
                    .kanji("系", "kei", "けい", "lineage, -type"),
                    .kanji("単", "tan", "たん", "simple, single"),
                    .kanji("因", "in", "いん", "cause, factor"),
                    .kanji("標", "hyou", "ひょう", "mark, target"),
                    .kanji("創", "sou", "そう", "creative, found (創作)"),
                    .kanji("囲", "kako(mu)", "かこ(む)", "surround"),
                    .kanji("雑", "zatsu", "ざつ", "miscellaneous"),
                    .kanji("徴", "chou", "ちょう", "sign, feature"),
                    .kanji("像", "zou", "ぞう", "statue, image"),
                    .kanji("賛", "san", "さん", "approve"),
                    .kanji("複", "fuku", "ふく", "duplicate, complex"),
                    .kanji("簡", "kan", "かん", "simplicity"),
                    .kanji("純", "jun", "じゅん", "pure"),
                    .kanji("誤", "go", "ご", "error"),
                    .kanji("較", "kaku", "かく", "contrast"),
                    .kanji("礎", "so", "そ", "cornerstone (基礎)"),
                    .kanji("践", "sen", "せん", "put into practice (実践)"),
                    .kanji("擬", "gi", "ぎ", "mock, simulate (模擬)"),
                    .kanji("汎", "han", "はん", "pan-, general (汎用)"),
                    .kanji("倣", "nara(u)", "なら(う)", "follow suit, emulate"),
                    .kanji("喩", "yu", "ゆ", "metaphor (比喩)")
                ]
            ),
            MojiSectionDefinition(
                key: "speech",
                title: "Speaking",
                subtitle: "Saying, asking, praising and scolding",
                columns: 4,
                cells: [
                    .kanji("述", "no(beru)", "の(べる)", "mention, describe (述べる)"),
                    .kanji("称", "shou", "しょう", "title, praise (名称)"),
                    .kanji("促", "unaga(su)", "うなが(す)", "urge, prompt (促す)"),
                    .kanji("勧", "susu(meru)", "すす(める)", "advise, urge (勧める)"),
                    .kanji("喚", "kan", "かん", "yell, summon (召喚)"),
                    .kanji("唱", "shou", "しょう", "chant, sing (合唱)"),
                    .kanji("句", "ku", "く", "phrase, haiku verse (俳句)"),
                    .kanji("唆", "sa", "さ", "suggest, incite (示唆)"),
                    .kanji("黙", "dama(ru)", "だま(る)", "be silent (黙る)"),
                    .kanji("尋", "tazu(neru)", "たず(ねる)", "inquire (尋ねる)"),
                    .kanji("叫", "sake(bu)", "さけ(ぶ)", "shout, scream (叫ぶ)"),
                    .kanji("諭", "sato(su)", "さと(す)", "admonish, reason with (諭す)"),
                    .kanji("誓", "chika(u)", "ちか(う)", "vow, swear (誓う)"),
                    .kanji("仰", "ao(gu)", "あお(ぐ)", "look up to, say (仰る)"),
                    .kanji("冗", "jou", "じょう", "joke, redundant (冗談)"),
                    .kanji("喝", "katsu", "かつ", "bellow, applause (喝采)"),
                    .kanji("吟", "gin", "ぎん", "recite, scrutinize (吟味)"),
                    .kanji("褒", "ho(meru)", "ほ(める)", "praise (褒める)"),
                    .kanji("暢", "chou", "ちょう", "fluent (流暢)"),
                    .kanji("綴", "tsuzu(ru)", "つづ(る)", "spell, bind (綴る)"),
                    .kanji("伺", "ukaga(u)", "うかが(う)", "ask, visit (humble) (伺う)"),
                    .kanji("叱", "shika(ru)", "しか(る)", "scold (叱る)"),
                    .kanji("挨", "ai", "あい", "greeting (挨拶)"),
                    .kanji("罵", "nonoshi(ru)", "ののし(る)", "abuse, curse (罵る)"),
                    .kanji("詫", "wa(biru)", "わ(びる)", "make amends, apology (お詫び)"),
                    .kanji("拶", "satsu", "さつ", "salutation (挨拶)"),
                    .kanji("嘲", "azake(ru)", "あざけ(る)", "ridicule (嘲笑)")
                ]
            ),
            MojiSectionDefinition(
                key: "thinking",
                title: "Thinking",
                subtitle: "Judging, guessing, remembering and doubting",
                columns: 4,
                cells: [
                    .kanji("推", "sui", "すい", "infer, push (推し)"),
                    .kanji("討", "tou", "とう", "examine, debate (検討)"),
                    .kanji("択", "taku", "たく", "select (選択)"),
                    .kanji("慮", "ryo", "りょ", "consideration (配慮)"),
                    .kanji("哲", "tetsu", "てつ", "philosophy (哲学)"),
                    .kanji("釈", "shaku", "しゃく", "interpret, release (解釈)"),
                    .kanji("妥", "da", "だ", "compromise, proper (妥協)"),
                    .kanji("憶", "oku", "おく", "memory (記憶)"),
                    .kanji("偏", "hen", "へん", "biased, lopsided (偏見)"),
                    .kanji("謀", "bou", "ぼう", "plot, scheme (陰謀)"),
                    .kanji("鑑", "kan", "かん", "appraise, guidebook (図鑑)"),
                    .kanji("悟", "sato(ru)", "さと(る)", "realize, resolve (覚悟)"),
                    .kanji("勘", "kan", "かん", "intuition, hunch (勘違い)"),
                    .kanji("幻", "maboroshi", "まぼろし", "illusion, phantom (幻想)"),
                    .kanji("把", "ha", "は", "grasp, get the picture (把握)"),
                    .kanji("眺", "naga(meru)", "なが(める)", "gaze at, view (眺め)"),
                    .kanji("錯", "saku", "さく", "confused, mix-up (錯覚)"),
                    .kanji("肯", "kou", "こう", "affirm (肯定)"),
                    .kanji("妄", "mou", "もう", "delusion (妄想)")
                ]
            )
        ],
        lessonOrder: "見言意思話派原解考認知信件基勢容応談状構聞説比断態述想象限準姿極影含観型況申識呼響推程討効否系単因標頼覚創囲雑択徴像賛願複慮簡称促純訳勧哲釈妥喚唱忘誤較礎句唆憶黙偏謀鑑尋悟叫諭勘幻誓把践仰眺錯冗肯喝吟擬汎褒暢綴伺叱挨妄倣罵詫拶喩嘲"
    )
}
